#!/sbin/openrc-run

# fallback values for /etc/conf.d/lidarr
: ${command_user:=lidarr:lidarr}
: ${directory:=/var/lib/lidarr}
: ${logdir:=/var/log/lidarr}
: ${umask:=0002}

name=lidarr
description="Lidarr daemon"
command="/usr/lib/lidarr/bin/Lidarr"
command_args="-nobrowser -data=$directory"
command_background=true

pidfile="/run/$name.pid"
output_log="$logdir/output.log"
error_log="$logdir/error.log"

depend() {
	need net
	use dns logger netmount
}

start_pre() {
	checkpath -d -o "$command_user" "$directory" "$logdir"
	checkpath -f -o "$command_user" "$output_log" "$error_log"
}
