diff --git a/Makefile b/Makefile
index c231153..5a595b4 100644
--- a/Makefile
+++ b/Makefile
@@ -21,7 +21,7 @@ GTK   = `pkg-config --libs --cflags gtk+-3.0` `pkg-config --libs x11`
 GTK  += `pkg-config --libs --cflags $(APPINDICATOR)`
 LIBAV = `pkg-config --libs --cflags libswscale libavutil`
 JPEG  = `pkg-config --libs --cflags libturbojpeg`
-USBMUXD := `pkg-config --libs --cflags $(USBMUXD)`
+USBMUXD := `pkg-config --libs --cflags $(USBMUXD)-2.0`
 
 LIBS  = -lspeex -lasound -lpthread -lm
 SRC   = src/connection.c src/settings.c src/decoder*.c src/av.c src/usb.c src/queue.c
