#!/sbin/runscript

depend() {
	provide logger
}

start() {
	ebegin "Starting busybox system logging"
	start-stop-daemon --start --exec /usr/sbin/klogd -- ${KLOGD_OPTS}
	start-stop-daemon --start --exec /usr/sbin/syslogd -- ${SYSLOGD_OPTS}
	eend $?
}

stop () {
	ebegin "Stopping busybox system logging"
	start-stop-daemon --stop --exec /usr/sbin/klogd
	start-stop-daemon --stop --exec /usr/sbin/syslogd
	eend $?
}

