diff --git a/Makefile b/Makefile
index 9e20c43..ef98e3c 100644
--- a/Makefile
+++ b/Makefile
@@ -9,7 +9,7 @@ TESTS		?= t/
 NGX_CARGO	?= cargo
 
 NGINX_CONFIGURE_BASE	= \
-	auto/configure \
+	./configure \
 		--with-http_ssl_module \
 		--with-http_v2_module \
 		--with-pcre \
