#!/sbin/runscript
# SIP Express Media Server configuration file
# Follows Gentoo/AlpineLinux standards 
# GPL 2 License - N. Angelacos 2011

CONFDIR="/etc/sems"
SVC="${SVCNAME#*.}"
if [ -n "${SVC}" ] && [ "${SVCNAME}" != "sems" ]; then
        SEMSPID="/var/run/sems/${SVC}.pid"
	else
        SEMSPID="/var/run/sems/sems.pid"
	fi
SEMSCONF="${CONFDIR}/${SVC}.conf"
daemon=/usr/sbin/sems

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting  ${SVCNAME}"
	echo $SEMSPID   $SEMSCONF
	start-stop-daemon --start --quiet --pidfile $SEMSPID --exec $daemon \
		-- \
		-u sems \
		-g sems \
		-P $SEMSPID \
		-f $SEMSCONF
	eend $?
}

stop() {
	ebegin "Stopping  ${SVCNAME}"
	start-stop-daemon --stop --quiet --pidfile $SEMSPID
	eend $?
}
