#!/bin/sh


[ -x /usr/bin/etckeeper ] || exit
[ -x /usr/bin/git ] || exit
[ -x /usr/bin/find ] || exit

AVOID_SPECIAL_FILE_WARNING=1
export AVOID_SPECIAL_FILE_WARNING

case "$1" in
	pre-commit)
		etckeeper pre-install
		;;
	post-commit)
		etckeeper post-install
		;;

	*)
		echo "$0: Un-handled action: $1"
		;;
esac
