#!/sbin/runscript

# This file is part of inetutils-syslogd
# Created for Alpine Linux by IT Offshore <developer@it-offshore.co.uk>

name=syslogd
daemon=/usr/sbin/$name
config_file="/etc/syslog.conf"

depend() {
	need clock hostname localmount
        provide logger
}

check_config() {
        [ -f "$config_file" ] || error "$config_file is missing"
}

start_pre() {
        check_config || return 1
}

start() {
	ebegin "Starting ${name}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${name}.pid \
			--exec ${daemon} -- ${SYSLOGD_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${name}"
		start-stop-daemon --stop --quiet \
			--pidfile /var/run/$name.pid \
			--exec ${daemon}
	eend $?
}

reload() {
        if [ ! -f "${PIDFILE}" ]; then
                eerror "rsyslogd not running"
                return 1
        fi

        ebegin "Re-opening intetutils-syslogd log files"
        start-stop-daemon --stop --signal HUP \
                --pidfile /var/run/$name.pid
        eend $?
}

