#!/sbin/runscript

# gpm init.d file for alpine linux.

name=gpm
daemon=/usr/sbin/${name}

depend() {
	after localmount
	use hotplug logger
}

start() {
	ebegin "Starting ${name}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${name}.pid \
			--exec ${daemon} -- ${gpm_opts}
	eend $?
}

stop() {
	ebegin "Stopping ${name}"
		start-stop-daemon --stop --quiet \
			--pidfile /var/run/${name}.pid \
			--exec ${daemon}
	eend $?
}

