
This patch was set upstream to author 2012-01-16

--- ./Makefile.orig
+++ ./Makefile
@@ -7,36 +7,42 @@
 # <dragorn> i think thats all anyone does
 # <dragorn> make is a twisted beast
 ##################################
-LDLIBS		= -lpcap
-CFLAGS		= -pipe -Wall -DOPENSSL 
-CFLAGS		+= -O2
-LDLIBS		+= -lcrypto
-CFLAGS		+= -g3 -ggdb
-#CFLAGS		+= -static
+
+CFLAGS		?= -O2 -g3 -ggdb -pipe
+
+PCAP_LIBS	= -lpcap
+CRYPTO_LIBS	= -lcrypto
+CRYPTO_CFLAGS	= -DOPENSSL
+
+LDLIBS		= $(PCAP_LIBS) $(CRYPTO_LIBS)
+
 PROGOBJ		= md5.o sha1.o utils.o cowpatty.o genpmk.o
 PROG		= cowpatty genpmk
 BINDIR		= /usr/local/bin
 
-all: $(PROGOBJ) $(PROG)
+OBJS_cowpatty	= cowpatty.o md5.o sha1.o utils.o
+OBJS_genpmk	= genpmk.o md5.o sha1.o utils.o
 
-cowpatty: common.h md5.c md5.h sha1.h cowpatty.c cowpatty.h sha1.c \
-            sha1.h utils.c utils.h
-	$(CC) $(CFLAGS) cowpatty.c -o cowpatty utils.o md5.o sha1.o $(LDLIBS)
+all: $(PROG)
 
-genpmk: genpmk.c cowpatty.h utils.h sha1.h common.h
-	$(CC) $(CFLAGS) genpmk.c -o genpmk utils.o sha1.o $(LDLIBS)
+cowpatty: $(OBJS_cowpatty)
+	$(CC) $(CFLAGS) -o $@ $(OBJS_cowpatty) $(LDLIBS)
 
-utils: utils.c utils.h
-	$(CC) $(CFLAGS) utils.c -c
+genpmk: $(OBJS_genpmk)
+	$(CC) $(CFLAGS) -o $@ $(OBJS_genpmk) $(LDLIBS)
 
-md5: md5.c md5.h
-	$(CC) $(CFLAGS) md5.c -c
+cowpatty.o: cowpatty.h common.h utils.h sha1.h md5.h radiotap.h
+genpmk.o: cowpatty.h common.h utils.h sha1.h
+md5.o: common.h md5.h
+sha1.o: common.h sha1.h
+utils.o: utils.h radiotap.h
+md5.o: md5.h
 
-sha1: sha1.c sha1.h
-	$(CC) $(CFLAGS) sha1.c -c
+%.o: %.c
+	$(CC) $(CFLAGS) $(CRYPTO_CFLAGS) $(CFLAGS_$@) -c $<
 
 clean:
-	@rm $(PROGOBJ) $(PROG)
+	@rm -f $(PROGOBJ) $(PROG) *.o
 
 strip:
 	@ls -l $(PROG)
@@ -45,7 +51,9 @@
 
 install: all
 	install -d $(DESTDIR)$(BINDIR)
-	install -m 755 $(PROG) $(BINDIR)$(DESTDIR)
+	install -m 755 $(PROG) $(DESTDIR)$(BINDIR)
 
 love:
 	@echo "Not right now, I have a headache."
+
+
