diff --git a/Makefile b/Makefile
index 9ce889d..e9ca9db 100644
--- a/Makefile
+++ b/Makefile
@@ -16,10 +16,10 @@ xterm256lut.h: xterm256lut_gen.py
 	python $< > $@
 
 lolcat: lolcat.c xterm256lut.h
-	$(CC) $(CFLAGS) -o $@ $< $(LIBS)
+	$(CC) $(CFLAGS) -o $@ $< $(LIBS) $(LDFLAGS)
 
 censor: censor.c
-	$(CC) $(CFLAGS) -o $@ $< $(LIBS)
+	$(CC) $(CFLAGS) -o $@ $< $(LIBS) $(LDFLAGS)
 
 install: lolcat censor
 	install lolcat $(DESTDIR)/lolcat
