#!/sbin/openrc-run

name="ProFTPD"
description="ProFTPD FTP Server"

pidfile="/run/proftpd/proftpd.pid"
command="/usr/sbin/proftpd"
command_args="-n"
command_background="yes"
required_files="/etc/proftpd/proftpd.conf"
extra_commands="checkconfig"
extra_started_commands="reload"
description_checkconfig="Check configuration"
description_reload="Reload configuration"

depend() {
	need net
	use logger dns
	after firewall
}

checkconfig() {
	$command -t
}

start_pre() {
	checkpath --directory ${pidfile%/*}
	checkconfig >/dev/null 2>&1
}

reload() {
	ebegin "Reloading ${name:-$RC_SVCNAME}"
	checkconfig >/dev/null 2>&1 && start-stop-daemon --signal HUP --pidfile $pidfile
	eend $?
}
