.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CORKSCREW 1 "November 22, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
corkscrew \- Tunnel TCP connections through HTTP proxies
.SH SYNOPSIS
.B corkscrew
.BR 
proxy
.BR 
proxyport 
.BR
targethost
.BR
targetport
.BR
[ authfile ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR corkscrew
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.

corkscrew is a simple tool to tunnel TCP connections through an HTTP
proxy supporting the CONNECT method. It reads stdin and writes to
stdout during the connection, just like netcat.
It can be used for instance to connect to an SSH server running on
a remote 443 port through a strict HTTPS proxy.


.SH PARAMETERS

.TP
.B proxy
This is the name of the host running the HTTP proxy.
.TP
.B proxyport
This is the port on which to connect on the proxy.
.TP
.B target
This is the host to reach through the proxy.
.TP
.B targetport
This is the port to connect to on the target host.

.SH COMMON USAGE

The common usage of corkscrew is to put the following line in your
ssh_config:

ProxyCommand corkscrew proxy proxyport %h %p

This will let your ssh connection go through the proxy with the help
of corkscrew.

.SH AUTH FILE

The auth file is made of one single line containing your username and
password in the form:

username:password

You should add the path to your auth file in the proxy command
described above:

ProxyCommand corkscrew proxy proxyport %h %p auth-file

.SH "SEE ALSO"
.IX Header "SEE ALSO"
\&\fIssh_config\fR\|(5)

.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH AUTHOR
corkscrew was written by Pat Padgett <agroman@agroman.net>.
Thomas Seyrat <tomasera@debian.org> is the debian maintainer for this
package.  This manual page was written by Laurent Fousse
<laurent@komite.net>, for the Debian GNU/Linux system (but may be used
by others).
