#!/sbin/openrc-run
#
# Init script for Alpine Linux
# (c) 2019 Francesco Colista <fcolista@alpinelinux.org>
#

command="/usr/sbin/p910nd"
pidfile="/run/p910nd/p910nd.${P910ND_NUM}.pid"
command_args="${P910ND_OPTS} ${P910ND_NUM}"

depend() {
	need localmount net
	after bootmisc
}

start_pre() {
        checkpath -d -m755 /run/p910nd
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon \
		--start \
		--pidfile ${pidfile} \
		--exec ${command} \
		-- ${command_args}
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon \
		--stop \
		--pidfile ${pidfile} \
		--exec ${command}
}
