#!/sbin/openrc-run

battery_name=${RC_SVCNAME#*.}

start_pre() {
    if [ "$battery_name" = "$RC_SVCNAME" ]; then
        eerror "$RC_SVCNAME cannot be started directly."
        eerror "please symlink $RC_SVCNAME.BAT0 -> $RC_SVCNAME"
        return 1
    fi
}

start() {
    echo $stop_threshold > /sys/class/power_supply/$battery_name/charge_control_end_threshold
    echo $start_threshold > /sys/class/power_supply/$battery_name/charge_control_start_threshold
}
stop() {
    echo 100 > /sys/class/power_supply/$battery_name/charge_control_end_threshold
    echo 0 > /sys/class/power_supply/$battery_name/charge_control_start_threshold
}

