#!/sbin/openrc-run
# Copyright 2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

supervisor=supervise-daemon
description="Kubernetes Proxy service"

if [ -e /var/lib/kubernetes/kube-proxy-flags.env ]; then
	. /var/lib/kubernetes/kube-proxy-flags.env;
fi

command="/usr/bin/kube-proxy"
command_args="${command_args} ${KUBE_PROXY_ARGS}"
: ${output_log:=/var/log/$RC_SVCNAME/$RC_SVCNAME.log}
: ${error_log:=/var/log/$RC_SVCNAME/$RC_SVCNAME.log}

depend() {
	after net
}

