#!/sbin/openrc-run

# for backward compat
case "$SVCNAME" in
snmpd) : ${OPTS:=$SNMPD_FLAGS} ;;
esac

pidfile="/var/run/${SVCNAME}.pid"
command="/usr/sbin/${SVCNAME}"
command_args="-p ${pidfile} ${OPTS}"
required_files="/etc/snmp/${SVCNAME}.conf"
extra_started_commands="reload"

depend() {
        use logger
        need net
        after firewall
}

reload() {
        ebegin "Reloading ${SVCNAME}"
        start-stop-daemon --signal HUP --pidfile ${pidfile} --name ${SVCNAME}
        eend $?
}
