#!/bin/sh -e
# Highly opinionated wrapper for Alpine Linux packaging (based on abuild-meson)

exec muon meson setup \
		"$@" \
		-Dprefix=/usr \
		-Dlibdir=/usr/lib \
		-Dlibexecdir=/usr/libexec \
		-Dbindir=/usr/bin \
		-Dsbindir=/usr/sbin \
		-Dincludedir=/usr/include \
		-Ddatadir=/usr/share \
		-Dmandir=/usr/share/man \
		-Dinfodir=/usr/share/info \
		-Dlocaledir=/usr/share/locale \
		-Dsysconfdir=/etc \
		-Dlocalstatedir=/var \
		-Dsharedstatedir=/var/lib \
		-Dbuildtype=plain \
		-Dauto_features=disabled \
		-Dwrap_mode=nodownload \
		-Ddefault_library=shared \
		-Db_lto=false \
		-Db_staticpic=true \
		-Db_pie=true \
		-Dpython.bytecompile=0 \
		-Dwerror=false
