#!/sbin/openrc-run

supervisor=supervise-daemon

name="stayrtr"
description="Simple RPKI-To-Router server. (Hard fork of GoRTR)"

command="/usr/bin/$RC_SVCNAME"
command_args="$STAYRTR_OPTS"
command_user="$RC_SVCNAME:$RC_SVCNAME"

extra_started_commands="reload"
description_reload="Reload configuration"

error_log="/var/log/$RC_SVCNAME.log"

depend() {
	need net
	after firewall
}

reload() {
	ebegin "Reloading $RC_SVCNAME configuration"
	$supervisor "$RC_SVCNAME" --signal HUP
	eend $?
}
