#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-admin/rsyslog/files/5-stable/rsyslog.initd,v 1.1 2010/10/21 07:38:29 dev-zero Exp $

opts="reload"

depend() {
	provide logger
}

start() {
	ebegin "Starting rsyslogd"
	start-stop-daemon \
		--start --quiet --exec /usr/sbin/rsyslogd \
		-- ${RSYSLOG_OPTS} -i "${PIDFILE}" -f "${CONFIGFILE}"
	eend $?
}

stop() {
	ebegin "Stopping rsyslogd"
	start-stop-daemon \
		--stop --quiet \
		--pidfile "${PIDFILE}"
	eend $?
}

reload() {
	if [ ! -f "${PIDFILE}" ]; then
		eerror "rsyslogd not running"
		return 1
	fi

	ebegin "Re-opening rsyslogd log files"
	start-stop-daemon --stop --oknodo --signal HUP \
		--pidfile "${PIDFILE}"
	eend $?
}
