#!/bin/sh

verbose=
board=
device=
dryrun=
imagedir=

get_defaults() {
	if [ -z "$board" -a -e /sys/firmware/devicetree/base/compatible ]; then
		case "$(cat /sys/firmware/devicetree/base/compatible 2>/dev/null)" in
		wand,*) board=wand ;;
		pine64,pine64-plus*) board=pine64_plus ;;
		pine64,pinebook-pro*) board=pinebook-pro-rk3399 ;;
		xunlong,orangepi-zero3*) board=orangepi_zero3 ;;
		xunlong,orangepi-3*) board=orangepi_3 ;;
		# Assume boot mode with default firmware
		riscv64-virtio) board=qemu-riscv64_smode ;;
		esac
	fi

	if [ -z "$device" ]; then
		case "$board" in
		wand|cubie|cubie2) device=/dev/mmcblk0p0 ;;
		pinebook-pro-rk3399) device=/dev/mmcblk2 ;;
		mx6cuboxi|*rk33*|pine64_plus) device=/dev/mmcblk0 ;;
		orangepi_3|orangepi_zero3) device=/dev/mmcblk0 ;;
		esac
	fi

	if [ -z "$imagedir" ]; then
		imagedir="$(realpath $(dirname $0))"
		[ -f "$imagedir/README.txt" ] || imagedir="/usr/share/u-boot"
	fi
}

die() {
	echo "ERROR: $@"
	exit 1
}

usage() {
	get_defaults

	cat <<EOF
usage: $0 [-b|--board <board-type>] [-d|--device <device>]

options:

 -b,--board <board>       Specify the board type: wand, cubie, cubie2, cuboxi, pine64-lts, etc.
                          (current default: ${board:-none})

 -d,--device <device>     Specify the device where to install u-boot
                          (current default: ${device:-none})

 -i,--imagedir <imagedir> Specify u-boot image directory
                          (current default: ${imagedir:-none})

 -n,--dry-run             Print commands but don't execute them

EOF
}

while [ $# -gt 0 ]; do
	opt="$1"
	shift
	case "$opt" in
	-b|--board)
		case "$1" in
		wand|wandboard) board="wand" ;;
		cubie|cubieboard) board="cubie" ;;
		cuboxi|mx6cuboxi) board="mx6cuboxi" ;;
		pine64-lts|pinebook|orangepi_3|orangepi_zero3|teres_i|a64-olinuxino|a64-olinuxino-emmc|nanopi_neo2|*rk33*|pine64_plus|qemu-riscv64*) board="$1" ;;
		*) usage; exit 1;;
		esac
		shift
		;;
	-d|--device)
		device="$1"
		shift
		;;
	-i|--imagedir)
		imagedir="$1"
		shift
		;;
	-n|--dry-run)
		dryrun="echo"
		;;
        --)
                break
                ;;
        -*)
                usage
                exit 1
                ;;
        esac
done

get_defaults
if [ -z "$board" -o -z "$device" -o -z "$imagedir" -o  ! -e "$imagedir" ]; then
	usage
	exit 1
fi

if [ -z "$dryrun" ]; then
	echo "Updating $board u-boot in $device in 3 seconds..."
	sleep 3
fi

(
set -e
case "$board" in
wand)
	[ -e "$imagedir/wandboard" ] || die "wandboard images not installed, apk add u-boot-wandboard"
	$dryrun dd if=$imagedir/wandboard/SPL of=$device bs=1k seek=1 status=none
	$dryrun dd if=$imagedir/wandboard/u-boot.img of=$device bs=1k seek=69 status=none
	;;
cubie|cubie2)
	[ -e "$imagedir/Cubieboard${board#cubie}" ] || die "Cubieboard images not installed, apk add u-boot-cubieboard"
	$dryrun dd if=$imagedir/Cubieboard${board#cubie}/u-boot-sunxi-with-spl.bin of=$device bs=1024 seek=8 status=none
	;;
mx6cuboxi)
	[ -e "$imagedir/mx6cuboxi" ] || die "iMX6 Cubox-i images not installed, apk add u-boot-cuboxi"
	$dryrun dd if=$imagedir/mx6cuboxi/SPL of=$device bs=1k seek=1 status=none
	$dryrun dd if=$imagedir/mx6cuboxi/u-boot.img of=$device bs=1k seek=69 status=none
	;;
pine64-lts|pinebook|orangepi_3|orangepi_zero3|teres_i|a64-olinuxino|a64-olinuxino-emmc|nanopi_neo2|pine64_plus)
	[ -e "$imagedir/$board" ] || die "sunxi images not installed, apk add u-boot-sunxi"
	$dryrun dd if=$imagedir/$board/u-boot-sunxi-with-spl.bin of=$device bs=1k seek=8 status=none
	;;
*rk33*)
	[ -e "$imagedir/$board" ] || die "$board images not installed, apk add u-boot-$board"

	echo "Writing u-boot image"
	$dryrun dd conv=notrunc if=$imagedir/$board/u-boot-rockchip.bin of=$device seek=64
	;;
qemu-riscv64|qemu-riscv64_smode)
	[ -e "$imagedir/$board" ] || die "$board images not installed, apk add u-boot-qemu"
	echo "Please copy $imagedir/$board/u-boot.bin outside of your virtual machine."
	echo "Then set -kernel path/to/copy/u-boot.bin in your next QEMU call."
	;;
esac
$dryrun sync
) || die "U-Boot installation in $device failed"

[ -z "$dryrun" ] && echo "Completed successfully."
