#!/sbin/openrc-run

description="IPMI system event log daemon"
pidfile="/var/run/$RC_SVCNAME.pid"
command="/usr/sbin/$RC_SVCNAME"

start() {
	ebegin "Starting $RC_SVCNAME"
	start-stop-daemon --start \
		--exec $command \
		--pidfile $pidfile \
		--make-pidfile \
		--quiet \
		--background \
		-- \
		$OPTIONS
	eend $?
}

stop() {
	ebegin "Stopping $RC_SVCNAME"
	start-stop-daemon --stop \
		--pidfile $pidfile
	eend $?
}
