#!/sbin/openrc-run

description="iNet wireless daemon"

: ${error_logger="logger -t iwd -p daemon.info"}

command="/usr/libexec/iwd"
command_background="yes"
command_args="
	${allowed_interfaces:+"--interfaces \"$allowed_interfaces\""}
	${ignored_interfaces:+"--nointerfaces \"$ignored_interfaces\""}
	${command_args:-}
	"
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need dbus
	before net
	keyword -shutdown
}
