#!/sbin/openrc-run

# fallback values for /etc/conf.d/knot-git
: ${command_user:=git:git}
: ${directory:=/var/lib/git}

name=knot-git
description="Knot Git server for Tangled.org"
command="/usr/bin/knot-git"
command_args="server"
command_background=true
pidfile="/run/$name.pid"

depend() {
	need net
	use dns logger
}

start_pre() {
	checkpath -d -o "$command_user" "$directory"

	if [ "$KNOT_REPO_SCAN_PATH" ]; then
		checkpath -d -m 2775 -o "git:git" "$KNOT_REPO_SCAN_PATH"
	fi

	if [ "$error_log" ]; then
		output_log="$error_log"
		checkpath -f -o "$command_user" "$output_log"
	else
		output_logger="logger -t $name -p daemon.info"
		error_logger="logger -t $name -p daemon.error"
	fi
}
