#!/bin/sh

tmp="$(mktemp -d -t cagerun.XXXXXX)"
chmod 0700 "$tmp"

trap 'rm -rf "$tmp"' EXIT HUP INT TERM

export XDG_RUNTIME_DIR="$tmp"
export WLR_RENDERER=pixman
export WLR_BACKENDS=headless

dbus-run-session -- cage -- "$@"
