#!/sbin/openrc-run

name="MPTCP Daemon"
description="MPTCP Daemon Service"

: ${error_logger="logger -t mptcpd -p daemon.info >/dev/null 2>&1"}
: ${start_wait=50}  # milliseconds

command="/usr/bin/mptcpd"
command_args="$command_args"
command_background="yes"
start_stop_daemon_args="
	${start_wait:+--wait $start_wait}
	${start_stop_daemon_args:-}
	"
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need net
	after firewall
}
