#!/sbin/runscript

NAME=3dm2
DAEMON=/usr/sbin/$NAME

depend() {
        need net
}

start() {
	ebegin "Starting ${NAME}"
	start-stop-daemon --start --quiet --background \
		--make-pidfile --pidfile /var/run/${NAME}.pid \
		--exec ${DAEMON} -- ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${NAME}"
	start-stop-daemon --stop --quiet \
		--exec ${DAEMON} \
		--pidfile /var/run/${NAME}.pid \
	eend $?
}
