#!/sbin/openrc-run

name="Drawpile Server"
description="Collaborative drawing server"
command="/usr/bin/drawpile-srv"
command_args="--database /var/lib/drawpile/guiserver.db
  --sessions /var/lib/drawpile/sessions
  --templates /etc/drawpile/templates
  --extauth https://drawpile.net/api/ext-auth/
  "
pidfile="/run/drawpile.pid"
command_background=true
command_user=drawpile:drawpile

depend() {
  need net
  after firewall
}
