#!/sbin/runscript

# Gearman server init.d file for alpine linux.

name=gearmand
daemon=/usr/sbin/$name

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting ${name}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${name}.pid \
			--chuid ${gearmand_user}:${gearmand_group} \
			--exec ${daemon} -d ${gearmand_opts}
	eend $?
}

stop() {
	ebegin "Stopping ${name}"
		start-stop-daemon --stop --quiet \
			--pidfile /var/run/$name.pid \
			--exec ${daemon}
	eend $?
}

