#!/sbin/openrc-run
supervisor=supervise-daemon

description="generic RADIUS proxy"
description_checkconfig="Check configuration"
description_reload="Reload configuration"
description_reopen="Reopen log files"

command_args_foreground="-f"

required_files="$cfgfile"

depend() {
	need net
	use dns logger netmount
}

start_pre() {
	$command $command_args -p
}

checkconfig() {
	ebegin "Checking $name configuration"

	start_pre
	eend $?
}

reload() {
	ebegin "Reloading $name configuration"
	start_pre && supervise-daemon --signal HUP
	eend $?
}

reopen() {
	ebegin "Reopening $name log files"
	supervise-daemon --signal USR1
	eend $?
}
