#!/sbin/openrc-run
supervisor=supervise-daemon

name="mautrix-linkedin"
description="Daemon for mautrix-linkedin, a Matrix-Linkedin Voice puppeting bridge"

: ${config:="/etc/mautrix-linkedin/config.yaml"}
: ${command_user:="mautrix-linkedin:mautrix-linkedin"}

command="/usr/bin/mautrix-linkedin"
command_args="-c $config $command_args"

depend() {
	need net
}

start_pre() {
	checkpath --file --owner "$command_user" "$config"
	checkpath --directory --owner "$command_user" /var/log/mautrix-linkedin
}
