#!/sbin/openrc-run

name="Laminar CI"
description="Fast and lightweight Continuous Integration server"

: ${output_logger="logger -t laminard -p daemon.info"}
: ${error_logger="logger -t laminard -p daemon.err"}

command="/usr/bin/laminard"
command_user="laminar:laminar"
command_background="yes"
directory="/var/lib/$RC_SVCNAME"
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need localmount
}

start_pre() {
	checkpath -d -o "$command_user" "$directory"

	source /etc/laminar.conf
}
