#!/sbin/openrc-run

supervisor=supervise-daemon
name=apollo
command="/usr/sbin/apollo"
pidfile="/run/apollo.pid"
extra_started_commands="reload"

depend() {
  use logger dns
  need net
  after coventry
}

stop() {
  ebegin "Stopping ${RC_SVCNAME}"
  start-stop-daemon --signal INT --pidfile "${pidfile}"
  eend $? "Failed to stop ${RC_SVCNAME}"
}

reload() {
  ebegin "Reloading ${RC_SVCNAME}"
  start-stop-daemon --signal HUP --pidfile "${pidfile}"
  eend $?
}

