#!/sbin/openrc-run

name=$RC_SVCNAME
command=/usr/bin/syncthing-inotify
command_args="${SYNCTHING_INOTIFY_ARGS}"
command_user="${SYNCTHING_INOTIFY_USER:-syncthing}"
pidfile=/run/${RC_SVCNAME}.pid
command_background=yes
start_stop_daemon_args="--stdout /var/log/$RC_SVCNAME/${RC_SVCNAME}.log --stderr /var/log/$RC_SVCNAME/${RC_SVCNAME}.log"

depend() {
        use logger dns
        need net
        after firewall
}

start_pre() {
        checkpath --directory --owner $command_user --mode 0775 \
                /var/log/$RC_SVCNAME
}

