#!/sbin/runscript

NAME=grossd
DAEMON=/usr/sbin/$NAME

depend() {
        need net
}

check_config() {
        if [ ! -e /var/db/gross/ ] ; then
                einfo "Generating Gross database..."
                install -dD -o${USER} -g${GROUP} /var/db/gross
                ${DAEMON} -Cf /etc/grossd.conf > /dev/null
        fi
}

start() {
        check_config || return 1
        ebegin "Starting ${NAME}"
        start-stop-daemon --start --quiet --background \
                --exec ${DAEMON} -- ${OPTS}
        eend $?
}

stop() {
        ebegin "Stopping ${NAME}"
        start-stop-daemon --stop --pidfile /var/run/grossd/grossd.pid
        eend $?
}

