#!/sbin/openrc-run

ZEROTIERONE_PIDFILE="/var/run/${SVCNAME}.pid"

depend() {
    need net
}

start() {
    ebegin "Starting zerotier-one"
    start-stop-daemon --start \
        --exec /usr/sbin/zerotier-one --make-pidfile --pidfile "${ZEROTIERONE_PIDFILE}" --background
    eend $?
}

stop() {
    ebegin "Stopping zerotier-one"
    start-stop-daemon --stop --quiet --pidfile "${ZEROTIERONE_PIDFILE}"
    eend $?
}
