#!/sbin/openrc-run

BURP_CONFIG="/etc/burp/burp-server.conf"

description="Burp is a network backup and restore program"

command="/usr/bin/burp"
command_args="-c ${BURP_CONFIG} -F"
command_background="yes"
pidfile="/run/burp.pid"
start_stop_daemon_arg="--wait 500"

extra_started_commands="reload mon"
description_reload="Reloads configuration"
description_mon="Displays status monitor"

depend() {
    need localmount
    after bootmisc
    use net
}

reload() {
    ebegin "Reloading ${SVCNAME} configuration"
    start-stop-daemon --exec ${command} --signal HUP
    eend $?
}

mon() {
    "${command}" -c "${BURP_CONFIG}" -a S
}