#!/sbin/openrc-run

extra_started_commands="reload mon"

description="Burp is a network backup and restore program"
description_reload="Reloads configuration"
description_mon="Displays status monitor"

cfgfile="/etc/burp/burp-server.conf"

command="/usr/bin/burp"
command_args="-c $cfgfile -F ${command_args:-}"
command_background="yes"
pidfile="/run/burp.pid"
start_stop_daemon_arg="--wait 500"

depend() {
	need localmount
	after bootmisc
	use net
}

reload() {
	ebegin "Reloading $RC_SVCNAME configuration"
	start-stop-daemon --exec $command --signal HUP
	eend $?
}

mon() {
	$command -a S
}
