#!/sbin/openrc-run
supervisor=supervise-daemon

name="mautrix-twitter"
description="Daemon for mautrix-twitter, a Matrix-Twitter puppeting bridge"

: ${config:="/etc/mautrix-twitter/config.yaml"}
: ${command_user:="mautrix-twitter:mautrix-twitter"}

command="/usr/bin/mautrix-twitter"
command_args="-c $config $command_args"

depend() {
	need net
}

start_pre() {
	checkpath --file --owner "$command_user" "$config"
	checkpath --directory --owner "$command_user" /var/log/mautrix-twitter
}
