# Configuration for probot-stale - https://github.com/probot/stale

pulls:
  daysUntilStale: 60
  daysUntilClose: 14
  staleLabel: S-stale
  exemptLabels:
    - S-WIP
  markComment: >
    This pull request has been automatically marked as stale because it has not
    had activity in the last 60 days. It will be automatically closed if no
    further activity occurs in the next 14 days. If you are still waiting for a
    review or response from one of our developers you can leave a comment to
    remove the stale label. If you know the username of the maintainer of the
    aport you could try to mention the username in the comment. You can also
    join our IRC channels on freenode and see if you can find an available
    developer. Thank you for your contributions.
  closeComment: >
    This pull request has been automatically closed.
