#!/sbin/openrc-run
supervisor=supervise-daemon
name=$RC_SVCNAME
description="Gromox mail spooler"
description_reload="Reload configuration without exiting"

command="/usr/libexec/gromox/delivery"

extra_started_commands="reload"

depend() {
    need mariadb
}

start_pre() {
    checkpath -d -m 750 -o gromox:gromox /run/gromox
}

reload() {
    ebegin "Reloading configuration"
    $supervisor $RC_SVCNAME --signal HUP
    eend $?
}
