--- statserial-1.1.orig/Makefile
+++ statserial-1.1/Makefile
@@ -7,7 +7,7 @@
 
 # for production code
 CFLAGS	= -Wall -O3 -fomit-frame-pointer
-LDFLAGS = -s -N
+LDFLAGS = -s
 
 statserial:	statserial.o
 	$(LD) $(LDFLAGS) -o statserial statserial.o -lcurses
