#!/sbin/openrc-run

name="blocky"
description="Blocky is a DNS proxy and ad-blocker"
command="/usr/bin/blocky"
pidfile="/run/${RC_SVCNAME}.pid"

: ${CFGFILE:="/etc/blocky/config.yml"}
required_files="${CFGFILE}"
command_args="-c ${CFGFILE}"
command_background=yes
command_user="blocky:blocky"
capabilities="^cap_net_bind_service"

depend() {
	need net
	after firewall
}

healthcheck() {
	$command healthcheck
	eend $?
}
