#!/sbin/openrc-run

command="/sbin/runsvdir"
command_args="/etc/service"
rundir="/run/service"
pidfile="/run/${SVCNAME}.pid"
command_background="true"
description="starts and monitors a collection of runsv(8) processes"
retry="SIGHUP/5"

depend() {
    need localmount
    after firewall
}

start_pre() {
    if [ ! -L "$rundir" ]; then
        rm -f $rundir && ln -s $command_args $rundir
    fi
}

