--- a/Makefile
+++ b/Makefile
@@ -25,7 +25,7 @@ LUA_CFLAGS := $(shell pkg-config --cflags --libs $(lua_package))
 all: subprocess.so subprocess.html
 
 subprocess.so: $(SOURCES)
-	$(CC) $(CFLAGS) $(LUA_CFLAGS) -DOS_POSIX -shared -fPIC -o $@ $(SOURCES)
+	$(CC) $(CFLAGS) $(LUA_CFLAGS) -DOS_POSIX -DSHARE_LIOLIB -shared -fPIC -o $@ $(SOURCES)
 
 subprocess.html: subprocess.txt
 	$(ASCIIDOC) $<
