#!/bin/sh

tmp=$PWD/tmp
aports=$PWD/../aports
target=alpine-test.iso

unapk() {
	local dest="$1"
	shift
	while [ $# -gt 0 ]; do
		tar -C "$dest" -zxf "$1"
		shift
	done
	rm -f "$dest/.PKGINFO"
}

rm -r $tmp
mkdir -p $tmp/apks $tmp/isolinux
cp /usr/share/syslinux/isolinux.* $tmp/isolinux
cat >$tmp/isolinux/isolinux.cfg <<EOF
timeout 20
prompt 1
default test

label test
	kernel /boot/vmlinuz
	append initrd=/boot/test.gz alpine_dev=cdrom quiet
EOF


#cp $aports/core/*/*.apk $tmp/apks

unapk $tmp $aports/core/linux-grsec/linux-grsec-[0-9]*.apk

sh mkinitram
sh mkmodloop

mkdir -p $tmp/boot/
cp test.gz $tmp/boot/ 
cp modloop.cmg $tmp/boot/

genisoimage -o $target -l -J -R \
	-b isolinux/isolinux.bin \
	-c isolinux/boot.cat	\
	-no-emul-boot		\
	-boot-load-size 4	\
	-boot-info-table	\
	-quiet			\
	$tmp


