#!/bin/sh

tmp=$PWD/tmp
aports=$PWD/../aports
target=alpine-test.iso

rm -r $tmp
mkdir -p $tmp/apks $tmp/isolinux
cp /usr/share/syslinux/isolinux.* $tmp/isolinux
cat >$tmp/isolinux/isolinux.cfg <<EOF
timeout 300
prompt 1
default test

label test
	kernel /boot/vmlinuz
	append initrd=/test.gz init=/sbin/init
EOF


cp $aports/core/*/*.apk $tmp/apks
tar -C $tmp -zxf $aports/core/linux-grsec/linux-grsec-[0-9]*.apk
rm -f $tmp/.PKGINFO

sh mkinitram

cp test.gz $tmp/ 

genisoimage -o $target -l -J -R \
	-b isolinux/isolinux.bin \
	-c isolinux/boot.cat	\
	-no-emul-boot		\
	-boot-load-size 4	\
	-boot-info-table	\
	-quiet			\
	$tmp


