#!/bin/sh

case "$1" in
	pre_install)
	# add something which happends before install
	# $2 contains package version
	;;
	post_install)
	# add something which happends after install
	# $2 contains package version
		echo Please run faxsetup to configure hylafax
	;;
	pre_upgrade)
	# add something which happends before update
	# $2 contains new package version
	# $3 contains old package version
	;;
	post_upgrade)
	# add something which happends after update
	# $2 contains new package version
	# $3 contains old package version
	;;
	pre_deinstall)
	# add something which happends before delete
	# $2 contains package version
	;;
	post_deinstall)
	# add something which happends after delete
	# $2 contains package version
	;;
esac
