#!/sbin/openrc-run

command="/usr/sbin/smsd"
pidfile="/run/smsd/smsd.pid"
command_args="-p $pidfile -i ${pidfile%/*}/smsd.working}"
: ${command_user:=smsd}
: ${command_group:=smsd}
: ${cfgfile:=/etc/smsd.conf}

depend() {
	after firewall
}

start_pre() {
	checkpath --directory --owner $command_user:$command_group ${pidfile%/*} \
		/var/log/smsd \
		/var/spool/sms/incoming \
		/var/spool/sms/outgoing \
		/var/spool/sms/checked
}
