#!/sbin/openrc-run
description="innernet VPN client service"

# To manage the wireguard interface named "ifname", link this file
# to /etc/init.d/innernet.ifname and start that service
interface="${RC_SVCNAME##*.}"

command="/usr/sbin/innernet"
command_args="up $interface --daemon ${command_extra_args:---interval 60}"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"

stop_post() {
	$command down $interface
}

depend() {
	use net
}
