#!/sbin/openrc-run
# Copyright 2020 Laurent Bercot for Alpine Linux
# Distributed under the terms of the ISC License.
#

name=utmpd
description="utmps daemon for the utmp service"
command=s6-ipcserver
command_args=".utmpd-socket utmps-utmpd"
command_user=utmp
command_background=true
directory=/run/utmps
pidfile=/run/utmps/utmpd.pid

start_pre() {
	mkdir -p -m 0755 /run/utmps
	chown utmp:utmp /run/utmps
}
