#!/sbin/openrc-run
# Copyright 2020-2021 Laurent Bercot for Alpine Linux
# Distributed under the terms of the ISC License.
#

depend() {
	need localmount
	after bootmisc
	before networking
	after utmpd
}

name=wtmpd
description="utmps daemon for the wtmp service"
command=s6-ipcserver
command_args="/run/utmps/.wtmpd-socket utmps-wtmpd"
command_user=utmp
command_background=true
directory=/var/log
pidfile=/run/utmps/wtmpd.pid

start_pre() {
	checkpath -f -o utmp:utmp -m 0644 /var/log/wtmp
}
