#!/sbin/openrc-run

DAEMON=/usr/bin/${SVCNAME}

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting ${SVCNAME}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${SVCNAME}.pid \
			--exec ${DAEMON} -- ${OPTS} --daemon
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
		start-stop-daemon --stop --quiet \
			--exec ${DAEMON} \
			--pidfile /var/run/${SVCNAME}.pid \
	eend $?
}

