#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-misc/openvswitch/files/ovs-vswitchd-r1,v 1.1 2013/04/08 19:37:58 dev-zero Exp $

description="Open vSwitch virtual switch"

command="/usr/sbin/ovs-vswitchd"
command_args="
    --pidfile
    --detach
    --monitor
    ${OPTIONS} ${DATABASE}"
pidfile="/var/run/openvswitch/ovs-vswitchd.pid"

depend() {
        need localmount ovsdb-server
        after bootmisc hwdrivers modules
        before net
    use logger
}

start_pre() {
	checkpath -d "/var/run/openvswitch" -m 0750
}
