#!/sbin/openrc-run

# fallback values for /etc/conf.d/prowlarr
: ${command_user:=prowlarr:prowlarr}
: ${directory:=/var/lib/prowlarr}
: ${logdir:=/var/log/prowlarr}

name=prowlarr
description="Prowlarr daemon"
command="/usr/lib/prowlarr/bin/Prowlarr"
command_args="-nobrowser -data=$directory"
command_background=true

pidfile="/run/$name.pid"
output_log="$logdir/output.log"
error_log="$logdir/error.log"

depend() {
	need net
	use dns logger netmount
}

start_pre() {
	checkpath -d -o "$command_user" "$directory" "$logdir"
	checkpath -f -o "$command_user" "$output_log" "$error_log"
}
