#!/sbin/openrc-run

command=/usr/sbin/netdata
pidfile=/run/netdata.pid
command_args="-P ${pidfile}"
name="netdata"
description="Real-time performance monitoring"

depend() {
	need net
	after apache2 squid nginx mysql named opensips hostapd postfix lm_sensors
}

start_pre() {
	checkpath --directory --owner netdata:netdata --mode 0750 /var/lib/netdata
	checkpath --directory --owner netdata:netdata --mode 0750 /var/log/netdata
	checkpath --directory --owner netdata:netdata --mode 0750 /var/cache/netdata
}
