#!/sbin/openrc-run
name="calibre-web"
: ${calibre_web_user:=calibre-web}
: ${calibre_web_group:=calibre-web}
: ${calibre_web_config_dir:=/var/lib/calibre-web}
: ${calibre_web_log_dir:=/var/log/calibre-web}
: ${calibre_web_port:=8083}
: ${calibre_web_host:=0.0.0.0}

command="/usr/bin/cps"
command_args="${calibre_web_opts}"
command_background="yes"
pidfile="/run/${RC_SVCNAME}.pid"
command_user="${calibre_web_user}:${calibre_web_group}"

output_log="${calibre_web_log_dir}/calibre-web.log"
error_log="${calibre_web_log_dir}/calibre-web.error.log"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath --directory --mode 0755 \
		--owner "${calibre_web_user}:${calibre_web_group}" \
		"${calibre_web_config_dir}"
	
	checkpath --directory --mode 0755 \
		--owner "${calibre_web_user}:${calibre_web_group}" \
		"${calibre_web_log_dir}"
	
	checkpath --file --mode 0644 \
		--owner "${calibre_web_user}:${calibre_web_group}" \
		"${output_log}" "${error_log}"
}
