#!/bin/sh
# This script exits with status 0 if the latop's lid is closed, 1 if opened,
# 10 if /proc/acpi/button/lid/LID/state does not exist or is not readable.
set -u

for STATE_FILE in /proc/acpi/button/lid/LID*/state; do break; done

verbose=false
[ "${1:-}" = '-v' ] && verbose=true

if ! [ -r "$STATE_FILE" ]; then
	$verbose && echo "$STATE_FILE does not exist or is not readable!" >&2
	exit 10
fi

read -r _ state < "$STATE_FILE" || exit 10

[ "$state" = 'closed' ]; rc=$?

$verbose && echo $rc
exit $rc
