diff --git a/community/openvas-scanner/openvas.conf b/community/openvas-scanner/openvas.conf
new file mode 100644
index 000000000000..8c1becbbfa5d
--- /dev/null
+++ b/community/openvas-scanner/openvas.conf
@@ -0,0 +1,3 @@
+db_address = /run/redis-openvas/redis-openvas.sock
+mqtt_server_uri = localhost:1883
+table_driven_lsc = yes
