#!/sbin/openrc-run
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need localmount
	before net
	use logger
}

start() {
	ebegin "Starting rdnssd"
	start-stop-daemon --start --quiet --exec /usr/sbin/rdnssd -- -u root -r /etc/resolv.conf
	eend $?
}

stop() {
	ebegin "Stopping rdnssd"
	start-stop-daemon --stop --quiet --pidfile /run/rdnssd.pid
} 
