#!/bin/sh

BASE_URL=http://geolite.maxmind.com/download/geoip/database

echo "Updating NTOP GeoIP databases..."

cd /usr/share/ntopng/geoip || exit

for u in \
	asnum/GeoIPASNum.dat.gz \
	asnum/GeoIPASNumv6.dat.gz \
	GeoLiteCity.dat.gz \
	GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz; do
	FILE_GZ=${u#*/}
	FILE=${FILE_GZ%.gz}
	wget -O ${FILE_GZ} ${BASE_URL}/${u} &&
		gunzip < ${FILE_GZ} > .${FILE} &&
		mv -f .${FILE} ${FILE} &&
		rm -f ${FILE_GZ} ||
		exit
done

rc-service ntopng status && rc-service ntopng restart

echo "NTOP GeoIP databases were successfully updated"
