#!/sbin/openrc-run
command="/usr/bin/spampd"
pidfile="/run/${RC_SVCNAME}.pid"
command_args="-p=$pidfile
    ${user:+-u=$user} ${group:+-g=$group}
    ${host:+--host=$host} ${port:+--port=$port}
    ${sock:+--socket=$sock} ${smod:+--socket-perms=$smod}
    ${rhost:+--relayhost=$rhost} ${rport:+--relayport=$rport}
    ${rsock:+--relaysocket=$rsock}
    $args"

# no reload because HUP does not reload spamassassin configuration

depend() {
    before mta
}
