#!/sbin/openrc-run

description="HTTP Server for Whisper speech recognition"
command=/usr/bin/whisper-server
: ${command_user:=whisper-server:whisper-server}

output_logger="logger -t whisper-server -p daemon.info"
error_logger="logger -t whisper-server -p daemon.info"

start_pre() {
	if [ -z "${command_args}" ]; then
		eerror "command_args not specified in /etc/conf.d/whisper-server"
		return 1
	fi
}

no_new_privs="yes"
supervisor="supervise-daemon"
