diff --git a/Makefile.orig b/Makefile
index ff8d684..b256ea3 100755
--- a/Makefile.orig
+++ b/Makefile
@@ -35,13 +35,13 @@ all:
 nslink.o: nslink.o nslink.c nslink_int.h nslink.h version.h
 
 nslinkd: nslinkd.c parse.c nslink.h nslinkd.h version.h
-	$(CC) -Wall -o nslinkd nslinkd.c parse.c
+	$(CC) $(CFLAGS) -Wall $(LDFLAGS) -o nslinkd nslinkd.c parse.c
 
 nslinkadmin: nslinkadmin.c
-	$(CC) -Wall -o nslinkadmin nslinkadmin.c
+	$(CC) $(CFLAGS) -Wall $(LDFLAGS) -o nslinkadmin nslinkadmin.c
 
 nslinkrelease: nslinkrelease.c
-	$(CC) -Wall -o nslinkrelease nslinkrelease.c
+	$(CC) $(CFLAGS) -Wall $(LDFLAGS) -o nslinkrelease nslinkrelease.c
 
 modules: nslink.o mod_nslink.o
 
