--- ./Makefile.orig
+++ ./Makefile
@@ -52,13 +52,13 @@
 nslink.o: nslink.o nslink.c nslink_int.h nslink.h version.h
 
 nslinkd: nslinkd.c parse.c nslink.h nslinkd.h version.h
-	gcc -Wall -o nslinkd nslinkd.c parse.c
+	$(CC) $(CFLAGS) -Wall $(LDFLAGS) -o nslinkd nslinkd.c parse.c
 
 nslinkadmin: nslinkadmin.c
-	gcc -Wall -o nslinkadmin nslinkadmin.c
+	$(CC) $(CFLAGS) -Wall $(LDFLAGS) -o nslinkadmin nslinkadmin.c
 
 nslinkrelease: nslinkrelease.c
-	$(CC) -Wall -o nslinkrelease nslinkrelease.c
+	$(CC) $(CFLAGS) -Wall $(LDFLAGS) -o nslinkrelease nslinkrelease.c
 
 modules: nslink.o mod_nslink.o
 
