# see https://github.com/sigoden/dufs#configuration-file

serve-path: '/var/lib/dufs/'
bind: 127.0.0.1
port: 5000

# read-only by default, uncomment to allow uploads/deletes
#allow-upload: true
#allow-delete: true

