#!/sbin/openrc-run
supervisor="supervise-daemon"

name=$RC_SVCNAME
description="A file server that supports static serving, uploading, searching, accessing control, webdav..."

command="/usr/bin/$name"
command_args="-c /etc/$name/config.yaml"
command_user="$name:$name"

depend() {
	need net localmount
	use logger
	after firewall
}

start_pre() {
	checkpath -d -m 755 -o "$command_user" /var/lib/$name
}
