#!/sbin/openrc-run

: ${command_user:="pacoloco:www-data"}
: ${cfgfile:="/etc/pacoloco.yaml"}
: ${directory:="/var/lib/pacoloco"}
: ${output_log="/var/log/pacoloco.log"}
: ${supervisor="supervise-daemon"}

name=pacoloco
description="Caching proxy server for Arch Linux pacman"

command="/usr/bin/pacoloco"
command_args="$command_args"
command_background="yes"
pidfile="/run/$RC_SVCNAME/$RC_SVCNAME.pid"

required_files="$cfgfile"

start_pre() {
	checkpath --directory --owner $command_user --mode 0775 /run/$RC_SVCNAME
}

depend() {
	use logger dns
	need net
	after firewall
}
