#!/sbin/runscript

# oscam init.d

name="oscam"
daemon="/usr/bin/$name"

depend() {
        use net
}

start() {
	ebegin "Starting oscam" 
	start-stop-daemon --start \
		--quiet \
		--user $user \
		--group $group \
		--name $name \
		--exec $daemon \
		-- $args
        eend $?
}

stop() {
        ebegin "Stopping oscam" 
        start-stop-daemon --stop \
		--signal 2 \
		--name $name
        eend $?
}
