#!/sbin/openrc-run

name="cockroach"
description="Cockroach DB Server"
pidfile="/run/cockroach/cockroach.pid"

command="/usr/bin/cockroach"
command_args="$cockroach_start_flags"

pidfile="/run/cockroach/cockroach.pid"
start() {
	ebegin "Starting ${name}"
	checkpath -m 755 -o $cockroach_user:$cockroach_group -d "$(dirname "$pidfile")"
	start-stop-daemon --start \
		--pidfile $pidfile -m \
		-u $cockroach_user -g $cockroach_group \
		--background $command -- $command_args
	eend $?
}

depend() {
	need net localmount
	after firewall
}
