#!/sbin/openrc-run

name="cockroach"
description="Cockroach DB Server"
pidfile="/run/cockroach/cockroach.pid"

command="/usr/bin/cockroach"
command_args="$cockroach_start_flags"
command_background="yes"
start_stop_daemon_args="-u $cockroach_user -g $cockroach_group"

pidfile="/run/cockroach/cockroach.pid"
start_pre() {
	checkpath -m 755 -o $cockroach_user:$cockroach_group -d "$(dirname "$pidfile")"
}

depend() {
	need net localmount
	after firewall
}
