#!/sbin/openrc-run

description="Incus Agent"
command="/usr/sbin/incus-agent"
command_args="${INCUS_AGENT_OPTIONS}"
command_background="true"
pidfile="/run/incus/${RC_SVCNAME}.pid"

depend() {
	before cloud-init cloud-init-local
}

start_pre() {
	# Required for running systemd containers
	if [ -d /sys/fs/cgroup/unified ] && ! [ -d /sys/fs/cgroup/systemd ]; then
		checkpath --directory --owner root:lxd /sys/fs/cgroup/systemd
		mount -t cgroup \
			-o rw,nosuid,nodev,noexec,relatime,none,name=systemd \
			cgroup /sys/fs/cgroup/systemd
	fi
}
