#!/sbin/runscript

description="rrdcollect daemon"
pidfile="/var/run/${RC_SVCNAME}.pid"
command="/usr/sbin/rrdcollect"
runas="root"

start_pre() {
	checkpath --directory --owner ${runas}:${runas} --mode 775 ${pidfile%/*}
}

start() {
	ebegin "Starting ${RC_SVCNAME}"
	start-stop-daemon --start \
		--user ${runas} \
		--pidfile ${pidfile} \
		--exec ${command} \
		-- ${RRD_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${RC_SVCNAME}"
	start-stop-daemon --stop \
		--pidfile ${pidfile}
	eend $?
}
