#!/sbin/openrc-run
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="/usr/sbin/postfwd2"
pidfile="/run/postfwd2.pid"
command_args="--file ${POSTFWD2_CONFIG}
--interface=${POSTFWD2_LISTEN}
--port=${POSTFWD2_PORT}
--user=${POSTFWD2_USER}
--group=${POSTFWD2_GROUP}
--pidfile ${pidfile}
${POSTFWD2_OPTS}
"
command_args_background="--daemon"

depend() {
	need net
}

