# Matridge configuration file.
# See https://slidge.im/docs/matridge/main/admin/config.html for all options.

# The JID of the gateway component.
jid = matridge.internal

# Secret shared for the XMPP server.
secret = hunter2

# Host and port of the XMPP server.
server = localhost
port = 5347

# Directory used for persistent data and caches.
home-dir = /var/lib/matridge
