--- ./Makefile.orig
+++ ./Makefile
@@ -1,12 +1,22 @@
-CC=		gcc
-LDFLAGS=	-L/usr/lib	-L/usr/local/lib  	-L/usr/lib/ncurses	-L/usr/local/lib/ncurses
+CC?=		gcc
+LDFLAGS?=	-L/usr/lib	-L/usr/local/lib  	-L/usr/lib/ncurses	-L/usr/local/lib/ncurses
 CPPFLAGS=	-I/usr/include	-I/usr/local/include	-I/usr/include/ncurses	-I/usr/local/include/ncurses
-CFLAGS=		-O3 -Wall -std=c99 
+CFLAGS?=		-O3 -Wall -std=c99 
 #CFLAGS+= -ffunction-sections -fdata-sections
 #LDFLAGS+= --gc-sections 
 LIBS=		-lncurses
-DESTDIR=	/usr/local/
 
+prefix=		/usr/local
+bindir=		$(prefix)/bin
+mandir=		$(prefix)/man
+man1dir=	$(mandir)/man1
+man5dir=	$(mandir)/man5
+DESTDIR=
+
+MKDIR_P=	install -d
+INSTALL=	install
+
+
 OFILES=buffers.o \
 	configfile.o \
 	correlation.o \
@@ -27,14 +37,11 @@
 	$(CC) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
 
 install:all
-	strip dhex
-	cp dhex $(DESTDIR)/bin
-	cp dhex.1 $(DESTDIR)/man/man1
-	cp dhexrc.5 $(DESTDIR)/man/man5
-	cp dhex_markers.5 $(DESTDIR)/man/man5
-	cp dhex_searchlog.5 $(DESTDIR)/man/man5
-
-	
+	$(MKDIR_P) $(DESTDIR)$(bindir) $(DESTDIR)$(man1dir) $(DESTDIR)$(man5dir)
+	$(INSTALL) -m755  dhex $(DESTDIR)$(bindir)
+	$(INSTALL) -m644 dhex.1 $(DESTDIR)$(man1dir)
+	$(INSTALL) -m644 dhexrc.5 dhex_markers.5 dhex_searchlog.5 \
+		$(DESTDIR)$(man5dir)
 
 .c.o:
 	$(CC) $< -c -I. $(CPPFLAGS) $(CFLAGS) $(OPTIONS)
