#!/sbin/openrc-run

# fallback values for /etc/conf.d/cocoon
: ${command_user:=cocoon:cocoon}
: ${directory:=/var/lib/cocoon}

name=cocoon
description="Cocoon ATProto PDS daemon"
command="/usr/bin/cocoon"
command_args="run"
command_background=true
pidfile="/run/$name.pid"

depend() {
	need net
	use dns logger
}

start_pre() {
	checkpath -d -o "$command_user" "$directory"

	if [ "$error_log" ]; then
		output_log="$error_log"
		checkpath -f -o "$command_user" "$output_log"
	else
		output_logger="logger -t $name -p daemon.info"
		error_logger="logger -t $name -p daemon.error"
	fi
}
