#!/sbin/openrc-run

description="UDP bittorrent Tracker"
supervisor=supervise-daemon
command=/usr/bin/udpt
command_args="-c /etc/udpt.conf"
command_user="udpt:udpt"
output_log=/var/log/$RC_SVCNAME.log
stopsig="SIGINT"

depend() {
        need net
}

start_pre() {
        checkpath --directory --owner $command_user --mode 0775 \
                /var/lib/$RC_SVCNAME
        checkpath --file --owner $command_user --mode 0644 \
                /var/log/$RC_SVCNAME.log
}
