--- a/include/Makefile.in
+++ b/include/Makefile.in
@@ -406,7 +406,7 @@
 			my_getopt.h sslopt-longopts.h my_dir.h \
 			sslopt-vars.h sslopt-case.h sql_common.h keycache.h \
 			m_ctype.h my_attribute.h $(HEADERS_GEN_CONFIGURE) \
-			$(HEADERS_GEN_MAKE)
+			$(HEADERS_GEN_MAKE) my_compiler.h
 
 noinst_HEADERS = config-win.h config-netware.h my_bit.h \
 			heap.h my_bitmap.h my_uctype.h \
@@ -416,7 +416,7 @@
 			my_aes.h my_tree.h my_trie.h hash.h thr_alarm.h \
 			thr_lock.h t_ctype.h violite.h my_md5.h base64.h \
 			my_handler.h my_time.h my_vle.h my_user.h \
-			my_libwrap.h my_stacktrace.h my_compiler.h
+			my_libwrap.h my_stacktrace.h
 
 EXTRA_DIST = mysql.h.pp mysql/plugin.h.pp
 
