--- ./Makefile.orig
+++ ./Makefile
@@ -7,19 +7,13 @@
 # out this line when debugging.
 OMIT_FRAME_POINTER = -fomit-frame-pointer
 
-# Seach for lua .pc file
-LUAPKG_CMD = $(shell pkg-config --list-all | grep Lua | awk '{print $$1}')
-CFLAGS = -fPIC -O3 -Wall $(shell pkg-config "$(LUAPKG_CMD)" --cflags)
-LFLAGS = -shared $(OMIT_FRAME_POINTER)
-INSTALL_PATH = $(shell pkg-config "$(LUAPKG_CMD)" --variable=INSTALL_CMOD)
-
 ## If your system doesn't have pkg-config, comment out the previous
 ## lines and uncomment and change the following ones according to your
 ## building enviroment.
 
-#CFLAGS = -I/usr/include/lua5.1/ -fPIC -O3 -Wall
-#LFLAGS = -shared $(OMIT_FRAME_POINTER)
-#INSTALL_PATH = /usr/lib/lua/5.1
+CFLAGS = -I/usr/include/lua$(LUAVER)/ -fPIC -O3 -Wall
+LFLAGS = -shared $(OMIT_FRAME_POINTER)
+INSTALL_PATH = /usr/lib/lua/$(LUAVER)
 
 all: $(LIBNAME)
 
