diff --git a/src/Makefile b/src/Makefile
index b684b82..3414312 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -12,7 +12,7 @@ LUA_ENABLE?=no
 MAXAGENTS?=2048
 REUSE_ID?=no
 # XXX Becareful NO EXTRA Spaces here
-PREFIX?=/var/ossec
+PREFIX=$(DESTDIR)/var/ossec
 PG_CONFIG?=pg_config
 MY_CONFIG?=mysql_config
 PRELUDE_CONFIG?=libprelude-config
@@ -22,8 +22,8 @@ OSSEC_USER_MAIL?=ossecm
 OSSEC_USER_REM?=ossecr
 
 INSTALL_CMD?=install -m $(1) -o $(2) -g $(3)
-INSTALL_LOCALTIME?=yes
-INSTALL_RESOLVCONF?=yes
+INSTALL_LOCALTIME=no
+INSTALL_RESOLVCONF=no
 
 USE_PRELUDE?=no
 USE_ZEROMQ?=no
