#!/sbin/runscript

# Sample init.d file for alpine linux.

name=uptimed
daemon=/usr/sbin/$name
source /etc/conf.d/$name

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting ${name}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${name}.pid \
			--chuid nobody:nobody \
			--exec ${daemon} -- ${opts}
	eend $?
}

stop() {
	ebegin "Stopping ${name}"
		start-stop-daemon --stop --quiet \
			--pidfile /var/run/$name.pid \
			--exec ${daemon}
	eend $?
}

