#!/sbin/runscript
# Init script for ipset
# Copyright (C) 2012 Kaarle Ritvanen
# Licensed under the terms of the GPL2

depend() {
	before iptables ip6tables
}

start() {
	if ls /etc/ipset.d/* &> /dev/null; then
		ebegin "Loading firewall IP sets"
		for f in /etc/ipset.d/*; do
			/usr/sbin/ipset restore < $f
		done
		eend $?
	fi
}

stop() {
	ebegin "Flushing firewall IP sets"
	/usr/sbin/ipset destroy
	eend $?
}
