--- a/Makefile
+++ b/Makefile
@@ -22,23 +22,23 @@
 install-completions: install-bash-completion install-zsh-completion install-fish-completion
 
 install-bash-completion:
-	install -m644 auto-completion/bash/pdd.bash $(PREFIX)/share/bash-completion/compilations/pdd
+	install -Dm644 auto-completion/bash/pdd.bash $(DESTDIR)$(PREFIX)/share/bash-completion/completions/pdd
 
 install-fish-completion:
-	install -m644 auto-completion/fish/pdd.fish -t $(PREFIX)/share/fish/vendor_completions.d
+	install -Dm644 auto-completion/fish/pdd.fish -t $(DESTDIR)$(PREFIX)/share/fish/vendor_completions.d
 
 install-zsh-completion:
 	cp pdd pdd.py
 	auto-completion/zsh/zsh_completion.py
-	install -m644 _pdd -t $(PREFIX)/share/zsh/site-functions
+	install -Dm644 _pdd -t $(DESTDIR)$(PREFIX)/share/zsh/site-functions
 
 uninstall:
 	rm -f $(BINDIR)/pdd
 	rm -f $(MANDIR)/pdd.1.gz
 	rm -rf $(DOCDIR)
-	rm -rf $(PREFIX)/share/bash-completion/compilations/pdd
-	rm -rf $(PREFIX)/share/fish/vendor_completions.d/pdd.fish
-	rm -rf $(PREFIX)/share/zsh/site-functions/_pdd
+	rm -rf $(DESTDIR)$(PREFIX)/share/bash-completion/completions/pdd
+	rm -rf $(DESTDIR)$(PREFIX)/share/fish/vendor_completions.d/pdd.fish
+	rm -rf $(DESTDIR)$(PREFIX)/share/zsh/site-functions/_pdd
 
 check:
 	@python3 -m pytest test.py
