#!/sbin/runscript

NAME=lsyncd
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
USER=root
GROUP=root
CONF=/etc/lsyncd/lsyncd.lua

depend() {
	need net
}

start() {
	touch "$PIDFILE"
	chown $USER:$GROUP "$PIDFILE"
	ebegin "Starting $NAME"
		start-stop-daemon --start --quiet \
			--pidfile "$PIDFILE" \
			--user "$USER" --group "$GROUP" \
			--chdir /etc/lsyncd \
			--exec "$DAEMON" -- \
			"$CONF" -pidfile "$PIDFILE"
	eend $?
}

stop() {
	ebegin "Stopping $NAME"
		start-stop-daemon --stop --quiet \
			--pidfile "$PIDFILE"
	eend $?
}
