#!/sbin/openrc-run

description="Touchegg daemon"
pidfile="/var/run/$RC_SVCNAME.pid"
command="/usr/bin/touchegg"

start() {
	ebegin "Starting $RC_SVCNAME"
	start-stop-daemon --start \
		--exec $command \
		--pidfile $pidfile \
		--make-pidfile \
		--quiet \
		--background \
		-- \
		--daemon
	eend $?
}

stop() {
	ebegin "Stopping $RC_SVCNAME"
	start-stop-daemon --stop \
		--pidfile $pidfile
	eend $?
}
