#!/sbin/runscript
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/www/viewcvs.gentoo.org/raw_cvs/gentoo-x86/net-proxy/haproxy/files/haproxy.initd,v 1.3 2007/10/27 10:42:32 mrness Exp $

opts="${opts} reload"

CONFFILE=/etc/${SVCNAME}.cfg
PIDFILE=/var/run/${SVCNAME}.pid

checkconfig() {
	if [ ! -f "${CONFFILE}" ]; then
		eerror "${CONFFILE} does not exist!"
		return 1
	fi
	/usr/sbin/haproxy -c -f "${CONFFILE}" >/dev/null 
}

depend() {
	need net
	after firewall
	use dns logger
}

start() {
	checkconfig || return 1

	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet \
		--exec /usr/sbin/haproxy \
		-- -D -p "${PIDFILE}" -f "${CONFFILE}"
	eend ${?}
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --pidfile "${PIDFILE}"
	eend ${?}
}

reload() {
	ebegin "Reloading ${SVCNAME}"
	/usr/sbin/haproxy -D -p "${PIDFILE}" -f "${CONFFILE}" -sf $(cat "${PIDFILE}")
	eend ${?}
}
