#!/sbin/openrc-run

name="ipfixprobe"
description="High-performance flow exporter"

: ${capabilities="^cap_net_raw,^cap_ipc_lock"}
: ${command_user:="ipfixprobe:ipfixprobe"}
: ${error_logger="logger -t ipfixprobe -p daemon.info >/dev/null 2>&1"}

command="/usr/bin/ipfixprobe"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"

command_args="--storage '$storage' --output '$output' $command_args"
for _item in $input; do
	command_args="$command_args --input '$_item'"
done
for _item in $process; do
	command_args="$command_args --process '$_item'"
done

depend() {
	need net
	after firewall
}
