#!/sbin/runscript

depend() {
  need net
  use dns
}

checkconfig() {
  if [ ! -f /etc/wzdftpd/wzd.cfg ] ; then
    eerror "No /etc/wzdftpd/wzd.cnf file exists!"
    return 1
  fi
}

start() {
  checkconfig || return 1
  ebegin "Starting wzdftpd"
  /usr/sbin/wzdftpd >/dev/null 2>&1 &
  eend $?
}

stop () {
  ebegin "Stopping mysqld"
  start-stop-daemon --stop --quiet \
    --pidfile=/var/run/wzdftpd/wzdftpd.pid --retry 20
  eend $?
}

