#!/sbin/runscript

depend() {
	need net
	after ntpd
}

checkconfig() {
        # Verify that the configuration file exists
        if [ ! -f /etc/aiccu.conf ]; then
        	eerror "AICCU Configuration file /etc/aiccu.conf doesn't exist"
		return 1
        fi
	
        # Verify that the configuration is correct
        if [ `grep -c "^username" /etc/aiccu.conf 2>/dev/null` -ne 1 ]; then
		eerror "AICCU is not configured, edit /etc/aiccu.conf first"
		return 1
	fi
}


start() {
	checkconfig || return 1
	ebegin "Starting aiccu"
	start-stop-daemon --start --quiet --exec /usr/sbin/aiccu -- start
	eend $?
}

stop() {
	ebegin "Stopping aiccu"
	start-stop-daemon --stop --pidfile /var/run/aiccu.pid --quiet --exec /usr/sbin/aiccu -- stop
	eend $?
}

restart() {
	stop
	sleep 3
	start
}
