#!/sbin/openrc-run

name="redict Sentinel"

: ${cfgfile:="/etc/sentinel.conf"}
: ${command_user:="redict:redict"}
: ${retry:=30}

command="/usr/bin/redict-sentinel"
command_args="$cfgfile --daemonize no $command_args"
command_background="yes"

pidfile="/run/$RC_SVCNAME.pid"

required_files="$cfgfile"

depend() {
	use net localmount logger
	after keepalived firewall redict
}

start_pre() {
	# Sets start-start-daemon's --chdir.
	directory=$(config_get 'dir' '/var/lib/redict')
}

config_get() {
	local key="$1"
	local default="${2:-}"

	local value=$(awk "\$1 == \"$key\" { print \$2 }" "$cfgfile")
	printf '%s\n' "${value:-$default}"
}
