#!/sbin/openrc-run

description_checkconfig="Check the configuration file for validity"

name="SMTP Server"

command=/usr/sbin/smtpd
command_args="-F ${command_args:-$SMTPD_OPTS}"  # SMTPD_OPTS is deprecated
command_background=yes

pidfile=/run/$RC_SVCNAME.pid
required_files=/etc/smtpd/smtpd.conf

depend() {
	need net localmount
	after bootmisc firewall
	use logger dns
	provide mta
}

start_pre() {
	checkconfig
}

checkconfig() {
	$command -n
}
