#!/sbin/openrc-run

name="ConnMan"
description="Daemon for managing internet connections"

: ${cfgfile:=/etc/connman/main.conf}
: ${start_wait=50}  # milliseconds

command=/usr/sbin/connmand
command_args="$command_args -c $cfgfile --nodaemon"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"
required_files="$cfgfile"

start_stop_daemon_args="
	${start_wait:+--wait $start_wait}
	${start_stop_daemon_args:-}
	"

depend() {
	need dbus
	provide net
}
