#!/sbin/openrc-run
supervisor=supervise-daemon

name="Piping Server"
description="Infinitely transfer data between devices over HTTP"

command="/usr/bin/piping-server"
command_args="$piping_server_opts"
command_user="nobody:nobody"
directory="/var/empty"

logdir="/var/log/piping-server"
logfile="$logdir/piping-server.log"
supervise_daemon_args="--stdout $logfile --stderr $logfile"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -d -o "$command_user" "$logdir"
	checkpath -f -o "$command_user" "$logfile"
}
