#!/sbin/openrc-run
supervisor=supervise-daemon

name="mautrix-meta"
description="Daemon for Mautrix-Meta, a Matrix-Facebook Messenger and Instagram DM puppeting bridge"

: ${config:="/etc/mautrix-meta/config.yaml"}
: ${command_user:="mautrix-meta:mautrix-meta"}

command="/usr/bin/mautrix-meta"
command_args="-c $config $command_args"

depend() {
	need net
}

start_pre() {
	checkpath --file --owner "$command_user" "$config"
	checkpath --directory --owner "$command_user" /var/log/mautrix-meta
}
