#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command=/usr/bin/sndiod
command_args="$sndio_args"
name="sndio sound daemon"

depends() {
	need localmount
	use net
}

start() {
	ebegin "Starting sndiod"
	start-stop-daemon --start --pidfile /var/run/sndiod.pid \
		--background --make-pidfile \
		--exec /usr/bin/sndiod -- ${SNDIO_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping sndiod"
	start-stop-daemon --stop --quiet --pidfile /var/run/sndiod.pid 
	eend $?
}

