#!/sbin/openrc-run

# Rundeck init.d file for alpine linux.

. /etc/rundeck/profile >/dev/null 2>&1

name="rundeck"
command="${JAVA_HOME:-/usr}/bin/java"
command_args="${RDECK_JVM} -cp ${BOOTSTRAP_CP} com.dtolabs.rundeck.RunServer /var/lib/rundeck ${RDECK_HTTP_PORT}"
command_background="yes"
pidfile="/run/$name/$name.pid"
daemonlog="/var/log/$name/$name.service.log"
start_stop_daemon_args="-1 ${daemonlog} -2 ${daemonlog} --user $name:$name"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -m 700 -o $name:$name -d ${pidfile%/*}
	checkpath -m 700 -o $name:$name -d /tmp/$name
}
