#!/sbin/openrc-run
description="Initialize Amazon Session Manager Plugin"
command="/usr/bin/session-manager-plugin"

start() {
	ebegin "Starting Session Manager Plugin"
	start-stop-daemon --start \
		--exec ${command} ${command_args} \
		-b --make-pidfile \
		--pidfile "${pidfile}"
	eend $?
}

stop() {
	ebegin "Stopping Session Manager Plugin"
	start-stop-daemon --stop \
		--exec ${command} \
		--pidfile "${pidfile}"
	eend $?
}
