diff -ruN a/misc/Makefile b/misc/Makefile
--- a/misc/Makefile	2023-07-15 15:10:47.000000000 +0000
+++ b/misc/Makefile	2025-05-17 03:44:34.581036277 +0000
@@ -29,7 +29,7 @@
 	@printf "make clean: 	        Remove build directories.\n"
 
 install:
-	python3 setup.py install --root=$(DESTDIR)/ --prefix=$(PREFIX) --record=install_log.txt
+	python3 -m installer -d $(DESTDIR) .dist/*.whl
 	install -Dm644 misc/vimiv.desktop $(APPDIR)/vimiv.desktop
 	install -Dm644 misc/org.karlch.vimiv.qt.metainfo.xml $(METAINFODIR)/org.karlch.vimiv.qt.metainfo.xml
 	install -Dm644 LICENSE $(LICENSEDIR)/vimiv/LICENSE
