#!/bin/sh

ELECTRON_RUN_AS_NODE=1 \
ELECTRON_STILL_PASS_THE_DEFAULT_FLAGS=1 \
exec /usr/bin/electron "/usr/lib/vscodium/resources/app/out/cli.js" \
    --app="/usr/lib/vscodium/resources/app" \
    "$@"
