#!/sbin/openrc-run

name=$RC_SVCNAME
command=/usr/bin/syncthing
command_args="${SYNCTHING_ARGS:---no-browser}"
command_user="${SYNCTHING_USER:-syncthing}"
pidfile=/run/${RC_SVCNAME}.pid
command_background=yes
output_logger="logger -t '${RC_SVCNAME}' -p daemon.info"
error_logger="logger -t '${RC_SVCNAME}' -p daemon.error"

depend() {
        use logger dns
        need net
        after firewall
}
