#!/sbin/openrc-run

description="LiteSpeed Web Server"

lshome=/var/lib/litespeed

command=$lshome/bin/lswsctrl
cfgfile=$lshome/conf/httpd_config.conf
pidfile=/tmp/lshttpd/lshttpd.pid
required_files="$cfgfile"

depend() {
	need net
	use dns netmount
}

start() {
	ebegin "Starting $RC_SVCNAME"
	$command start >/dev/null
	eend $?
}

stop() {
	ebegin "Stopping $RC_SVCNAME"
	$command stop >/dev/null
	eend $?
}

restart() {
	ebegin "Restarting $RC_SVCNAME"
	$command restart >/dev/null
	eend $?
}
