#!/sbin/openrc-run

name=frpc
description="frp client"
command="/usr/bin/$name"
supervisor=supervise-daemon

: ${cfgfile:=/etc/frp/$RC_SVCNAME.ini}
command_args="-c $cfgfile"
pidfile="/run/$RC_SVCNAME.pid"
extra_started_commands="reload"
description_reload="Reload configuration"

: ${respawn_delay:=5}
: ${respawn_max:=0}

depend() {
	need net
	after firewall
}

reload() {
	frpc reload -c $cfgfile
}