#!/sbin/openrc-run
supervisor=supervise-daemon

name="mautrix-zulip"
description="Daemon for mautrix-zulip, a Matrix-Zulip puppeting bridge"

: ${config:="/etc/mautrix-zulip/config.yaml"}
: ${command_user:="mautrix-zulip:mautrix-zulip"}

command="/usr/bin/mautrix-zulip"
command_args="-c $config $command_args"

depend() {
	need net
}

start_pre() {
	checkpath --file --owner "$command_user" "$config"
	checkpath --directory --owner "$command_user" /var/log/mautrix-zulip
}
