#!/sbin/runscript
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
	after firewall
	use postgresql
}

start() {
	ebegin "Starting pgpool-II"
	start-stop-daemon --start --quiet --exec /usr/bin/pgpool --f /etc/pgpool.conf -F /etc/pcp.conf
	result=$?
	eend $result
}

stop() {
	ebegin "Stopping pgpool-II"
	start-stop-daemon --stop --quiet --pidfile /var/run/pgpool.pid
	result=$?
	eend $result
}

