#!/sbin/openrc-run
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/zabbix/files/1.6.6/init.d/zabbix-agentd,v 1.1 2009/10/05 15:55:23 patrick Exp $

supervisor=supervise-daemon

name="Monitoring Agent"
description="Daemon for the Zabbix Monitoring Agent"

command_user=zabbix:zabbix
command_args_foreground="-f"

depend() {
	need net
	provide zabbix-agent
	use zabbix-server
}
