#!/sbin/openrc-run

# fallback values for /etc/conf.d/porla
: ${command_user:=porla:porla}
: ${directory:=/var/lib/porla}
: ${umask:=0002}

name=porla
description="porla torrent daemon"
command="/usr/bin/porla"
command_background=true
pidfile="/run/$name.pid"

depend() {
	need net
	use dns logger netmount
	after firewall
}

start_pre() {
	checkpath -d -o "$command_user" "$directory"

	if [ -n "$logdir" ]; then
		checkpath -d -o "$command_user" "$logdir"
	fi

	if [ -n "$output_log" ]; then
		checkpath -f -o "$command_user" "$output_log"
	fi

	if [ -n "$error_log" ]; then
		checkpath -f -o "$command_user" "$error_log"
	fi
}
