Patch-Source: https://aur.archlinux.org/cgit/aur.git/tree/Makefile.in.diff?h=spnavcfg
diff --git a/Makefile.in b/Makefile.in
index b760f4d..f66ba22 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -2,7 +2,7 @@ csrc = $(wildcard src/*.c)
 ccsrc = $(wildcard src/*.cc)
 mochdr = src/ui.h
 mocsrc = $(mochdr:.h=.moc.cc)
-obj = $(csrc:.c=.o) $(ccsrc:.cc=.o) $(mocsrc:.cc=.o) res.cc
+obj = $(sort $(csrc:.c=.o) $(ccsrc:.cc=.o) $(mocsrc:.cc=.o)) res.cc
 dep = $(csrc:.c=.d) $(ccsrc:.cc=.d)
 bin = spnavcfg
 
