#!/sbin/openrc-run

description="iNet wireless daemon without dbus"

: ${error_logger="logger -t eiwd -p daemon.info >/dev/null 2>&1"}
: ${start_wait=50}  # milliseconds

command="/usr/libexec/iwd"
command_background="yes"
command_args="
	${allowed_interfaces:+"--interfaces \"$allowed_interfaces\""}
	${ignored_interfaces:+"--nointerfaces \"$ignored_interfaces\""}
	${command_args:-}
	"
start_stop_daemon_args="
	${start_wait:+--wait $start_wait}
	${start_stop_daemon_args:-}
	"
pidfile="/run/iwd.pid"

depend() {
	before net
	keyword -shutdown
	provide wlan
}
