#!/sbin/runscript

daemon=/usr/bin/media-dispatcher
pidfile=/var/run/mediaproxy/mediaproxy-dispatcher.pid

depend() {
	need net
	after firewall
	after kamailio
}

start() {
	ebegin "Starting Mediaproxy Dispatcher"
	start-stop-daemon --start --quiet --pidfile $pidfile --exec $daemon \
		-- \
		-u kamailio \
		-g kamailio \
		-P $pidfile \
	eend $?
}

stop() {
	ebegin "Stopping Mediaproxy Dispatcher"
	start-stop-daemon --stop --quiet --pidfile $pidfile
	eend $?
}
