#!/sbin/runscript

daemon=/usr/bin/media-dispatcher
pidfile=/var/run/mediaproxy/dispatcher.pid

depend() {
	need net
	after firewall
	after kamailio
}

start() {
	ebegin "Starting Mediaproxy Dispatcher"
	start-stop-daemon --start --verbose --pidfile $pidfile --exec $daemon 
	eend $?
}

stop() {
	ebegin "Stopping Mediaproxy Dispatcher"
	start-stop-daemon --stop --quiet --pidfile $pidfile
	eend $?
}
