--- a/Makefile
+++ b/Makefile
@@ -40,10 +40,10 @@ install-test:
 	fi
 
 .PHONY: test
-test: install-test clean build
+test: build
 	@chmod +x "./utils/tests.sh"; sync; \
 	export SECRET_PROJECT_ROOT="${PWD}"; \
-	export PATH="${PWD}/vendor/bats-core/bin:${PWD}:${PATH}"; \
+	export PATH="${PWD}:${PATH}"; \
 	"./utils/tests.sh"
 
 #
