--- a/Makefile
+++ b/Makefile
@@ -39,10 +39,10 @@
 	git clone https://github.com/sstephenson/bats.git vendor/bats; fi
 
 .PHONY: test
-test: install-test clean build
+test: build
 	@chmod +x "./utils/tests.sh"; sync; \
 	export SECRET_PROJECT_ROOT="${PWD}"; \
-	export PATH="${PWD}/vendor/bats/bin:${PWD}:${PATH}"; \
+	export PATH="${PWD}:${PATH}"; \
 	"./utils/tests.sh"
 
 #
