#!/sbin/openrc-run

description="Open Ticket Management System"
extra_started_commands="reload status"

otrs_cron=/var/lib/otrs/bin/Cron.sh
otrs_daemon=/var/lib/otrs/bin/otrs.Daemon.pl

depend() {
	need net
	after firewall
}

otrs() {
	[ -n "$2" ] && su -s /bin/sh otrs -c "$(eval echo \$otrs_$1) $2" >/dev/null
}

start() {
	ebegin "Starting $RC_SVCNAME"
	/var/lib/otrs/bin/otrs.SetPermissions.pl --web-group=www-data >/dev/null
	otrs daemon start
	otrs cron start
	eend
}

stop() {
	ebegin "Stopping $RC_SVCNAME"
	otrs daemon stop
	otrs cron stop
	eend
}

reload() {
	ebegin "Reloading $RC_SVCNAME"
	otrs daemon restart
	otrs cron restart
	eend
}

status() {
	otrs daemon status
}
