#!/sbin/runscript
# Released under the 2-clause BSD license.

depend() {
	need net
	need avahi
}

start() {
        ebegin "Starting shairplay"
        start-stop-daemon --start --background --pidfile /var/run/shairplay.pid --make-pidfile --exec /usr/bin/shairplay -- ${SHAIRPLAY_OPTS}
        eend $?
}

stop() {
        ebegin "Stopping shairplay"
        start-stop-daemon --stop --pidfile /var/run/shairplay.pid
        eend $?
}
