#!/sbin/runscript

# note that the spoofprotect, syncoockies and ip_forward options are set in 
# /etc/sysctl.conf
depend() {
	after bootmisc
	provide net
	keyword nojail noprefix novserver
}

start() {
	ebegin "Configuring network interfaces"
	ifup -a >/dev/null 2>&1
	eend $?
}

stop() {
	ebegin "Deconfiguring network interfaces"
	ifdown -a >/dev/null 2>&1
	eend $?
}

restart() {
	ebegin "Reconfiguring network interfaces"
	ifdown -a >/dev/null 2>&1 && ifup -a >/dev/null 2>&1
	eend $?
}

