#!/sbin/openrc-run
name="angie"
description="Angie web server"
command="/usr/sbin/angie"
command_args="-c /etc/angie/angie.conf"
pidfile="/run/angie.pid"
start_stop_daemon_args="--quiet --oknodo"
extra_commands="checkconfig reload"

depend() {
	need net
	after firewall
}

checkconfig() {
	ebegin "Checking angie configuration"
	$command -t -c /etc/angie/angie.conf
	eend $?
}

reload() {
	checkconfig || return 1
	ebegin "Reloading angie configuration"
	start-stop-daemon --signal HUP --pidfile $pidfile
	eend $?
}
