#!/sbin/openrc-run

name="aero2solver"
description="Aero2 solver daemon"

: ${command_user:="aero2solver:aero2solver"}
: ${logfile:="/var/log/$RC_SVCNAME.log"}

command="/usr/bin/aero2solver"
command_args="$command_args"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"

output_log="$logfile"
error_log="$logfile"

depend() {
	need net
	use dns
	after firewall
}

start_pre() {
	if [ "$logfile" ]; then
		checkpath -f -m 644 -o "$command_user" "$logfile"
	fi
}
