#!/bin/sh

local ip="${SSH_CLIENT/ */}"
local identity="$1"
[ -z "$ip" -o -z "$identity" ] && exit 1

set -- $SSH_ORIGINAL_COMMAND
cmd="$1"
shift

case "$cmd" in
create) /usr/libexec/aaudit/aaudit-repo-create -a "$ip" "$@" -i "$identity" ;;
commit) /usr/libexec/aaudit/aaudit-repo-update -a "$ip" "$@" -i "$identity" ;;
esac
