#!/bin/sh
CONF="/etc/aaudit/aaudit.conf"
[ -r "$CONF" ] && . "$CONF"
AAUDIT_USER=${AAUDIT_USER:-aaudit}
if [ -z "$AAUDIT_SERVER" ]; then
	echo "Initialize $CONF with AAUDIT_SERVER=<hostname> first!"
	exit 0
fi
exec ssh $AAUDIT_USER@$AAUDIT_SERVER "$@"
