#!/bin/sh -e

IP="$1"
DESC="$2"

if [ -z "$IP" -o -z "$DESC" ]; then
	echo "usage: $0 <IP> <Description>"
	exit 1
fi

git init --quiet --bare
echo "$IP" > aaudit-hostname
echo "$DESC ($IP)" > description

if ! ssh root@$IP 'lbu package -' | gunzip | /usr/libexec/aaudit/aaudit-import-tar --initial-commit; then
	git branch --quiet -D import
	exit 1
fi
git branch --quiet --force master import
git branch --quiet -D import
