#!/sbin/runscript

depend() {
        need net
}

start() {
        ebegin "Starting tvheadend"
        start-stop-daemon --start \
                --exec ${TVHBIN} -- \
                -C -f -u ${TVHUSER} \
                -c ${TVHCONF}
        eend $?
}

stop() {
        ebegin "Stopping tvheadend"
        start-stop-daemon --stop --quiet \
                --retry TERM/30/KILL/5 \
                --pidfile /var/run/tvheadend.pid
        eend $?
}

