#!/sbin/openrc-run

name="busybox $SVCNAME"
command="/usr/sbin/$SVCNAME"
pidfile="/run/$SVCNAME.pid"
command_args="$CRON_OPTS"
reboot_file=/run/crond.reboot

depend() {
	need localmount
	need logger
}

start_pre() {
	if [ ! -f $reboot_file ]; then
		if [ -n "$(run-parts --test ${REBOOT_PATH} 2>/dev/null)" ]; then
			einfo "Running @reboot scripts..."
			run-parts ${REBOOT_PATH} &
		fi
		touch $reboot_file
	fi
}

