#!/bin/sh


# cdrom symlink
case "$MDEV" in
	sr*|xvd*)
		caps="0x`cat /sys/block/$MDEV/capability`"
		if [ $(($caps & 8)) -gt 0 ]; then
			case $ACTION in
				add|"")	ln -sf $MDEV cdrom ;;
				remove) [ "`readlink cdrom 2>/dev/null`" = $MDEV ] && rm -f cdrom ;;
			esac
		fi
		;;
esac

# by-id symlinks
mkdir -p disk/by-id

if [ -e /sys/class/block/$MDEV/partition ]; then
	partition=$(cat /sys/class/block/$MDEV/partition)
	partsuffix="-part$partition"
fi

if [ -e /sys/class/block/$MDEV/wwid ]; then
	wwid=$(cat /sys/class/block/$MDEV/wwid)
fi
if [ -e /sys/class/block/$MDEV/device/wwid ]; then
	wwid=$(cat /sys/class/block/$MDEV/device/wwid)
fi

if [ -n "$wwid" ]; then
	case "$MDEV" in
		nvme*) ln -s ../../$MDEV disk/by-id/nvme-${wwid}${partsuffix};;
	esac
	case "$wwid" in
		naa.*) ln -s ../../$MDEV disk/by-id/wwn-0x${wwid#naa.};;
	esac
fi

if [ -e /sys/class/block/$MDEV/device/serial ]; then
	serial=$(sed -E -e 's/^\s+//' -e 's/\s+$//' -e 's/ /_/g' \
		/sys/class/block/$MDEV/device/serial)
fi

if [ -e /sys/class/block/$MDEV/device/model ]; then
	model=$(sed -E -e 's/^\s+//' -e 's/\s+$//' -e 's/ /_/g' \
		/sys/class/block/$MDEV/device/model)
fi

if [ -n "$serial" ] && [ -n "$model" ]; then
	case "$MDEV" in
		nvme*) ln -s ../../$MDEV disk/by-id/nvme-${model}_${serial}${partsuffix};;
	esac
fi

# virtio-blk
if [ -n "$serial" ]; then
	case "$MDEV" in
		vd*) ln -s ../../$MDEV disk/by-id/virtio-${serial}${partsuffix};;
	esac
fi

# by-uuid, by-partuuid
eval $(blkid /dev/$MDEV | cut -d: -f2-)
if [ -n "$UUID" ]; then
	mkdir -p disk/by-uuid
	ln -s ../../$MDEV disk/by-uuid/$UUID
fi
if [ -n "$PARTUUID" ]; then
	mkdir -p disk/by-uuid
	ln -s ../../$MDEV disk/by-partuuid/$PARTUUID
fi

