#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	persistent_storage_cdrom \
	persistent_storage_nvme_wwid \
	persistent_storage_sda_wwid \
	persistent_storage_nvme_model_serial \
	persistent_storage_virtio_serial \
	persistent_storage_by_uuid \
	persistent_storage_by_partuuid \
	persistent_storage_usbdisk_symlink \
	persistent_storage_usbdisk_partition_symlink

mdevscript=$(atf_get_srcdir)/persistent-storage
export SYSFS=sys

persistent_storage_cdrom_body() {
	for dev in sr0 xvdc; do
		mkdir -p sys/block/$dev
		echo 109 > sys/block/$dev/capability

		MDEV=$dev ACTION=add atf_check \
			sh $mdevscript
		atf_check -o match:"$dev" \
			readlink cdrom

		MDEV=$dev ACTION=remove atf_check \
			sh $mdevscript
		atf_check -s not-exit:0 -o not-match:"$dev" \
			readlink cdrom
	done
}

persistent_storage_nvme_wwid_body() {
	mkdir -p sys/class/block/nvme0n1
	echo eui.0025386b61b01dcd > sys/class/block/nvme0n1/wwid

	MDEV=nvme0n1 ACTION=add atf_check \
		sh $mdevscript
	atf_check -o match:"nvme0n1" \
		readlink disk/by-id/nvme-eui.0025386b61b01dcd

	MDEV=nvme0n1 ACTION=remove atf_check \
		sh $mdevscript
	atf_check -s not-exit:0 \
		readlink disk/by-id/nvme-eui.0025386b61b01dcd
}

persistent_storage_sda_wwid_body() {
	mkdir -p sys/class/block/sda/device
	echo naa.5002538f4158fd7b > sys/class/block/sda/device/wwid

	MDEV=sda ACTION=add atf_check \
		sh $mdevscript
	atf_check -o match:"sda" \
		readlink disk/by-id/wwn-0x5002538f4158fd7b

	MDEV=sda ACTION=remove atf_check \
		sh $mdevscript
	atf_check -s not-exit:0 \
		readlink disk/by-id/wwn-0x5002538f4158fd7b
}

persistent_storage_nvme_model_serial_body() {
	mkdir -p sys/class/block/nvme0n1/device
	echo 'Samsung SSD 960 EVO 500GB               ' > sys/class/block/nvme0n1/device/model
	echo 'S3EUNX0HB01245Y     ' > sys/class/block/nvme0n1/device/serial

	MDEV=nvme0n1 ACTION=add atf_check \
		sh $mdevscript
	atf_check -o match:"nvme0n1" \
		readlink disk/by-id/nvme-Samsung_SSD_960_EVO_500GB_S3EUNX0HB01245Y
}

persistent_storage_virtio_serial_body() {
	mkdir -p sys/class/block/vda/device
	echo 'foobar' > sys/class/block/vda/device/serial

	MDEV=vda ACTION=add atf_check \
		sh $mdevscript
	atf_check -o match:"vda" \
		readlink disk/by-id/virtio-foobar
}

persistent_storage_by_uuid_body() {
	local fs_uuid="2022-05-15-22-31-31-00"

	cat <<-EOF > blkid
	#!/bin/sh
	# blkid mock
	case \$1 in
		/dev/sr0)
		echo "/dev/sr0: BLOCK_SIZE=\"2048\" UUID=\"$fs_uuid\" LABEL=\"cidata\" TYPE=\"iso9660\""
		;;
	esac
	EOF
	chmod +x blkid
	export PATH="$PWD:$PATH"

	MDEV=sr0 ACTION=add atf_check \
		sh $mdevscript
	atf_check -o match:"sr0" \
		readlink disk/by-uuid/"$fs_uuid"
}

persistent_storage_by_partuuid_body() {
	local partuuid="f6daa453-3150-46a2-b6f9-863e38fcd2aa"
	mkdir bin

	cat <<-EOF > bin/blkid
	#!/bin/sh
	# blkid mock
	case \$1 in
		/dev/vda1)
		echo '/dev/vda1: LABEL="testlabel" UUID="9850e420-fecd-4d61-bf8e-50c8babebbb2" BLOCK_SIZE="512" TYPE="xfs" PARTLABEL="Linux filesystem" PARTUUID="$partuuid"'
		;;
	esac
	EOF
	chmod +x bin/blkid
	export PATH="$PWD/bin:$PATH"

	MDEV=vda1 ACTION=add atf_check \
		sh $mdevscript
	atf_check -o match:"vda1" \
		readlink disk/by-partuuid/"$partuuid"
}

persistent_storage_usbdisk_symlink_body() {
	mkdir -p sys/class/block sys/block bin
	ln -s ../../devices/pci0000:00/0000:00:14.0/usb2/2-10/2-10:1.0/host4/target4:0:0/4:0:0:0 sys/class/block/sdc
	ln -s ../devices/pci0000:00/0000:00:14.0/usb2/2-10/2-10:1.0/host4/target4:0:0/4:0:0:0 sys/block/sdc

	cat <<-EOF > bin/blkid
	#!/bin/sh
	# blkid mock
	case \$1 in
		/dev/sdc)
		echo '/dev/sdc: UUID="436D-F3F4" BLOCK_SIZE="512" TYPE="vfat"'
		;;
	esac
	EOF
	chmod +x bin/blkid
	export PATH="$PWD/bin:$PATH"

	MDEV=sdc ACTION=add atf_check \
		sh $mdevscript
	atf_check -o match:"sdc" \
		readlink usbdisk
}

persistent_storage_usbdisk_partition_symlink_body() {
	mkdir -p sys/class/block
	ln -s ../../devices/pci0000:00/0000:00:14.0/usb2/2-10/2-10:1.0/host4/target4:0:0/4:0:0:0 sys/class/block/sdc1

	MDEV=sdc1 ACTION=add atf_check \
		sh $mdevscript
	atf_check -o match:"sdc1" \
		readlink usbdisk
}
