#!/sbin/openrc-run

description="The ACPI Daemon"

extra_started_commands="reload"
description_reload="Reload configuration"

command="/usr/sbin/acpid"
command_args="--foreground ${command_args:-}"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need dev localmount
	after hwdrivers modules
	provide acpid
	keyword -vserver -lxc
}

reload() {
	ebegin "Reloading $RC_SVCNAME configuration"
	if [ "$supervisor" ]; then
		$supervisor "$RC_SVCNAME" --signal HUP
	else
		start-stop-daemon --pidfile "$pidfile" --signal HUP
	fi
	eend $?
}
