#!/sbin/runscript
# Copyright (c) 2011 http://foxpa.ws
# All rights released

description="Runs C++ RTMP Server on Gentoo"

depend()
{
        need net
}

start()
{
        ebegin "Starting C++ RTMP Server"
        start-stop-daemon --start --quit \ 
		--exec /usr/sbin/crtmpserver --daemon --uid=${RTMPD_USER} --pid=/var/run/crtmpserver.pid ${CONFFILE}
        eend ${?}
}

stop()
{
        ebegin "Stopping C++ RTMP Server"
	start-stop-daemon --stop --quiet \
		--exec /usr/sbin/crtmpserver --pid=/var/run/crtmpserver.pid
        eend ${?}
}
