--- a/Makefile
+++ b/Makefile
@@ -2,8 +2,7 @@
 	$(CC) eatmemory.c -o eatmemory
 
 install: eatmemory
-	mkdir -p $(PREFIX)/bin
-	install -m 0755 eatmemory $(PREFIX)/bin/
+	install -D -m 0755 eatmemory $(PREFIX)/usr/bin/eatmemory
 
 clean:
 	rm -rf *o eatmemory
