#!/sbin/openrc-run

CONFIGFILE=/etc/ndppd.conf
PIDFILE=/run/ndppd/ndppd.pid

depend() {
	need net
	after firewall
}

checkconfig() {
	if [ ! -f "${CONFIGFILE}" ]; then
		eerror "Configuration file ${CONFIGFILE} not found"
		return 1
	fi

	checkpath -d ${PIDFILE%/*}
}

start() {
	checkconfig || return 1

	ebegin "Starting IPv6 Router Advertisement Daemon"
	start-stop-daemon -S -x /usr/sbin/ndppd \
		-- -c "${CONFIGFILE}" -p "${PIDFILE}" -d
	eend $?
}

stop() {
	ebegin "Stopping IPv6 Router Advertisement Daemon"
	start-stop-daemon -K -x /usr/sbin/ndppd --pidfile "${PIDFILE}"
	eend $?
}
