#!/bin/bash
# Copyright 2018 Orson Teodoro
# License: MIT

targetconfig=".config"

echo -e "\nUnset all debug"
IFS=$'\n'
for l in $(grep -r -e "DEBUG" $targetconfig) ; do
	echo "raw: $l"
	echo "$l" | grep -E -e "=[0-9]+" > /dev/null
	if [[ "$?" == "0" ]] ; then
		echo "skipping $l"
		continue
	fi
	a=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g")
	b=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g" -e "s|=[0-9ynm]+||g")
	echo "modding $a"
	sed -i -E -e "s|[ ]*${a}\$|# $b is not set|g" $targetconfig
done

echo -e "\nUnset all trace"
for l in $(grep -r -e "TRACE" $targetconfig) ; do
	echo "raw: $l"
	echo "$l" | grep -E -e "=[0-9]+" > /dev/null
	if [[ "$?" == "0" ]] ; then
		echo "skipping $l"
		continue
	fi
	a=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g")
	b=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g" -e "s|=[0-9ynm]+||g")
	echo "modding $a"
	sed -i -E -e "s|[ ]*${a}\$|# $b is not set|g" $targetconfig
done

echo -e "\nUnset all verbose"
for l in $(grep -r -e "VERBOSE" $targetconfig) ; do
	echo "raw: $l"
	echo "$l" | grep -E -e "=[0-9]+" > /dev/null
	if [[ "$?" == "0" ]] ; then
		echo "skipping $l"
		continue
	fi
	a=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g")
	b=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g" -e "s|=[0-9ynm]+||g")
	echo "modding $a"
	sed -i -E -e "s|[ ]*${a}\$|# $b is not set|g" $targetconfig
done

echo -e "\nUnset all asserts"
for l in $(grep -r -e "ASSERT" $targetconfig) ; do
	echo "raw: $l"
	echo "$l" | grep -E -e "=[0-9]+" > /dev/null
	if [[ "$?" == "0" ]] ; then
		echo "skipping $l"
		continue
	fi
	a=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g")
	b=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g" -e "s|=[0-9ynm]+||g")
	echo "modding $a"
	sed -i -E -e "s|[ ]*${a}\$|# $b is not set|g" $targetconfig
done

echo -e "\nUnset some options"
for c in \
	CONFIG_BRIDGE_EBT_LOG \
	CONFIG_NETFILTER_NETLINK_LOG \
	CONFIG_NETFILTER_XT_TARGET_LOG \
	CONFIG_NETFILTER_XT_TARGET_NFLOG \
	CONFIG_BRIDGE_EBT_NFLOG \
	CONFIG_NF_LOG_ARP \
	CONFIG_NF_LOG_BRIDGE \
	CONFIG_NF_LOG_COMMON \
	CONFIG_NF_LOG_IPV4 \
	CONFIG_NF_LOG_IPV6 \
	CONFIG_NFT_LOG \
	CONFIG_DM_LOG_USERSPACE \
	CONFIG_DM_LOG_WRITES \
	CONFIG_SFC_MCDI_LOGGING \
	CONFIG_PRINTK_TIME \
	CONFIG_PRINTK \
	CONFIG_PRINTK_NMI \
	CONFIG_AIC7XXX_REG_PRETTY_PRINT \
	CONFIG_AIC79XX_REG_PRETTY_PRINT \
		; do
	for l in $(grep -r -e "$c" $targetconfig) ; do
		echo "raw: $l"
		a=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g")
		b=$(echo "$l" | sed -r -e "s|# ||g" -e "s| is not set||g" -e "s|=[0-9ynm]+||g")
		echo "modding $a"
		sed -i -r -e "s|[ ]*${a}\$|# $b is not set|g" $targetconfig
	done
done

echo -e "\nReducing log levels and bits shifted"
sed -i -E -e "s|CONFIG_WIMAX_DEBUG_LEVEL=[0-9]+|CONFIG_WIMAX_DEBUG_LEVEL=0|g" \
	-e "s|CONFIG_AIC7XXX_DEBUG_MASK=[0-9]+|CONFIG_AIC7XXX_DEBUG_MASK=0|g" \
	-e "s|CONFIG_AIC79XX_DEBUG_MASK=[0-9]+|CONFIG_AIC79XX_DEBUG_MASK=0|g" \
	-e "s|CONFIG_ATM_FORE200E_DEBUG=[0-9]+|CONFIG_ATM_FORE200E_DEBUG=0|g" \
	-e "s|CONFIG_WIMAX_I2400M_DEBUG_LEVEL=[0-9]+|CONFIG_WIMAX_I2400M_DEBUG_LEVEL=0|g" \
	-e "s|CONFIG_NOUVEAU_DEBUG=[0-9]+|CONFIG_NOUVEAU_DEBUG=0|g" \
	-e "s|CONFIG_NOUVEAU_DEBUG_DEFAULT=[0-9]+|CONFIG_NOUVEAU_DEBUG_DEFAULT=0|g" \
	-e "s|CONFIG_NOUVEAU_DEBUG_DEFAULT=[0-9]+|CONFIG_NOUVEAU_DEBUG_DEFAULT=0|g" \
	-e "s|CONFIG_JFFS2_FS_DEBUG=[0-9]+|CONFIG_JFFS2_FS_DEBUG=0|g" \
	-e "s|CONFIG_DEBUG_KMEMLEAK_EARLY_LOG_SIZE=[0-9]+|CONFIG_DEBUG_KMEMLEAK_EARLY_LOG_SIZE=200|g" \
	-e "s|CONFIG_CONSOLE_LOGLEVEL_DEFAULT=[0-9]+|CONFIG_CONSOLE_LOGLEVEL_DEFAULT=1|g" \
	-e "s|CONFIG_MESSAGE_LOGLEVEL_DEFAULT=[0-9]+|CONFIG_MESSAGE_LOGLEVEL_DEFAULT=1|g" \
	-e "s|CONFIG_PRINTK_SAFE_LOG_BUF_SHIFT=[0-9]+|CONFIG_PRINTK_SAFE_LOG_BUF_SHIFT=10|g" \
	-e "s|CONFIG_LOG_CPU_MAX_BUF_SHIFT=[0-9]+|CONFIG_LOG_CPU_MAX_BUF_SHIFT=0|g" \
	-e "s|CONFIG_LOG_BUF_SHIFT=[0-9]+|CONFIG_LOG_BUF_SHIFT=12|g" \
	-e "s|CONFIG_SCSI_OSD_DPRINT_SENSE=[0-9]+|CONFIG_SCSI_OSD_DPRINT_SENSE=0|g" \
	$targetconfig

echo "Activate necessary debug"

#echo -e "\nenable for ureadahead (Ubuntu readahead) for bootup speedup"
#sed -i -E \
#	-e "s|# CONFIG_FTRACE is not set|CONFIG_FTRACE=y|g" \
#	-e "s|# CONFIG_TRACING_SUPPORT is not set|CONFIG_TRACING_SUPPORT=y|g" \
#	-e "s|# CONFIG_DEBUG_FS is not set|CONFIG_DEBUG_FS=y|g" \
#	-e "s|# CONFIG_ENABLE_DEFAULT_TRACERS is not set|CONFIG_ENABLE_DEFAULT_TRACERS=y|g" \
#	$targetconfig
