#!/bin/bash
# Copyright 2018 Orson Teodoro
# License: MIT

_kernver="$1"
_flavor="$2"

cd src/linux-${_kernver}

update_disable() {
	local ALPINE_ARCH="$1"
	local KERNEL_ARCH="$1"
	cp ../../config-${_flavor}.$ALPINE_ARCH .config
	../../disable_debug
	cp .config ../../config-${_flavor}.$ALPINE_ARCH
}

update_all_disable() {
	update_disable aarch64 arm64
	update_disable armhf arm
	update_disable ppc64le powerpc
	update_disable ppc powerpc
	update_disable x86_64 x86
	update_disable x86 x86
	update_disable s390x s390
}

update_oldconfig() {
	ALPINE_ARCH="$1"
	KERNEL_ARCH="$2"
	cp ../../config-$_flavor.$ALPINE_ARCH .config
	yes "" | make ARCH=$KERNEL_ARCH oldconfig
	cp .config ../../config-$_flavor.$ALPINE_ARCH
}

update_all_oldconfig() {
	update_oldconfig aarch64 arm64
	update_oldconfig armhf arm
	update_oldconfig ppc64le powerpc
	update_oldconfig ppc powerpc
	update_oldconfig x86_64 x86
	update_oldconfig x86 x86
	update_oldconfig s390x s390
}

update_all_disable
update_all_oldconfig
