--- rtapd.orig/Makefile	Tue Mar 30 15:10:02 2010
+++ rtapd/Makefile	Tue Mar 30 15:10:11 2010
@@ -23,8 +23,8 @@
 
 # Use PostgreSQL-server (with includes in /usr/include/pgsql
 # and libs in /usr/lib
-#CFLAGS		= -DUSE_POSTGRESQL -I/usr/include/pgsql
-#LIBS		= -lpq
+CFLAGS		= -DUSE_POSTGRESQL -I/usr/include/pgsql
+LIBS		= -lpq
 
 PREFIX		= /usr/local
 INCLUDES	= -I./
