#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

DAEMON=/usr/sbin/rtapd
USER=rtnppd

start() {
	ebegin "Starting $(basename $DAEMON)"
	start-stop-daemon --start --user ${USER} --exec ${DAEMON} \
		-- -C /etc/rtnppd/rtapd.conf ${RTAPD_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping $(basename $DAEMON)"
	start-stop-daemon --stop --exec ${DAEMON}
	eend $?
}
