#!/sbin/openrc-run

export SEAHUB_LOG_DIR=/var/lib/seafile/$instance/logs

depend() {
	need net
}

start() {
	ebegin "Starting Seafile $instance instance"
	start-stop-daemon --chdir /var/lib/seafile/$instance --user $seafile_user \
	    --group $seafile_group /usr/bin/seafile-admin start
}

stop() {
	ebegin "Stopping Seafile $instance instance"
	start-stop-daemon --chdir /var/lib/seafile/$instance /usr/bin/seafile-admin \
	    stop
}
