#!/sbin/openrc-run

cmd=/usr/sbin/consolation
cmd_args="--no-daemon"
pid=/run/consolation.pid
description="Linux Console Pointer Interface"

depend() {
	after bootmisc
}

start() {
	ebegin "Starting Consolation"
	start-stop-daemon --start --exec $cmd --background \
		--pidfile $pid --make-pidfile -- $cmd_args
	eend $?
}

stop() {
	ebegin "Stopping Consolation"
	start-stop-daemon --stop --exec $cmd
	eend $?
}

restart() {
	stop
	start
}

