#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/www/viewcvs.gentoo.org/raw_cvs/gentoo-x86/net-misc/knock/files/knockd.initd,v 1.2 2004/07/15 00:01:08 agriffis Exp $

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting knockd"
	start-stop-daemon --start --quiet --exec /usr/sbin/knockd -- ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping knockd"
	start-stop-daemon --stop --quiet --exec /usr/sbin/knockd
	eend $?
}
