diff --git a/makefile b/makefile
index 9efe262..00a5391 100644
--- a/makefile
+++ b/makefile
@@ -6054,7 +6054,7 @@ linuxa:
 	$(MAKE) xermit KTARGET=$${KTARGET:-$(@)} "CC = gcc" "CC2 = gcc" \
 	"CFLAGS = -O -DLINUX -pipe -funsigned-char -DFNFLOAT -DCK_POSIX_SIG \
 	-DCK_NEWTERM -DTCPSOCKET -DLINUXFSSTND -DNOCOTFMC -DPOSIX \
-	-DUSE_STRERROR $(KFLAGS)" "LNKFLAGS = $(LNKFLAGS)" \
+	-DUSE_STRERROR -DNOARROWKEYS $(KFLAGS)" "LNKFLAGS = $(LNKFLAGS)" \
 	"LIBS = $(LIBS) -lm"
 
 # As above but with profiling
diff --git a/makefile b/makefile
index ef6296b..ef0bf89 100644
--- a/makefile
+++ b/makefile
@@ -817,7 +817,7 @@ CKVER= "9.0.302"
 #
 # The following symbols are used to specify library and header file locations:
 # 
-prefix  = /usr/local
+prefix  = /usr
 srproot = $(prefix)
 sslroot = $(prefix)
 manroot = $(prefix)
@@ -828,8 +828,8 @@ K5LIB=-L/usr/kerberos/lib
 K5INC=-I/usr/kerberos/include
 SRPLIB=-L$(srproot)/lib
 SRPINC=-I$(srproot)/include
-SSLLIB=-L$(sslroot)/ssl/lib
-SSLINC=-I$(sslroot)/ssl/include
+SSLLIB=-L$(sslroot)/lib
+SSLINC=-I$(sslroot)/include
 
 # To override these assignments; for example, if your OpenSSL files are
 # not in /usr/local/ssl, invoke the desired target like this:
