#!/sbin/openrc-run
supervisor=supervise-daemon

command="/usr/bin/postgres_exporter"
command_args="$ARGS"
command_background="yes"
command_user="prometheus:prometheus"

export DATA_SOURCE_NAME
logdir="/var/log/prometheus"
error_log="$logdir/${SVCNAME}.log"
pidfile="/var/run/${SVCNAME}.pid"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -d -o $command_user -m755 $logdir
	checkpath -f -o $command_user -m644 $error_log
}
