#!/sbin/openrc-run

name='Minio Block Storage Server'
command=/usr/bin/minio
command_args="server \
    ${address:+--address=$address} \
    $MINIO_OPTS \
    $MINIO_VOLUMES"
command_background=true
command_user="minio:minio"
pidfile="/run/${RC_SVCNAME}.pid"

start_pre() {
    # the conf.d file might contain secrets!
    [ -f "/etc/conf.d/${RC_SVCNAME}" ] && checkpath --file --mode 0600 --owner root:root "/etc/conf.d/${RC_SVCNAME}"
    # make sure the default volume exists
    checkpath --directory --mode 0700 --owner minio:minio "/srv/${RC_SVCNAME}"
}
