#!/sbin/openrc-run

description="Save and restore display backlight settings"

save_file="/var/lib/brightnessctl/state"

start() {
	ebegin "Setting brightness to saved value ..."
	# fails to start first time if file does not exist
	if [ -f $save_file ]; then
		brightnessctl -q s $(cat $save_file)
	else
		brightnessctl -q g > $save_file
	fi
	eend $? || return 1
}
stop() {
	ebegin "Saving brightness value ..."
	brightnessctl -q g > $save_file
	eend $? || return 1
}
