#!/sbin/openrc-run
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

INSTALL_DIR="/usr/bin"
RUNTIME_DIR="/var/run/openxcap"
DEFAULTS="/etc/default/openxcap"
SERVER="$INSTALL_DIR/openxcap"
PID="$RUNTIME_DIR/openxcap.pid"
OPTIONS=""
NAME="openxcap"
DESC="OpenXCAP server"

depend() {
    need net
    after firewall
}

start() {
    ebegin "Starting $DESC: $NAME "
    start-stop-daemon --start --quiet --pidfile $PID --exec $SERVER -- $OPTIONS
    eend $?
}

stop () {
    ebegin -n "Stopping $DESC: $NAME "
    start-stop-daemon --stop --quiet --oknodo --signal 15 --pidfile $PID
    eend $?
}

exit 0

