#!/sbin/runscript
#

daemon=/usr/bin/openxcap
pidfile=/var/run/openxcap/openxcap.pid

depend() {
	 need net
	 after firewall
}

start() {
    	ebegin "Starting OpenXCAP Presence Server"
	start-stop-daemon --start --quiet --pidfile $pidfile --exec $daemon
	eend $?
}

stop() {
   	ebegin "Stopping OpenXCAP Presence Server"
	start-stop-daemon --stop --quiet --signal 15 --pidfile $pidfile
	eend $?
}

