#!/sbin/openrc-run

description="Lore revision control server"

command="/usr/bin/loreserver"
command_args="--config /etc/lore/server"
command_user="lore:lore"
command_background=true
pidfile="/run/$RC_SVCNAME.pid"
output_log="/var/log/lore/server.log"
error_log="/var/log/lore/server.log"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -d -m 0750 -o lore:lore /var/lib/lore /var/log/lore
}
