#!/sbin/openrc-run

# fallback values for /etc/conf.d/webhookd
: ${command_user:=webhookd:webhookd}
: ${directory:=/var/lib/webhookd}
: ${logdir:=/var/log/webhookd}

name=webhookd
description="webhookd daemon"
command="/usr/bin/webhookd"
command_background=true
pidfile="/run/$name.pid"

depend() {
	need net
	use dns logger
}

start_pre() {
	checkpath -d -o "$command_user" "$directory" "$logdir"

	if [ -n "$output_log" ]; then
		checkpath -f -o "$command_user" "$output_log"
	fi

	if [ -n "$error_log" ]; then
		checkpath -f -o "$command_user" "$error_log"
	fi
}
