--- a/tools/fip_create/Makefile	2017-12-06 09:44:35.000000000 -0600
+++ b/tools/fip_create/Makefile	2019-05-03 18:51:24.000000000 -0500
@@ -28,11 +28,11 @@
 # POSSIBILITY OF SUCH DAMAGE.
 #
 
-HOST_EXTRACFLAGS = -Wall -Werror -pedantic -std=c99
+HOST_EXTRACFLAGS = -Wall -pedantic -std=c99
 hostprogs-y := fip_create
 fip_create-objs := fip_create.o
 
-HOST_EXTRACFLAGS = -Wall -Werror -pedantic -std=c99
+HOST_EXTRACFLAGS = -Wall -pedantic -std=c99
 ifeq (${DEBUG},1)
   HOST_EXTRACFLAGS += -g -O0 -DDEBUG
 else
