#!/sbin/openrc-run
supervisor=supervise-daemon

name="mautrix-discord"
description="Daemon for Mautrix-Discord, a Matrix-Discord puppeting bridge"

: ${config:="/etc/mautrix-discord/config.yaml"}
: ${command_user:="mautrix-discord:mautrix-discord"}

command="/usr/bin/mautrix-discord"
command_args="-c $config $command_args"

depend() {
	need net
}

start_pre() {
	checkpath --file --owner "$command_user" "$config"
	checkpath --directory --owner "$command_user" /var/log/mautrix-discord
}
