#!/sbin/runscript

name=consul
daemon=/usr/sbin/$name
daemon_user=$name
daemon_group=$name

depend() {
        need net
        after firewall
}

start() {
        ebegin "Starting ${name}"
                start-stop-daemon --start --quiet \
                        -m --pidfile /var/run/${name}.pid \
                        --user ${daemon_user} --group ${daemon_group} \
                        -b -1 /dev/null -2 /dev/null \
			-k 027 --exec ${daemon} -- ${consul_opts}
        eend $?
}

stop() {
        ebegin "Stopping ${name}"
                start-stop-daemon --stop --quiet \
                        --pidfile /var/run/${name}.pid \
                        --exec ${daemon}
        eend $?
}

