#!/sbin/openrc-run
supervisor=supervise-daemon

name="mautrix-bluesky"
description="Daemon for mautrix-bluesky, a Matrix-Bluesky puppeting bridge"

: ${config:="/etc/mautrix-bluesky/config.yaml"}
: ${command_user:="mautrix-bluesky:mautrix-bluesky"}

command="/usr/bin/mautrix-bluesky"
command_args="-c $config $command_args"

depend() {
	need net
}

start_pre() {
	checkpath --file --owner "$command_user" "$config"
	checkpath --directory --owner "$command_user" /var/log/mautrix-bluesky
}
