#!/sbin/openrc-run
supervisor=supervise-daemon

name="synapse"
description="Daemon for Synapse, the Matrix reference homeserver"

: ${command_user:="synapse:synapse"}
: ${config:="/etc/synapse/homesever.yaml"}

command="/usr/bin/python3"
command_args="-m synapse.app.homeserver --config-path=$config $command_args"

pidfile="/run/${RC_SVCNAME}.pid"

depends() {
	need net
}

start_pre() {
	# /var/lib/synapse needs to be owned by the synapse user and so does the config location
	checkpath --directory --owner "$command_user" /var/lib/synapse
	checkpath --file --owner "$command_user" $config
}
