#!/sbin/openrc-run

# Sample init.d file for alpine linux.

NAME=mdadm
DAEMON=/sbin/$NAME

depend() {
	use logger dns net
	after firewall
}

start_pre() {
	checkpath --directory /run/mdadm
}

start() {
	ebegin "Starting ${NAME}"
		start-stop-daemon --start --quiet --background \
			--exec ${DAEMON} -- \
			--monitor --scan \
			--daemonise ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${NAME}"
		start-stop-daemon --stop --quiet \
			--exec ${DAEMON}
	eend $?
}

