#!/sbin/openrc-run

depend() {
	need net
}

start() {
	ebegin "Starting accel-pppd"
	start-stop-daemon --start --quiet --exec /usr/sbin/accel-pppd -- -p /var/run/accel-pppd.pid ${ACCEL_PPPD_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping accel-pppd"
	start-stop-daemon --stop --quiet --pidfile /var/run/accel-pppd.pid
	result=$?
	start-stop-daemon --stop --quiet --oknodo --exec /usr/sbin/accel-pppd
	result=$(( $result + $? ))
	eend $result
}
