#!/sbin/openrc-run

# fallback values for /etc/conf.d/radarr
: ${command_user:=radarr:radarr}
: ${directory:=/var/lib/radarr}
: ${logdir:=/var/log/radarr}
: ${umask:=0002}

name=radarr
description="Radarr daemon"
command="/usr/lib/radarr/bin/Radarr"
command_args="-nobrowser -data=$directory"
command_background=true

pidfile="/run/$name.pid"
output_log="$logdir/output.log"
error_log="$logdir/error.log"

depend() {
	need net
	use dns logger netmount
}

start_pre() {
	checkpath -d -o "$command_user" "$directory" "$logdir"
	checkpath -f -o "$command_user" "$output_log" "$error_log"
}
