#!/bin/sh

PIPE="/run/cloud-init/hook-hotplug-cmd"

mkfifo -m700 $PIPE

while true; do
  # shellcheck disable=SC2162
  read args < $PIPE
  # shellcheck disable=SC2086
  exec /usr/bin/cloud-init devel hotplug-hook $args
done

exit
