#!/bin/sh

echo "Enabling cloud-init's boot services..."
for i in boot/cloud-init-local \
         default/cloud-config \
         default/cloud-final \
         default/cloud-init; do
	if ! [ -e /etc/runlevels/$i ]; then
		ln -s /etc/init.d/${i#*/} /etc/runlevels/$i
	fi
done

# Cloud-init requires udev so enable it also
echo "Enabling udev's boot services (and disabling mdev if currently enabled)..."
setup-devd udev

exit 0
