#!/bin/sh

# Can be passed a parameter to indicate whether mdev / mdevd / udev
# should be used.

echo "Enabling cloud-init's boot services..."
for i in boot/cloud-init-local \
         default/cloud-config \
         default/cloud-final \
         default/cloud-init; do
	if ! [ -e /etc/runlevels/$i ]; then
		ln -s /etc/init.d/${i#*/} /etc/runlevels/$i
	fi
done

# If mdev / mdevd / udev not specified as parameter then assume udev
_device_mgmt="${1:-udev}"

case $_device_mgmt in
  udev )
    : ;;
  mdev | mdevd )
    echo
    echo "cloud-init does not currently support $_device_mgmt!"
    echo
    exit 1
    ;;
  * )
    echo
    echo "Unknown parameter, only 'mdev', 'mdevd', and 'udev' are valid!"
    echo
    exit 1
    ;;
esac

echo "Enabling $_device_mgmt boot services..."
setup-devd "$_device_mgmt"

exit 0
