[piler]
listen = /run/php/php8.3-fpm.sock
listen.owner = piler
listen.group = www-data
listen.mode = 0660

user = piler
group = www-data

; piler for 5 users
pm = ondemand
pm.max_children = 15
pm.max_requests = 500

env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
env[HOME] = /home

php_admin_value[memory_limit] = 128M
;php_admin_value[open_basedir] = ${open_basedir}:/usr/share/webapps/piler:/etc/webapps/piler:/var/lib/piler:/var/log/piler
;php_admin_value[session.save_path] = /var/piler/www/tmp

; The maximum POST limit. To upload large files, this value must be larger than upload_max_filesize.
php_admin_value[upload_max_filesize] = 30M
php_admin_value[post_max_size] = 31M

; php_admin_value[date.timezone] = Europe/Berlin

php_flag[magic_quotes_gpc] = off
php_flag[register_globals] = off
php_flag[magic_quotes_runtime] = off
php_flag[short_open_tag] = on

