#!/sbin/openrc-run
supervisor=supervise-daemon

name="mautrix-whatsapp"
description="Daemon for Mautrix-Whatsapp, a Matrix-WhatsApp puppeting bridge"

command="/usr/bin/mautrix-whatsapp"
command_args="-c /etc/mautrix-whatsapp/config.yaml"
command_user="synapse:synapse"

depends() {
	need net synapse
}

start_pre() {
	checkpath --file --owner synapse:synapse /etc/mautrix-whatsapp/config.yaml
	checkpath --file --owner synapse:synapse /etc/mautrix-whatsapp/registration.yaml
	checkpath --file --owner synapse:synapse /var/log/mautrix-whatsapp.log
}
