#!/usr/bin/execlineb -S1

fdmove -c 2 1
emptyenv -p
fdmove 1 3
envfile /etc/conf.d/tipidee
unexport HTTP
unexport HTTPS
multisubstitute
{
  importas -uSi TIPIDEED_IPv@V@
  importas -uSi TIPIDEED_ROOT
  importas -uSD1000 TIPIDEED_CONCURRENCY
  importas -uSD10 TIPIDEED_LOCAL_CONCURRENCY
}
s6-envuidgid tipideed
cd ${TIPIDEED_ROOT}
s6-tcpserver -1 -U -c ${TIPIDEED_CONCURRENCY} -C ${TIPIDEED_LOCAL_CONCURRENCY} -- ${TIPIDEED_IPv@V@} 80
tipideed
