#!/sbin/openrc-run

description="HOMER App and UI"
command=/usr/bin/homer-app
command_args="-webapp-config-path=${CONFIG_PATH:-/etc/homer} -webapp-log-path /var/log/homer"
command_background=yes
command_user="${USER:-homer}"
command_group="${GROUP:-homer}"
pidfile="/run/homer/${RC_SVCNAME}.pid"

depend() {
	need net
	after firewall
	want postgresql
}

start_pre() {
	checkpath --directory --owner $command_user:$command_group ${pidfile%/*} /var/log/homer
}
