#!/sbin/openrc-run

command="/usr/bin/rebuilderd"
command_args="-c /etc/rebuilderd.conf"
command_background="yes"
command_user="rebuilderd"
directory="/var/lib/rebuilderd"
pidfile="/run/rebuilderd.pid"

export REBUILDERD_COOKIE_PATH=/var/lib/rebuilderd/auth-cookie

start_pre() {
	checkpath --directory --owner rebuilderd:rebuilderd --mode 0770 \
		"$directory"
}

depend() {
	need net
	after firewall
}
