#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header$

PIDFILE=/var/run/rtpproxy.pid

depend() {
	need net
}

start() {
	ebegin "Starting rtpproxy"
	start-stop-daemon --start --quiet --pidfile "${PIDFILE}" \
		--exec /usr/bin/rtpproxy \
        -- -urtpproxy:rtpproxy -p"${PIDFILE}" ${RTPPROXY_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping rtpproxy"
	start-stop-daemon --stop --quiet --pidfile "${PIDFILE}"
	eend $?
}

