#!/sbin/openrc-run
supervisor=supervise-daemon
name=$RC_SVCNAME
description="Gromox zcore service"
description_reload="Reload configuration without exiting"

command="/usr/libexec/gromox/zcore"

extra_started_commands="reload"

depend() {
    after mariadb
}

start_pre() {
    checkpath -d -m 775 -o gromox:gromox /run/gromox
}

reload() {
    ebegin "Reloading configuration"
    $supervisor $RC_SVCNAME --signal HUP
    eend $?
}
