Author: Hose Amigo <sir@frojnd.com>
Summary: Fix suffixex, prefixes
----
--- a/Makefile	2024-12-02 15:05:01.070000205 +0100
+++ b/Makefile	2024-12-02 15:06:23.923333533 +0100
@@ -20,7 +20,7 @@ EARLY_PREFIX ?=
 
 BINDIR ?= /usr/bin
 PYTHON ?= python3
-DOCDIR ?= /usr/share/docs/$(PROGRAM_PREFIX)bootchart$(PROGRAM_SUFFIX)
+DOCDIR ?= /usr/share/doc/$(PROGRAM_PREFIX)bootchart$(PROGRAM_SUFFIX)
 MANDIR ?= /usr/share/man/man1
 # never contains /usr; typically /lib, /lib64 or e.g. /lib/x86_64-linux-gnu
 LIBDIR ?= /lib
@@ -36,7 +36,7 @@ endif
 PY_SITEDIR ?= $(PY_LIBDIR)/site-packages
 LIBC_A_PATH = /usr$(LIBDIR)
 # Always lib, even on systems that otherwise use lib64
-SYSTEMD_UNIT_DIR = $(EARLY_PREFIX)/lib/systemd/system
+SYSTEMD_UNIT_DIR = /usr/lib/systemd/system
 COLLECTOR = \
 	collector/collector.o \
 	collector/output.o \
@@ -99,7 +99,7 @@ install-chroot:
 	install -d $(DESTDIR)$(PKGLIBDIR)/tmpfs
 
 install-collector: all install-chroot
-	install -m 755 -D bootchartd $(DESTDIR)$(EARLY_PREFIX)/sbin/$(PROGRAM_PREFIX)bootchartd$(PROGRAM_SUFFIX)
+	install -m 755 -D bootchartd $(DESTDIR)$(EARLY_PREFIX)/bin/$(PROGRAM_PREFIX)bootchartd$(PROGRAM_SUFFIX)
 	install -m 644 -D bootchartd.conf $(DESTDIR)/etc/$(PROGRAM_PREFIX)bootchartd$(PROGRAM_SUFFIX).conf
 	install -m 755 -D bootchart-collector $(DESTDIR)$(PKGLIBDIR)/$(PROGRAM_PREFIX)bootchart$(PROGRAM_SUFFIX)-collector
 
