#!/sbin/openrc-run

command=/usr/libexec/vino-server

depend() {
        need net
        after firewall
}

start () {
        ebegin "Starting vino-server"
        export DISPLAY=:0.0
        start-stop-daemon \
                --background \
                --start \
                --exec $command
        eend $?
}

stop () {
        ebegin "Stopping vino-server"
        start-stop-daemon \
		--stop \
		--exec $command
        eend $?
}
