#!/sbin/openrc-run

: "${command_user:=tranquil-pds:tranquil-pds}"
: "${config:=/etc/tranquil-pds/config.toml}"
: "${data:=/var/lib/tranquil-pds}"
: "${frontend:=/usr/share/webapps/tranquil-pds}"

name=tranquil-pds
command="/usr/bin/tranquil-pds"
command_args="--config '$config'"
command_background=yes
pidfile="/run/$RC_SVCNAME.pid"

output_log="/var/log/$name.log"
error_log="/var/log/$name.log"

required_files="$config"

start_pre() {
	checkpath -d -o "$command_user" -m 0755 "$data"
	checkpath -f -o "$command_user" -m 0644 "$config"
	checkpath -f -o "$command_user" -m 0644 "$output_log"
	
	export FRONTEND_DIR="$frontend"
}

depend() {
	use dns
	need net
	after firewall postgresql
}
