.Dd 2025-08-23
.Dt alpine-hier 7
.\" TODO: inject version here?
.Os Alpine Linux
.Sh NAME
.Nm alpine-hier
.Nd filesystem hierarchy
.Sh DESCRIPTION
Overview of the filesystem hierarchy on Alpine Linux.
.Bl -tag -width "/media/"
.It Pa /
Root directory of the file system.
.It Pa /bin/
Essential system utilities. The distinction between this directory and
.Pa /usr/bin/
is somewhat loose, and new packages should prefer the latter. In future, this
shall be a symlink to
.Pa /usr/bin/ .
.It Pa /boot/
Static files used for the boot process. On BIOS systems, this is often the boot
partition. On UEFI systems, this is sometimes the ESP, although this is
strongly discouraged when using SecureBoot.
.It Pa /boot/efi/
On UEFI systems, if this path exists it is typically the ESP partition. On
other systems, this directory does not usually exist.
.It Pa /dev/
Device files. Typically mounted as devtmpfs.
.It Pa /dev/shm/
POSIX shared memory segments, as those created via
.Xr shm_open 3 .
.It Pa /efi/
On UEFI systems, alternative path for the ESP. Does not exist on non-UEFI
systems.
.It Pa /etc/
Configuration files which are host-specific. Some packages with multiple files
use their own directory inside
.Pa /etc/ .
May include files installed by packages themselves. Files inside this directory
are typically not overwritten during package updates. See
.Xr apk-protected_paths 5 .
.It Pa /etc/apk/
Configuration files for the Alpine Package Keeper. See
.Xr apk 8 .
.It Pa /etc/ssl/certs/
CA certificates for anchoring trust.
.It Pa /etc/ssl/certs/ca-certificates.crt
Bundle with all CA certificates.
.It Pa /etc/localtime
Defines the local timezone by linking to or copying the appropriate timezone
data from
.Pa /usr/share/zoneinfo/ .
.It Pa /etc/modules-load.d/
Configuration files for modules which should be loaded automatically. See
.Xr modules 7 .
.It Pa /etc/os-release
Identification information for the operating system and its current version.
.It Pa /etc/sysctl.d/
Configuration for kernel parameters. See
.Xr sysctl 8 .
.It Pa /home/
Home directories for regular users (each one as an individual subdirectory).
.It Pa /lib/
Shared libraries for essential system utilities. In future, this shall be a
deprecated in favour of
.Pa /usr/lib/ .
.It Pa /lib/apk/
Files describing system state and configuration for
.Xr apk 8 .
The contents inside this directory are not intended to be tampered directly,
and no guarantees are made about its inner structure.
.It Pa /lib/firmware/
Firmware loaded by the kernel.
.It Pa /lib/modules/
Kernel modules.
.It Pa /lib/modules-load.d/
Configuration files for modules which should be loaded automatically. This
directory is intended to be used by packages, and will be overwritten during
updates. See
.Xr modules 7 .
.It Pa /media/
Mount points for removable media.
.It Pa /mnt/
Mount point for a single, temporally mounted filesystem.
.It Pa /opt/
Utilities installed by the system administrator. Packages shall not install
files into this directory. Usually, software which cannot be adapted to follow
.Xr alpine-hier 7
shall be installed into a single directory here.
.It Pa /proc/
Exposes information about running processes. Typically mounted as the proc
pseudo-filesystem. See
.Xr proc 5 .
.It Pa /root/
The home directory for the root user.
.It Pa /run/
Runtime files for the current boot. Services should place sockets, pid files
and other runtime-only files here. Files are typically
.Em not
preserved between reboots.
.It Pa /sbin/
Essential system utilities.
.It Pa /srv/
Files served by local system services, managed by the system administrator. The
exact structure of this directory is defined by the system administrator.
.It Pa /sys/
Exposes information from the kernel. Typically mounted as the sysfs
pseudo-filesystem.
.It Pa /tmp/
Temporary files which are not usually preserved between reboots. Usually
mounted as tmpfs.
.It Pa /usr/
The majority of user utilities and their support files. This directory should
generally be treated as read-only (except for package installation, deletion or
upgrades) and may be mounted across multiple hosts.
.It Pa /usr/bin/
Common utilities, games and applications.
.It Pa /usr/include/
Standard C or C++ headers.
.It Pa /usr/lib/
Common shared object libraries, and other private support files. Larger
packages may include a subdirectory here.
.It Pa /usr/lib/os-release
Fallback identification information for the operating system and its current
version. This file is present only for compatibility with the systemd
ecosystem of tools.
.It Pa /usr/libexec/
Executables meant for internal use and not intended to be executed directly
from a user's shell.
.It Pa /usr/local/
Reserved for programs installed by the system administrator without using
.Xr apk 8 .
The directory structure of this directory is identical to that of
.Pa /usr/ ,
except that it does not contain a nested
.Pa local
subdirectory.
.It Pa /usr/local/bin/
Utilities, games and applications installed manually.
.It Pa /usr/sbin/
System utilities.
.It Pa /usr/share/
Architecture-independent application data. Files which are
architecture-dependant should be placed in
.Pa /usr/lib
instead.
.It Pa /usr/share/doc/
Documentation provided by installed packages, excluding manual pages.
.It Pa /usr/share/licenses/
Licenses for installed packages.
.It Pa /usr/share/man/
Manual pages. See
.Xr man 1 .
.It Pa /usr/src
Source files.
.It Pa /var/
Variable system data, including application state, spool files and logs.
Usually persists across reboots.
.It Pa /var/cache/
Ephemeral cache data for local utilities and services.
.It Pa /var/log/
System log files.
.It Pa /var/run/
Symlink to
.Pa /var/ .
Exists only for backwards compatibility.
.El
.Sh SEE ALSO
.Xr apk 8 ,
.Xr apk-protected_paths 5 ,
.Xr find 1 ,
.Xr man 1 ,
.Xr modules 7 ,
.Xr proc 5 ,
.Xr sysctl 8 ,
.Xr whereis 1 ,
.Xr which 1
.Pp
.Xr gnu-hier 7
provided by the man-pages project contains similar general information, but
applies more generally to GNU/Linux systems, contains information which does
not apply to Alpine Linux and lacks some distributions-specific conventions.
.Sh HISTORY
The following are related standards and conventions. Alpine Linux does not
strictly adhere to any of them, but attempts to align as close as possible
where applicable.
.Bl -bullet -compact -offset ident
.It
Filesystem Hierarchy Standard
.Lk https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html
.It
hier — Linux man pages
.Lk https://man7.org/linux/man-pages/man7/hier.7.html
.It
Linux File System Hierarchy
.Lk https://uapi-group.org/specifications/specs/linux_file_system_hierarchy/
.It
file-hierarchy — systemd
.Lk https://www.freedesktop.org/software/systemd/man/latest/file-hierarchy.html
.El
