#!/sbin/openrc-run

# Sample init.d file for alpine linux.

name=atd
daemon=/usr/sbin/$name

depend() {
	after localmount
}

start() {
	ebegin "Starting command schedulng daemon ${name}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${name}.pid \
			--exec ${daemon}
	eend $?
}

stop() {
	ebegin "Stopping command schedulng daemon ${name}"
		start-stop-daemon --stop --quiet \
			--pidfile /var/run/$name.pid \
			--exec ${daemon}
	eend $?
}

