#!/sbin/openrc-run

description="EXIM internet mailer"
cfgfile=/etc/exim/exim.conf
pidfile=/run/exim.pid
command=/usr/sbin/exim
command_args=${command_args:--bd -q15m}
required_files="$cfgfile"
extra_started_commands="reload"
description_reload="Reload configuration"

depend() {
	use antivirus net
	provide mta
}

start_pre() {
	ebegin
	$command -bV >/dev/null 2>>${startuplog:-/dev/null}
	eend $?
}

reload() {
	ebegin "Reloading $RC_SVCNAME"
	start-stop-daemon --signal HUP --pidfile $pidfile
	eend $?
}
