#!/sbin/openrc-run

name="Victoria Metrics"
description="Fast, cost-effective and scalable time series database"

command="/usr/bin/victoria-metrics"
command_args="$victoriametrics_opts"
command_user=victoriametrics:victoriametrics
command_background=yes
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need net
	after firewall
}

start_pre() {
	if [ -n "$victoriametrics_home" ]; then
		checkpath -d -o $command_user -m755 "$victoriametrics_home"
	fi
}
