#!/sbin/openrc-run

name="SSHGuard"
description="Protects hosts from brute-force attacks against SSH and other services"

# Log startup errrors to syslog.
: ${error_logger="logger -t sshguard -p daemon.err >/dev/null 2>&1"}

command="/usr/sbin/sshguard"
# $SSHGUARD_OPTS is only for backward compatibility (Alpine <3.19)
command_args="$SSHGUARD_OPTS $command_args"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	after firewall
	use logger
}
