#!/sbin/openrc-run

NAME=telegraf
DAEMON=/usr/bin/$NAME

# /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting ${NAME}"
		start-stop-daemon --start --quiet --background \
			--make-pidfile --pidfile /var/run/${NAME}.pid \
			--exec ${DAEMON} -- ${OPTS} -config /etc/${NAME}/${NAME}.conf -config-directory /etc/${NAME}/${NAME}.d
	eend $?
}

stop() {
	ebegin "Stopping ${NAME}"
		start-stop-daemon --stop --quiet \
			--exec ${DAEMON} \
			--pidfile /var/run/${NAME}.pid \
	eend $?
}

reload() {
	ebegin "Reloading ${NAME}"
	if ! service_started "${NAME}" ; then
		eend 1 "${NAME} is not started"
		return 1
	fi
	start-stop-daemon --stop --oknodo --signal HUP \
		--exec ${DAEMON} --pidfile /var/run/${NAME}.pid
	eend $?
}

