#!/sbin/openrc-run

name="docker-volume-local-persist"
description="Docker Volume plugin local-persist"
command="/usr/bin/docker-volume-local-persist"
DOCKER_VOLUME_ERRFILE="/var/log/docker-volume-err.log"
DOCKER_VOLUME_OUTFILE="/var/log/docker-volume-out.log"
start_stop_daemon_args="--background \
    --stderr \"${DOCKER_VOLUME_ERRFILE}\" --stdout \"${DOCKER_VOLUME_OUTFILE}\""

depend() {
    before docker
    wants docker
}