diff --git a/Makefile b/Makefile
index 86e03a3..17871ea 100644
--- a/Makefile
+++ b/Makefile
@@ -12,13 +12,17 @@
 #
 #CFLAGS = -Wall -O -D_GNU_SOURCE -g -DDEBUG
 #CFLAGS = -Wall -g -Os -D_GNU_SOURCE
-CFLAGS = -Wall -g -O3 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 \
-	 -I/usr/include/ffmpeg \
-	 -I/usr/include/libavutil -I/usr/include/libavcodec -I/usr/include/libavformat \
-	 -I/usr/include/ffmpeg/libavutil -I/usr/include/ffmpeg/libavcodec -I/usr/include/ffmpeg/libavformat
+
+libavutil_cflags := $(shell pkg-config --cflags libavutil)
+libavformat_cflags := $(shell pkg-config --cflags libavformat)
+libavfilter_cflags := $(shell pkg-config --cflags libavfilter)
+
+CFLAGS += -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I. \
+	$(libavutil_cflags) $(libavfilter_cflags) $(libavformat_clfags)
+
 #STATIC_LINKING: CFLAGS += -DSTATIC
 #STATIC_LINKING: LDFLAGS = -static
-CC = gcc
+CC ?= gcc
 RM = rm -f
 INSTALL = install
 
