#!/sbin/runscript

name="MiniDLNA"
configfile="${CONFIG:-/etc/minidlna.conf}"
start_stop_daemon_args="--user ${M_USER:-minidlna} --group ${M_GROUP:-minidlna}"
command=/usr/sbin/minidlnad
command_args="-f ${configfile}"

depend() {
	need net
}

start_pre() {
	if ! [ -f "${configfile}" ]; then
		eerror "${configfile} is missing"
		return 1
	fi
	if yesno "${RESCAN}"; then
		command_args="$command_args -R"
	fi

	if ! [ -d /var/run/minidlna ]; then
		install -d -o ${M_USER:-minidlna} -g ${M_GROUP:-minidlna} /var/run/minidlna
	fi
}

