#!/sbin/openrc-run

supervisor=supervise-daemon

name="Grafana image renderer"
description="Grafana Backend Plugin that handles rendering of panels & dashboards to PNGs using headless chrome"

command="/usr/bin/node"
command_args="build/app.js server $GRAFANA_IR_OPTS"
command_user=grafanair:grafanair
directory=/usr/share/grafana-image-renderer
supervise_daemon_args="-e CHROME_BIN=/usr/bin/chromium-browser"

depend() {
	need net
	after firewall
}
