#!/sbin/openrc-run

name="Grafana image renderer"
description="Grafana Backend Plugin that handles rendering of panels & dashboards to PNGs using headless chrome"
supervisor=supervise-daemon
command="/usr/bin/node"
command_args="build/app.js server $GRAFANA_IR_OPTS"
command_user=grafanair:grafanair
directory=/usr/share/grafana-image-renderer

export NODE_ENV=production

depend() {
	need net
	after firewall
}
