--- nx-libs-3.5.0.28/Makefile
+++ ../Makefile
@@ -14,7 +14,7 @@
 BINDIR=$(PREFIX)/bin
 NXLIBDIR=$(PREFIX)/lib/nx
 X2GOLIBDIR=$(PREFIX)/lib/x2go
-CONFIGURE ?= ./configure
+CONFIGURE ?= ./configure --prefix=usr
 
 SHELL:=/bin/bash
 
