# System-wide .zshenv file for zsh(1), sourced on all invocations of the shell.
#
# Global order: zshenv, zprofile, zshrc, zlogin

# If $ZDOTDIR is not set and neither $HOME/.zshrc nor $HOME/.zshenv exists,
# read ZSH startup files from $XDG_CONFIG_HOME/zsh/ instead of $HOME.
if [[ -z "${ZDOTDIR-}" && ! -f "$HOME"/.zshrc && ! -f "$HOME"/.zshenv ]]; then
	ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
fi

# vim: set ft=zsh ts=4:
