#!/sbin/openrc-run

extra_started_commands="reload"
description="A netlink-listening device manager similar to mdev"
description_reload="Reload the configuration file"

: ${cfgfile:="/etc/mdev.conf"}
: ${logfile:="/var/log/$RC_SVCNAME.log"}

pidfile="/run/$RC_SVCNAME.pid"
required_files="$cfgfile"

command="/bin/mdevd"
command_args="-f $cfgfile ${command_args:-}"
command_background="yes"
start_stop_daemon_args="--stdout $logfile --stderr $logfile"

depend() {
	provide dev
	need sysfs dev-mount
	before checkfs fsck
	keyword -containers -lxc -vserver
}

start_pre() {
	mkdir -p /dev
}

reload() {
	ebegin "Reloading $name configuration"
	start-stop-daemon --signal HUP --pidfile "$pidfile"
	eend $?
}
