#!/bin/sh
# taken from https://github.com/archlinux/svntogit-community/blob/3b6e414da1733d2fc1bc4f830e1bd913c1f4b529/trunk/wrapper
TMPPATH=$(mktemp -d "/tmp/lua-language-server.XXXX")
DEFAULT_LOGPATH="$TMPPATH/log"
DEFAULT_METAPATH="$TMPPATH/meta"

exec /usr/lib/lua-language-server/bin/lua-language-server -E /usr/lib/lua-language-server/main.lua \
  --logpath="$DEFAULT_LOGPATH" --metapath="$DEFAULT_METAPATH" \
  "$@"
