#!/bin/sh -e

# HOMER database setup script
# Copyright (c) 2017 Kaarle Ritvanen

exec_sql() {
	mysql $2 < /usr/share/homer-db/$1.sql
}

exec_sql homer_databases
exec_sql homer_user

for db in configuration data statistic; do
	exec_sql schema_$db homer_$db
done

homer_rotate

[ "$1" = -r ] || exit 0

mysql <<EOF
CREATE USER 'homer_user' IDENTIFIED BY 'homer_password';
GRANT SELECT ON homer_data.* TO 'homer_user';
EOF
