diff --git a/src/Makefile b/src/Makefile
index 7fc04c0..c55c6b5 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -21,14 +21,14 @@ OSSEC_USER?=ossec
 OSSEC_USER_MAIL?=ossecm
 OSSEC_USER_REM?=ossecr
 
-INSTALL_LOCALTIME?=yes
-INSTALL_RESOLVCONF?=yes
+INSTALL_LOCALTIME=no
+INSTALL_RESOLVCONF=no
 
 USE_PRELUDE?=no
 USE_ZEROMQ?=no
 USE_GEOIP?=no
-USE_INOTIFY=no
-USE_PCRE2_JIT=yes
+USE_INOTIFY=yes
+USE_PCRE2_JIT=?yes
 USE_SYSTEMD?=yes
 
 ifneq (${TARGET},winagent)
@@ -416,7 +416,6 @@ install-hybrid: install-server-generic
 install-server: install-server-generic
 
 install-common: build
-	./init/adduser.sh ${OSSEC_USER} ${OSSEC_USER_MAIL} ${OSSEC_USER_REM} ${OSSEC_GROUP} ${PREFIX}
 	$(call INSTALL_CMD,0550,root,${OSSEC_GROUP}) -d ${PREFIX}/
 	$(call INSTALL_CMD,0750,${OSSEC_USER},${OSSEC_GROUP}) -d ${PREFIX}/logs
 	$(call INSTALL_CMD,0660,${OSSEC_USER},${OSSEC_GROUP}) /dev/null ${PREFIX}/logs/ossec.log
@@ -1262,7 +1261,7 @@ ossec-makelists: analysisd/makelists-live.o ${analysisd_live_o} ${format_o} aler
 #### test ##########
 ####################
 
-CFLAGS_TEST = -g -O0 --coverage
+CFLAGS_TEST = -g -O0
 
 LDFLAGS_TEST = -lcheck -lm -pthread -lrt -lsubunit
 
@@ -1273,7 +1272,7 @@ endif #TEST
 
 test_programs = test_os_zlib test_os_xml test_os_regex test_os_crypto test_shared
 
-.PHONY: test run_tests build_tests test_valgrind test_coverage
+.PHONY: test run_tests build_tests test_valgrind
 
 test: build_tests
 	${MAKE} run_tests
