#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/common.sh

APK_TOOLS_URI='https://repository.fit.cvut.cz/mirrors/alpine/v3.3/main/x86_64/apk-tools-static-2.6.5-r1.apk'
APK_TOOLS_SHA256='03162d70e6d42eea77624a8da76d69e665ca19aa834361c3652414f111884636'


title 'Downloading apk-tools-static'

cd /tmp
wget "$APK_TOOLS_URI"
echo "$APK_TOOLS_SHA256  $(basename "$APK_TOOLS_URI")" | sha256sum -c
tar -xzf $(basename "$APK_TOOLS_URI")


title 'Installing Alpine Linux'

mkdir -p "$ALPINE_ROOT"/etc/apk
cd "$ALPINE_ROOT"

cp -R "$CLONE_DIR"/.travis/keys etc/apk/keys
cp "$CLONE_DIR"/.travis/repositories etc/apk/repositories
cp /etc/resolv.conf etc/resolv.conf

/tmp/sbin/apk.static \
	--root . --update-cache --initdb --no-progress \
	add alpine-base

mount -t proc none proc
mount --rbind /sys sys
mount --rbind /dev dev
