#!/sbin/openrc-run

name=domoticz
command=/usr/bin/$name
command_args="-dbase $dbase -userdata $userdata -wwwroot $wwwroot -pidfile $pidfile -syslog -daemon $daemon_args"
command_background=YES
start_stop_daemon_args="--user $user"

depend() {
        use logger dns
        need net
        after firewall
}

start_pre() {
        checkpath --directory --owner "$user" \
                --mode 0775 /var/run/"$name"
}

