#!/sbin/runscript

name=bitlbee
daemon=/usr/sbin/$name

. /etc/conf.d/$name

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting ${name}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${name}.pid \
			--user nobody:nobody \
			--exec ${daemon} -- ${PORT} ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${name}"
		start-stop-daemon --stop --signal 9 --quiet \
			--pidfile /var/run/$name.pid  \
			--exec ${daemon}
	eend $?
}

