#!/sbin/openrc-run
name="bitlbee"
description="bitlbee irc service"
supervisor=supervise-daemon
BITLBEE_USER=${BITLBEE_USER:-bitlbee}
LOGS=/var/log/bitlbee.log
supervise_daemon_args="-1 $LOGS -2 $LOGS"
command="/usr/bin/bitlbee"
command_args="-n"
command_user="$BITLBEE_USER:$BITLBEE_USER"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -f "$LOGS" -m 644 -o "$BITLBEE_USER:$BITLBEE_USER"
}
