if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# set fallback PS1; only if currently set to upstream bash default
if [ "$PS1" = '\s-\v\$ ' ]; then
	PS1='\h:\w\$ '
fi

if [ -r /etc/bash/bash_completion.sh ]; then
	. /etc/bash/bash_completion.sh
fi
