#!/sbin/runscript

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="openvcpd"
NAME=openvcpd
DAEMON=/usr/bin/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

start() {
	ebegin "OpenVCP Starting"
	start-stop-daemon --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS || return 1
	eend $?
}

stop() {
	ebegin "OpenVCP Stopping"
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	eend $?
}
