#!/sbin/runscript

depend () {
	use net
	after firewall
}

start() {
	ebegin "OpenVCP Starting"
	start-stop-daemon --start --quiet --background --exec /bin/openvcpd -- --pidfile /var/run/openvcpd.pid || return 1
	eend $?
}

stop() {
	ebegin "OpenVCP Stopping"
	kpid=`cat /var/run/openvcpd.pid`
	kill -kill `expr $kpid - 1`
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile /var/run/openvcpd.pid
	eend $?
}
