#!/sbin/openrc-run

# Upper case variables are for backward compatibility only.
: ${cfgfile:="/etc/oidentd.conf"}
: ${user:=${USER:-"nobody"}}
: ${group:=${GROUP:-"nobody"}}

command="/usr/sbin/oidentd"
command_args="
	--foreground
	--config $cfgfile
	--user $user
	--group $group
	${command_args:-$OPTIONS}"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"

required_files="$cfgfile"

depend() {
	need net
	after firewall
}
