#!/sbin/openrc-run

# Sample init.d file for alpine linux.

name=aprx
command="/usr/sbin/$name"
command_args="$DAEMON_OPTS"
command_background="yes"
pidfile="/run/$name.pid"

depend() {
	need net
	after firewall
}

start() {
  ebegin "Starting $pname"
  start-stop-daemon --start --pidfile $pidfile --exec $command
  eend $?
}

stop() {
  ebegin "Stopping $name"
  start-stop-daemon --stop --quiet --signal TERM --oknodo --pidfile $pidfile
  eend $? "Failed to stop $name"
}

