#!/sbin/runscript

NAME=dkimproxy

depend() {
	need net
	after firewall
}

launch() {
	ebegin "Starting ${DAEMON}"
		start-stop-daemon --start --quiet --background \
			--pidfile /var/run/${DAEMON}.pid \
			--exec ${DAEMON} -- ${OPTS}
	eend $?
}

terminate() {
	ebegin "Stopping ${DAEMON}"
		start-stop-daemon --stop --quiet \
			--exec ${DAEMON} \
			--pidfile /var/run/${DAEMON}.pid \
	eend $?
}

start() {
	DAEMON="${NAME}.in"
	launch
	DAEMON="${NAME}.out"
	launch
}

stop() {
	DAEMON="${NAME}.in"
	terminate
	DAEMON="${NAME}.out"
	terminate
}
