#!/sbin/openrc-run
name="gmnisrv"
description="gemini server daemon"
supervisor=supervise-daemon
command=/usr/bin/gmnisrv
command_args="-C $gmnisrv_config"
command_user="gmnisrv:gmnisrv"

start_pre() {
	[ -n "$output_log" ] && checkpath -f "$output_log" -o gmnisrv:gmnisrv
	[ -n "$error_log" ] && checkpath -f "$error_log" -o gmnisrv:gmnisrv
	certs="$(grep '^store=' "$gmnisrv_config" | cut -d= -f2-)"
	checkpath -d "$certs" -o gmnisrv:gmnisrv
}
