#!/sbin/openrc-run

supervisor=supervise-daemon

name="Woodpecker CI agent"

command="/usr/bin/woodpecker-agent"
command_user="woodpecker:woodpecker"
directory="/var/lib/woodpecker"

error_log="/var/log/woodpecker/agent.log"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -f -m 640 -o "woodpecker:woodpecker" /etc/woodpecker/agent.conf
	checkpath -d -m 755 -o "woodpecker:woodpecker" /var/lib/woodpecker
	checkpath -f -m 644 -o "woodpecker:woodpecker" /var/log/woodpecker/agent.log

	# Source and export configuration variables
	set -a
	source /etc/woodpecker/agent.conf
	set +a
}
