#!/sbin/openrc-run
#
# CGroups Rules Engine Daemon
#
# This is a daemon for automatically classifying processes into cgroups based
# on UID/GID.
#
extra_started_commands="reload"

name="CGroup Rules Engine Daemon"
command="/usr/sbin/cgrulesengd"
pidfile=${PID_FILE:-"/var/run/cgred.pid"}
command_args="${NODAEMON} ${LOG}"
start_stop_daemon_args="--make-pidfile --background --stdout /dev/null"


depend() {
	need cgconfig
	use logger
}

start_pre() {
	if [ -n "${LOG_FILE}" ]; then
		command_args="${command_args} --log-file=${LOG_FILE}"
	fi
}

reload() {
	ebegin "Reloading ${name}"
	start-stop-daemon --signal USR2 --pidfile "${pidfile}" \
		--exec "${command}"
	eend $?
}

