#!/sbin/openrc-run

: ${user:=${EJABBERD_USER:-"ejabberd"}}
: ${group:=${EJABBERD_GROUP:-"ejabberd"}}
: ${pidfile:=${EJABBERD_PIDFILE:-"/run/ejabberd/ejabberd.pid"}}

command="/usr/sbin/ejabberdctl"
start_stop_daemon_args="
        --user $user
        --group $group
        --pidfile $pidfile
        --progress
        -e EJABBERD_PID_PATH=$pidfile"

depend() {
        use dns
        need net
        provide jabber-server
}

start_pre() {
        checkpath -d -m 1775 -o $user:$group "$(dirname $pidfile)"
}

start() {
        ebegin "Starting ejabberd"
        start-stop-daemon --start \
                $start_stop_daemon_args \
                --wait 3000 \
                --exec "$command" \
                -- start ${EJABBERDCTL_OPT}
        retval=$?

        if [ $retval -ne 0 ]; then
                einfo "Please check the logs to see what's going on."
        fi
        eend $retval
}

stop() {
        ebegin "Stopping ejabberd"
        start-stop-daemon --stop \
                $start_stop_daemon_args \
                --exec "$command" \
                -- stop
        retval=$?

        if [ $retval -ne 0 ]; then
                einfo "Please, run '/usr/sbin/ejabberdctl stop' to see what's going on."
        fi
        eend $retval
}
