diff --git a/Makefile.in b/Makefile.in
index 0d91344..1276950 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -87,6 +87,7 @@ deps/.got:
 	$(REBAR) get-deps && :> deps/.got
 
 deps/.built: deps/.got
+	$(SED) -i -e "23 i#include \<stdint.h\>"  deps/stringprep/c_src/stringprep.cpp
 	$(REBAR) compile && :> deps/.built
 
 src: deps/.built
