#!/sbin/openrc-run

name="tofutf agent"

: ${command_user:="tofutf:tofutf"}

command="/usr/bin/tofutf-agent"
command_args="--token $(cat $token_file) $command_args"
command_background="yes"
error_log="/var/log/tofutf-agent.log"
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need net
	after firewall
}

start_pre() {
        checkpath -f --owner "$command_user" --mode 0644 \
                $error_log
}
