#!/sbin/openrc-run
#
# AWS EFS service script for Alpine Linux
#
# See https://wiki.alpinelinux.org/wiki/Writing_Init_Scripts
# See https://github.com/OpenRC/openrc/blob/master/service-script-guide.md
# See https://github.com/OpenRC/openrc/blob/master/supervise-daemon-guide.md
#
command="/usr/bin/amazon-efs-mount-watchdog"
command_background=true
start_stop_daemon_args="-1 /var/log/amazon/efs/mount-watchdog.log -2 /var/log/amazon/efs/mount-watchdog.log"
pidfile="/var/run/efs.pid"
supervisor=supervise-daemon
respawn_delay=15
respawn_max=1
respawn_period=15

depend() {
  need networking
  use network-online
  provide amazon-efs-mount-watchdog
}
