#!/sbin/runscript

extra_started_commands="reload"

depend() {
	need logger
	use antivirus net
	provide mta
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet --exec /usr/sbin/${SVCNAME} --pidfile /var/run/${SVCNAME}.pid -- ${EXIM_OPTS:--bd -q15m}
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --pidfile /var/run/${SVCNAME}.pid --name ${SVCNAME}
	eend $?
}

reload() {
	ebegin "Reloading ${SVCNAME}"
	start-stop-daemon --signal HUP --pidfile /var/run/${SVCNAME}.pid --name ${SVCNAME}
	eend $?
}
