#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# Removed start_pre since full of bashism

my_daemon="shellinaboxd"
pidfile="/var/run/${my_daemon}/${my_daemon}.pid"
command="/usr/bin/${my_daemon}"
command_args="${SIAB_OPTS}"

depend() {
    use net
}

start() {
    ebegin "Starting ${my_daemon}"
    start-stop-daemon \
        --start \
        --background \
        --pidfile ${pidfile} \
        --make-pidfile \
        --exec ${command} \
        -- ${command_args}
    eend $?
}

stop() {
    ebegin "Stopping ${my_daemon}"
    start-stop-daemon \
        --stop \
        --pidfile ${pidfile}
    eend $?
}
