#!/sbin/openrc-run

command="/usr/sbin/grafana-server"
command_args="$GRAFANA_OPTS"
command_background=yes
command_user=grafana:grafana
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need net
	after firewall
}

start_pre() {
        checkpath -d -o grafana:grafana -m755 $GRAFANA_HOME \
                $GRAFANA_HOME/provisioning \
                $GRAFANA_HOME/provisioning/dashboards \
                $GRAFANA_HOME/provisioning/datasources \
                $GRAFANA_HOME/provisioning/notifiers
}
