#!/sbin/runscript

depends() {
	needs network
	provide logstash
}

description="logstash"
command="/usr/share/logstash/bin/logstash"
pidfile="/var/run/logstash/logstash.pid"
start_stop_daemon_args="--user logstash"
command_args="${LS_OPTS}"

start_pre() {
	checkpath --owner logstash:daemon --directory ${pidfile%/*}
}

start() {
	ebegin "Starting logstash"
	start-stop-daemon $start_stop_daemon_args --background --start --exec \
		$command --make-pidfile --pidfile $pidfile -- $command_args 
	eend $?
}

# uses the openrc templates for start()/stop()
