#!/sbin/openrc-run
name=puma
command=/usr/bin/puma
pidfile=/var/run/puma/puma.pid
command_args="--daemon --pidfile $pidfile ${puma_args}"
start_stop_daemon_args="--background --user $puma_user --group $puma_group --chdir $puma_approot"

depend() {
        use logger dns
        need net
        after firewall
}

start_pre() {
        checkpath --directory --owner $puma_user:$puma_group --mode 0775 \
        /var/run/$name
}

