#!/sbin/openrc-run

name="Notus Scanner"

: ${notus_scanner_pidfile="/run/notus-scanner/notus-scanner.pid"}
: ${notus_scanner_user="gvm"}

notus_scanner_group="gvm"
pidfile=${notus_scanner_pidfile}

command=/usr/bin/notus-scanner
command_interpreter="/usr/bin/python3"
command_args="--pid-file ${pidfile} --products-directory /var/lib/notus/products --log-file /var/log/gvm/notus-scanner.log ${notus_scanner_flags}"
