#!/sbin/openrc-run
name="pushgateway"
description="Prometheus push acceptor for ephemeral and batch jobs"
supervisor=supervise-daemon
command=/usr/bin/pushgateway
command_args="--web.listen-address=$pushgateway_bind_address"
command_user="prometheus:prometheus"

start_pre() {
	[ -n "$output_log" ] && checkpath -f "$output_log" \
		-m 644 -o prometheus:prometheus
	[ -n "$error_log" ] && checkpath -f "$error_log" \
		-m 644 -o prometheus:prometheus
}
