#!/sbin/runscript

daemon=/usr/sbin/kamailio
pidfile=/var/run/kamailio/kamailio.pid

depend() {
	need net
}

start() {
	ebegin "Starting Kamailio"
	start-stop-daemon --start --quiet --pidfile $pidfile --exec $daemon \
		-- \
		-u ${KAMAILIO_USER:-opensips} \
		-g ${KAMAILIO_GROUP:-opensips} \
		-P $pidfile  
	eend $?
}

stop() {
	ebegin "Stopping Kamailio"
	start-stop-daemon --stop --quiet --pidfile $pidfile
	eend $?
}
