--- a/Makefile
+++ b/Makefile
@@ -21,11 +21,11 @@
 	install -D -m644 40-usb_modeswitch.rules $(RULESDIR)/40-usb_modeswitch.rules
 
 db-install:
-	install -m644 -t $(PREFIX)/share/usb_modeswitch ./usb_modeswitch.d/*
+	cp ./usb_modeswitch.d/* $(PREFIX)/share/usb_modeswitch
 
 db-install-packed:
 	cd ./usb_modeswitch.d; tar -czf ../configPack.tar.gz *
-	install -m644 -t $(PREFIX)/share/usb_modeswitch ./configPack.tar.gz
+	install -m644 $(PREFIX)/share/usb_modeswitch ./configPack.tar.gz
 	rm -f ./configPack.tar.gz
 
 
