#!/bin/sh
CASKPATH="/usr/share/emacs/site-lisp/cask/"
for elpa in $(find $CASKPATH -name "elpa" -type d) ; do
	for d in $(ls -d $CASKPATH/* | sort) ; do
		dirs="$dirs:$d"
	done
done
for b in $(find $CASKPATH -name "bin" -type d) ; do
	bindirs="$bindirs:$b"
done
export EMACSLOADPATH="$dirs:$CASKPATH:$EMACSLOADPATH"
export PATH="$bindirs:$PATH"
cask $@
