Don't run tests on install.

--- a/Makefile
+++ b/Makefile
@@ -165,7 +165,7 @@
 W/imapsync.1: imapsync
 	pod2man imapsync > W/imapsync.1
 
-install: testp W/imapsync.1
+install: W/imapsync.1
 	mkdir -p $(DESTDIR)$(PREFIX)/bin
 	install imapsync $(DESTDIR)$(PREFIX)/bin/imapsync
 	chmod 755 $(DESTDIR)$(PREFIX)/bin/imapsync
@@ -708,4 +708,4 @@
 	rsync -aHv  --delete ./FAQ.d/        ../imapsync_website/FAQ.d/
 	rsync -avH  --delete ./doc/          ../imapsync_website/doc/
 	rsync -aHvz --delete ../imapsync_website/ root@ks.lamiral.info:/var/www/imapsync/
-	ssh root@ks.lamiral.info 'apachectl configtest && /etc/init.d/apache2 reload'
\ No newline at end of file
+	ssh root@ks.lamiral.info 'apachectl configtest && /etc/init.d/apache2 reload'
