#!/bin/sh

HOME=/var/amavis
QUARANTINE=$HOME/quarantine
USER=amavis
GROUP=amavis
DIRS="$HOME $HOME/tmp $HOME/var $HOME/db $HOME/home $QUARANTINE"
CONFIG=/etc/amavisd.conf

addgroup $USER
adduser -h $HOME -s /bin/false -G $GROUP -D $USER
chown -R $USER:$GROUP $HOME
chmod -R 750 $HOME
chown root:$GROUP $CONFIG
