#!/bin/sh
dirs=""
for elpa in $(find /usr/share/emacs/site-lisp/emacs-ycmd/ -name "elpa" -type d) ; do
	for d in $(ls -d $elpa/* | sort) ; do
		dirs="$dirs:$d"
	done
done
local pv=$(python3 -c 'import sys; print("%i.%i" % (sys.version_info.major, sys.version_info.minor))')
local pydirs=
for pd in $(ls -d /usr/lib/python${pv}/site-packages/ycmd/third_party/* | sort) ; do
	pydirs="$pydirs:$pd"
done
export PYTHONPATH="/usr/lib/python${pv}/site-packages/jedi:$pydirs:$PYTHONPATH"
export EMACSLOADPATH="$dirs:$EMACSLOADPATH"
emacs $@
