--- a/makefile
+++ b/makefile
@@ -226,7 +226,6 @@
 	echo "#define LINKER_OPT_DYN_LINK_LIBS \"-ldl\"" >> chkccomp.h
 	echo "#define POTENTIAL_PARTIAL_LINKING_OPTIONS \"-r\", \"-r -nostdlib\"" >> chkccomp.h
 	echo "#define USE_GMP 0" >> chkccomp.h
-	echo "#define ALLOW_REPLACEMENT_OF_SYSTEM_HEADERS" >> chkccomp.h
 
 base.h:
 	echo "#define PATH_DELIMITER '/'" > base.h
