#!/sbin/openrc-run

command="/usr/share/ovn/scripts/ovn-ctl"
command_args="start_controller --ovn-manage-ovsdb=no --no-monitor $OVN_CTL_OPTS"
command_background="yes"
pidfile="/run/ovn/$RC_SVCNAME.pid"
description="Open Virtual Network host control daemon"

depend() {
	need net ovs-vswitchd
	after firewall
}

start_pre() {
	checkpath --directory "${pidfile%/*}"
}

stop() {
	ebegin "Stopping $RC_SVCNAME"
	$command stop_controller --no-monitor
	eend $?
}
