#!/sbin/openrc-run

command="/usr/share/ovn/scripts/ovn-ctl"
command_args="run_sb_ovsdb $OVN_CTL_OPTS"
command_background="yes"
pidfile="/run/ovn/$RC_SVCNAME.pid"
description="Open vSwitch database server for OVN Southbound database"

depend() {
	need net ovn-northd
	after firewall
}

start_pre() {
	checkpath --directory "${pidfile%/*}"
}

stop() {
	ebegin "Stopping $RC_SVCNAME"
	$command stop_sb_ovsdb
	eend $?
}
