#!/sbin/openrc-run

name="Docker registry authentication server"

command="/usr/bin/docker-auth"
# Without `-logtostderr=true` the daemon litters /tmp with logfiles
command_args="-logtostderr=true $cfgfile"
command_background="yes"
logfile="/var/log/${RC_SVCNAME}.log"
error_log="$logfile"
output_log="$logfile"
pidfile="/run/${RC_SVCNAME}.pid"

required_files="$cfgfile"

start_pre() {
	if [ "$logfile" ]; then
		checkpath -f -m 0644 -o "$command_user" "$logfile" || return 1
	fi
}
