#!/sbin/runscript

depend() {
	need xencommons
	before xendomains
}

await_daemons_up() {
	i=1
	rets=10
	/usr/sbin/xend status
	while [ $? -ne 0 -a $i -lt $rets ]; do
		sleep 1
		i=$(($i + 1))
		/usr/sbin/xend status
	done
}

start() {
	ebegin "Starting Xen daemons"
	if [ -z "`ps xenconsoled -o pid=`" ]; then
		eend 1
		echo "xencommons should be started first."
		exit 1
	fi
	mkdir -p /var/lock
	if [ -d /var/lock/subsys ]; then
		touch /var/lock/subsys/xend
	else
		touch /var/lock/xend
	fi
	/usr/sbin/xend start
	await_daemons_up
	eend $?
}

stop() {
	ebegin "Stopping Xen control daemon"
	/usr/sbin/xend stop
	rm -f /var/lock/subsys/xend /var/lock/xend
	eend $?
}

restart() {
	ebegin "Restarting Xen control daemon"
	/usr/sbin/xend restart
	await_daemons_up
	eend $?
}

status() {
	/usr/sbin/xend status
}
