--- ./Makefile.orig
+++ ./Makefile
@@ -7,7 +7,7 @@
 VERSION=$(shell grep package_version src/version.h | cut -f2)
 
 compile: 
-	cd src && $(MAKE) -$(MAKEFLAGS) 
+	cd src && $(MAKE)
 
 install: compile
 	./install.sh $(BINDIR)
@@ -16,7 +16,7 @@
 	./uninstall.sh $(BINDIR)
 
 clean:
-	cd src && $(MAKE) -$(MAKEFLAGS) clean
+	cd src && $(MAKE) clean
 
 package: compile clean
 	./package.sh
--- ./src/Makefile.orig
+++ ./src/Makefile
@@ -37,15 +37,15 @@
 # Use the following only on GNU/Linux and only if you need ps listing like "smsd: MAINPROCESS" and "smsd: GSM1"
 # CFLAGS += -D USE_LINUX_PS_TRICK
 
-all: smsd 
-
-smsd: smsd.c extras.o locking.o cfgfile.o logging.o alarm.o smsd_cfg.o charset.o stats.o blacklist.o whitelist.o modeminit.o pdu.o
-
 ifneq (,$(findstring SOLARIS,$(CFLAGS)))
 ifeq (,$(findstring DISABLE_INET_SOCKET,$(CFLAGS)))
 override LFLAGS += -lsocket -lnsl
 endif
 endif
+
+all: smsd 
+
+smsd: smsd.c extras.o locking.o cfgfile.o logging.o alarm.o smsd_cfg.o charset.o stats.o blacklist.o whitelist.o modeminit.o pdu.o
 
 ifneq (,$(findstring NOSTATS,$(CFLAGS)))
 	$(CC) $(CFLAGS) -o $@ $^ $(LFLAGS)
