#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --exec "/usr/sbin/hiawatha" \
		--pidfile "/var/run/hiawatha.pid"
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --exec "/usr/sbin/hiawatha" \
		--pidfile "/var/run/hiawatha.pid"
	eend $?
}
