#!/sbin/runscript

# Sample init.d file for alpine linux.

name=tor
daemon=/usr/bin/$name

depend() {
	need net
	after firewall
        provide $name
}

start() {
	ebegin "Starting ${name}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${name}.pid \
			-u ${name} \
			--exec ${daemon} -- --runasdaemon 1
	eend $?
}

stop() {
	ebegin "Stopping ${name}"
		start-stop-daemon --stop --quiet \
			--pidfile /var/run/$name.pid \
			--exec ${daemon}
	eend $?
}

