#!/sbin/openrc-run

name=cloudi
command="/usr/bin/$name"
command_args=""
command_background="false"

description="CloudI is an open-source private cloud computing framework for efficient, scalable, and stable soft-realtime event processing."

extra_started_commands="attach"
description_attach="Attach to the running CloudI Erlang shell"

depend() {
	need localmount
	need net
	after firewall
}
start() {
	$command start
}
stop() {
	$command stop
}
restart() {
	$command restart
}
attach() {
	$command attach
}
