#!/sbin/openrc-run
supervisor=supervise-daemon

name=radicale
description="A simple CalDAV (calendar) and CardDAV (contact) server"

command=/usr/bin/radicale
command_args_foreground="--foreground"

command_user=radicale:radicale

depend() {
	use net
	need localmount
}

pre_start() {
	checkpath --directory --owner radicale /var/lib/radicale
	checkpath --directory --owner radicale /var/log/radicale
	checkpath --file --owner root:radicale --mode 0640 /etc/radicale/config
	checkpath --file --owner root:radicale --mode 0640 /etc/radicale/logging
}
