#!/sbin/openrc-run

VAULT_LOG_FILE="/var/log/${SVCNAME}.log"

description="Vault is a tool for securely accessing secrets"
command=/usr/sbin/${SVCNAME}
command_args="${vault_opts}"
command_background="true"
start_stop_daemon_args="-w 100 --user ${SVCNAME}:${SVCNAME}  --stdout $VAULT_LOG_FILE --stderr $VAULT_LOG_FILE"
pidfile="/run/${SVCNAME}.pid"

start_pre() {
	checkpath -f -m 0644 -o ${SVCNAME}:${SVCNAME} "$VAULT_LOG_FILE"
}

depend() {
        need net
        after firewall
}
