#!/sbin/openrc-run

name=nut-server
pidfile=/var/run/nut/upsd.pid
command=/usr/sbin/upsd
required_files="/etc/nut/nut.conf /etc/nut/upsd.conf"
extra_started_commands="reload"

depend() {
	use net
}

start_pre() {
	. /etc/nut/nut.conf
	case $MODE in
	standalone|netserver)
		checkpath -d --owner nut:nut --mode 750 ${pidfile%/*} || return 1
		/usr/sbin/upsdrvctl start > /dev/null
		;;
	none)
		eerror "$name disabled, please adjust the configuration to your needs"
		eerror "Then set MODE to a suitable value in /etc/nut/nut.conf to enable it"
		return 1
		;;
	*)
		return 1
		;;
	esac
}

stop_post() {
	/usr/sbin/upsdrvctl stop > /dev/null
}

reload() {
	ebegin "Reloading $name"
	start-stop-daemon --signal HUP --pidfile ${pidfile}
	eend $?
}
