#!/sbin/runscript

daemon=/usr/sbin/opensips
pidfile=/var/run/opensips/opensips.pid

depend() {
	need net
}

start() {
	ebegin "Starting OpenSIPS"
	start-stop-daemon --start --quiet --pidfile $pidfile --exec $daemon \
		-- \
		-u ${OPENSIPS_USER:-opensips} \
		-g ${OPENSIPS_GROUP:-opensips} \
		-P $pidfile  
	eend $?
}

stop() {
	ebegin "Stopping OpenSIPS"
	start-stop-daemon --stop --quiet --pidfile $pidfile
	eend $?
}

