#!/sbin/openrc-run

name="Authelia"
description="Single Sign-On Multi-Factor portal for web apps"

: "${command_user:="authelia:authelia"}"
: "${cfgfile:="/etc/authelia/configuration.yml"}"

command="/usr/bin/authelia"
command_args="--config $cfgfile $command_args"
directory="/var/lib/authelia"
supervisor="supervise-daemon"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath --directory --owner "$command_user" --mode 0750 "$directory"
}
