#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-crypt/heimdal/files/heimdal-kpasswdd,v 1.3 2004/09/13 22:44:54 solar Exp $

depend() {
	need net
	use heimdal-kdc
	after logger
}

start() {
	ebegin "Starting heimdal kpasswdd"
	start-stop-daemon --background --start --quiet --exec \
		/usr/sbin/kpasswdd
	eend $?
}

stop() {
	ebegin "Stopping heimdal kpasswdd"
	start-stop-daemon --stop --quiet --exec \
		/usr/sbin/kpasswdd
	eend $?
}
