--- a/Makefile
+++ b/Makefile
@@ -1,8 +1,8 @@
 all: build
 
-GIT_COMMIT:=$(shell git rev-list -1 HEAD)
-GIT_LAST_TAG:=$(shell git describe --abbrev=0 --tags)
-GIT_EXACT_TAG:=$(shell git name-rev --name-only --tags HEAD)
+GIT_COMMIT?=$(shell git rev-list -1 HEAD)
+GIT_LAST_TAG?=$(shell git describe --abbrev=0 --tags)
+GIT_EXACT_TAG?=$(shell git name-rev --name-only --tags HEAD)
 UNAME_S := $(shell uname -s)
 XARGS:=xargs -r
 ifeq ($(UNAME_S),Darwin)
