#! /sbin/openrc-run

description="darkhttpd web server"
command="/usr/bin/darkhttpd"
command_args="${document_root:-/var/www/localhost/htdocs} --chroot --daemon --uid darkhttpd --gid www-data --log /var/log/darkhttpd/access.log $darkhttpd_args"
procname="darkhttpd"
pidfile=""
stopsig="SIGTERM"

optional_arg() {
	if [ -n "$2" ]; then
		command_args="$command_args $1 $2"
	fi
}

start_pre() {
	optional_arg --addr "$addr"
	optional_arg --port "$port"
	optional_arg --mimetypes "$mimetypes"
}
