#!/sbin/openrc-run

name=apt-swarm
description="apt-swarm p2p daemon"
command=/usr/bin/apt-swarm
command_args="p2p $apt_swarm_args"
command_user="$apt_swarm_user:$apt_swarm_group"
command_background=true
pidfile="/run/$RC_SVCNAME.pid"

error_logger="logger -t '${RC_SVCNAME}' -p daemon.info"

depend() {
	use dns logger
	need localmount net
	after firewall
}

start_pre() {
	checkpath --directory --owner "$command_user" "$APT_SWARM_DATA_PATH"
}
