#!/sbin/openrc-run

CONFIG=/etc/dcmtk/dcmqrscp.cfg

depend() {
	need net
}

start() {
	ebegin "Starting DCMTK central test node dcmqrscp"
	start-stop-daemon --start --quiet --background \
		--make-pidfile --pidfile "/var/run/${SVCNAME}.pid" \
		--exec /usr/bin/dcmqrscp -- -c "${CONFIG}"
	eend ${?}
}

stop() {
	ebegin "Stopping DCMTK central test node dcmqrscp"
	start-stop-daemon --stop --quiet --pidfile "/var/run/${SVCNAME}.pid"
	eend ${?}
}
