#!/sbin/runscript

depend() {
        need net
        after firewall
}

checkconfig() {
     if [ ! -e "${CONF}" ] ; then
                eerror "You need a ${CONF} file to run sniproxy"
                return 1
     fi
}

start() {
        checkconfig || return 1
        ebegin "Starting ${SVCNAME}"
        start-stop-daemon --start \
                --exec "${CMD}" --pidfile "${PIDFILE}" \
                -- -c "${CONF}"
        eend $?
}

stop() {
        checkconfig || return 1
        ebegin "Stopping ${SVCNAME}"
        start-stop-daemon --stop --exec "${CMD}" \
                --pidfile "${PIDFILE}" --quiet
        eend $?
}

