#!/sbin/openrc-run

depend()
{
	need net wpa_supplicant
}

start()
{
	ebegin "Starting wpa_actiond"
	start-stop-daemon --start --quiet --exec /usr/sbin/wpa_actiond -p /var/run/wpa_actiond.pid -- \
		-i ${WPA_ACTIOND_INTERFACE} -a ${WPA_ACTIOND_SCRIPT} ${WPA_ACTIOND_OPTS}
	eend $?
}

stop()
{
	ebegin "Stopping wpa_actiond"
	start-stop-daemon --stop --quiet --exec /usr/sbin/wpa_actiond -p /var/run/wpa_actiond.pid
	eend $?
}

