Don't create /var/lib/soju, it's done by soju.pre-install script
with proper permissions.

diff --git a/Makefile b/Makefile
index af65f77..4cb971b 100644
--- a/Makefile
+++ b/Makefile
@@ -33,7 +33,6 @@ install:
 	mkdir -p $(DESTDIR)$(PREFIX)/$(BINDIR)
 	mkdir -p $(DESTDIR)$(PREFIX)/$(MANDIR)/man1
 	mkdir -p $(DESTDIR)$(SYSCONFDIR)/soju
-	mkdir -p $(DESTDIR)$(sharedstatedir)/soju
 	cp -f $(commands) $(DESTDIR)$(PREFIX)/$(BINDIR)
 	cp -f $(man_pages) $(DESTDIR)$(PREFIX)/$(MANDIR)/man1
 	[ -f $(DESTDIR)$(config_path) ] || cp -f config.in $(DESTDIR)$(config_path)
