#!/sbin/openrc-run

# init.d file for atd (command scheduling daemon)

command="/usr/sbin/$SVCNAME"
pidfile="/var/run/$SVCNAME.pid"

depend() {
	after localmount
}

start() {
	ebegin "Starting command scheduling daemon ${SVCNAME}"
		start-stop-daemon --start --quiet \
			--pidfile ${pidfile} \
			--exec ${command}
	eend $?
}

stop() {
	ebegin "Stopping command scheduling daemon ${name}"
		start-stop-daemon --stop --quiet \
			--pidfile ${pidfile} \
			--exec ${command}
	eend $?
}

