#!/sbin/openrc-run
# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="remotely control an OpenVAS Scanner"
command="/usr/bin/ospd-openvas"
command_args="${OSPD_OPENVAS_OPTIONS} \
	${OSPD_OPENVAS_UNIX_SOCKET} \
	${OSPD_OPENVAS_SOCKET_MODE} \
	--config /etc/openvas/ospd.conf"

pidfile="/run/ospd-openvas.pid"
command_background="true"

depend() {
	after bootmisc
	need localmount redis
}
