#!/sbin/openrc-run
# Contributor: Wang Qi <ericwq057@qq.com>
# Maintainer: Wang Qi <ericwq057@qq.com>
#
name="apshd"
description="apshd daemon for the aprilsh service"

export GOMAXPROCS=1
command=/usr/bin/apshd
command_args=""
supervisor=supervise-daemon
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
error_log="/var/log/${RC_SVCNAME}.log"

depend() {
    need sshd
    want utmpd logger
    after networking
}
