#!/sbin/runscript
#

PIDFILE="/var/run/dbmail/timsieved.pid"

depend() {
	need net
	use mysql
	use pgsql
	after mta
}

checkconfig() checkconfig() {
        if [ ! -e "/etc/dbmail.conf" ]; then
                eerror "You need to create apropriate config"
                eerror "/etc/dbmail.conf"
                return 1
        fi
        # Avoid using root's TMPDIR
        unset TMPDIR
}

start() {
	checkconfig && \
	ebegin "Starting DBMail SIEVE daemon"
	    start-stop-daemon --start --quiet \
		--exec /usr/sbin/dbmail-timsieved \
		-- -p ${PIDFILE} -f /etc/dbmail.conf 2>&1
	eend $?
}	

stop() {
	ebegin "Stopping DBMail SIEVE daemon"
	    start-stop-daemon --stop --quiet --retry 5 \
		--pidfile ${PIDFILE}
	eend $?
}	

