#!/sbin/runscript
#

PIDFILE="/var/run/dbmail/lmtpd.pid"

depend() {
	need net
	use mysql
	use pgsql
	after mta
}

checkconfig() {
	if [ ! -e "/etc/dbmail.conf" ]; then
		eerror "You need to create apropriate config"
		eerror "/etc/dbmail.conf"
		return 1
	fi
	# Avoid using root's TMPDIR
	unset TMPDIR
}


start() {
	checkconfig && \
	ebegin "Starting DBMail LMTP daemon"
	    start-stop-daemon --start --quiet \
		--exec /usr/sbin/dbmail-lmtpd \
		--name dbmail-lmtpd \
		-- -p ${PIDFILE} -f /etc/dbmail.conf 2>&1
	eend $?
}	

stop() {
	ebegin "Stopping DBMail LMTP daemon"
	    start-stop-daemon --stop --quiet --retry 5 \
		--pidfile ${PIDFILE}
	eend $?
}	

