#!/sbin/openrc-run

# fallback values for /etc/conf.d/lidarr
: ${command_user:=lidarr:lidarr}
: ${directory:=/var/lib/lidarr}
: ${umask:=0002}

name=lidarr
description="Lidarr daemon"
command="/usr/lib/lidarr/bin/Lidarr"
command_args="-nobrowser -data=$directory"
command_background=true
pidfile="/run/$name.pid"

depend() {
	need net
	use dns logger netmount
}

start_pre() {
	checkpath -d -o "$command_user" "$directory"

	if [ -n "$logdir" ]; then
		checkpath -d -o "$command_user" "$logdir"
	fi

	if [ -n "$output_log" ]; then
		checkpath -f -o "$command_user" "$output_log"
	fi

	if [ -n "$error_log" ]; then
		checkpath -f -o "$command_user" "$error_log"
	fi
}
