#!/sbin/openrc-run

: ${port:=9102}
: ${cfgfile:=/etc/bacula/bacula-fd.conf}
: ${exec_user:=root}
: ${exec_group:=root}

name="Bacula File Daemon"
command="/usr/sbin/$RC_SVCNAME"
command_args="-u $exec_user -g $exec_group -c $cfgfile"
pidfile="/var/run/bacula/$RC_SVCNAME.$port.pid"

depend() {
	need net
	use dns
}

start_pre() {
        checkpath -d -m 0775 -o ${exec_user}:${exec_group} /var/run/bacula
}

