#!/sbin/openrc-run

: ${port:=9101}
: ${cfgfile:=/etc/bacula/bacula-dir.conf}
: ${command_user:=bacula}
: ${command_group:=bacula}

name="Bacula Director"
command="/usr/sbin/${RC_SVCNAME}"
command_args="-c $cfgfile"
start_stop_daemon_args="--user $command_user --group $command_group"
pidfile="/run/bacula/${RC_SVCNAME}.$port.pid"

depend() {
	need net
	use dns
	after firewall
}

start_pre() {
        checkpath --directory --mode 0775 \
		--owner ${command_user}:${command_group} /run/bacula
}

