#!/sbin/openrc-run

: ${port:=9103}
: ${cfgfile:=/etc/bacula/bacula-dir.conf}
: ${exec_user:=bacula}
: ${exec_group:=bacula}

name="Bacula Storage Daemon"
command="/usr/sbin/$RC_SVCNAME"
command_args="-u $exec_user -g $exec_group -c $cfgfile"
pidfile="/var/run/bacula/$RC_SVCNAME.$port.pid"

depend() {
	need net
	use dns
}

start_pre() {
        checkpath -d -m 0775 -o ${exec_user}:${exec_group} /var/run/bacula
}
