#!/sbin/openrc-run

GDM_LOG_FILE="/var/log/${SVCNAME}.log"

description="GNOME display manager"
command=/usr/sbin/${SVCNAME}
command_args="${gdm_opts}"
command_background="true"
start_stop_daemon_args="-w 100 --user ${SVCNAME}:${SVCNAME}  --stdout $GDM_LOG_FILE --stderr $GDM_LOG_FILE"
pidfile="/run/${SVCNAME}.pid"

start_pre() {
        checkpath -f -m 0644 -o ${SVCNAME}:${SVCNAME} "$GDM_LOG_FILE"
}

depend() {
        need net
}
