#!/sbin/runscript
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

KEEPALIVED_BIN="/usr/sbin/keepalived"
KEEPALIVED_CFG=${KEEPALIVED_CFG:-/etc/keepalived/keepalived.conf}

depend() {
	use logger
	need net
	after firewall
}

start() {
	ebegin "Starting keepalived"
	start-stop-daemon --start --exec "${KEEPALIVED_BIN}" \
		-- -f "${KEEPALIVED_CFG}" ${KEEPALIVED_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping keepalived"
	start-stop-daemon --stop --exec "${KEEPALIVED_BIN}"
	eend $?
}
