#!/sbin/openrc-run
name="yggdrasil"
description="An experiment in scalable routing as an encrypted IPv6 overlay network"
supervisor=supervise-daemon
command=/usr/bin/yggdrasil
command_args="-useconffile $yggdrasil_config_file"
command_user="yggdrasil:yggdrasil"

depend() {
	need net
	after firewall
	before radvd
}

start_pre() {
	[ -n "$output_log" ] && checkpath -f "$output_log" \
		-m 644 -o yggdrasil:yggdrasil || true
	[ -n "$error_log" ] && checkpath -f "$error_log" \
		-m 644 -o yggdrasil:yggdrasil || true
	checkpath /var/run/yggdrasil.sock -m 755 -o yggdrasil:yggdrasil
}
