#!/sbin/runscript

NAME=lsyncd
DAEMON=/usr/bin/$NAME
USER=daemon
CONF=/etc/lsyncd/lrsync.lua

depend() {
        need net
}

start() {
        ebegin "Starting $NAME"
                start-stop-daemon --start --quiet \
			--user $USER \
                        --exec $DAEMON -- \
			$CONF
        eend $?
}

stop() {
        ebegin "Stopping $NAME"
                start-stop-daemon --stop --quiet \
                        --exec $DAEMON
        eend $?
}
