#!/sbin/runscript

NAME="grossd"
DAEMON="/usr/sbin/$NAME"
USER="gross"
GROUP="gross"

depend() {
	need net
	after firewall
}

check_config() {
	if [ ! -f /var/db/gross/state ] ; then
		einfo "Generating Gross database..."
		install -dD -o${USER} -g${GROUP} /var/db/gross
		${DAEMON} -Cu ${USER} > /dev/null
	fi
}

start() {
	check_config || return 1
	ebegin "Starting ${NAME}"
	start-stop-daemon --start --quiet --background \
		--exec ${DAEMON} -- \
		-p /var/run/gross/grossd.pid \
		-u ${USER} ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${NAME}"
	start-stop-daemon --stop --pidfile /var/run/gross/grossd.pid
	eend $?
}

