diff '--color=auto' -Naur a/makefile b/makefile
diff --git a/makefile b/makefile
index e4ec5de..7dd0e4c 100644
--- a/makefile
+++ b/makefile
@@ -274,16 +274,11 @@ TRACING =
 #TRACING = -g -fno-omit-frame-pointer -fsanitize=undefined
 #TRACING = -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-recover
 
-#PREFIX	= /home/jeff
-PREFIX	= /usr/local
+PREFIX	= /usr
 BINDIR	= $(PREFIX)/bin
-#LOUTLIBDIR	= $(PREFIX)/lout.lib
-#LOUTDOCDIR	= $(PREFIX)/lout.doc
-#MANDIR	= $(PREFIX)/lout.man
-LIBDIR	= $(PREFIX)/share/lout-$(VERSION)
-LOUTLIBDIR	= $(LIBDIR)/lib
-LOUTDOCDIR	= $(LIBDIR)/doc
-MANDIR	= $(LIBDIR)/man
+LOUTLIBDIR = $(PREFIX)/share/lout
+LOUTDOCDIR = $(PREFIX)/share/doc/lout
+MANDIR = $(PREFIX)/share/man/man1
 
 LIBFONT = font
 LIBMAPS = maps
@@ -295,7 +290,7 @@ LIBLOCA = locale
 CHARIN	= 1
 CHAROUT	= 0
 
-USELOC	= 1
+USELOC	= 0
 LOC_FR	= fr
 LOC_DE	= de
 
