-- PL/Tcl System administrator create table template
-- Author: G.J.R. Timmer
-- Date: 2017/01/28
-- Created from pltcl_loadmod

-- PL/Tcl create table pltcl_modules
create table pltcl_modules (modname name, modseq int2, modsrc text);
create index pltcl_modules_i on pltcl_modules using btree (modname name_ops);

-- PL/Tcl create table pltcl_modfuncs
create table pltcl_modfuncs (funcname name, modname name);
create index pltcl_modfuncs_i on pltcl_modfuncs using hash (funcname name_ops);

-- EOF
