#!/sbin/openrc-run

supervisor=supervise-daemon
name=bordeaux
command="/usr/sbin/bordeaux"
command_args="-d ${DRIVER:-coventry}"
pidfile="/run/bordeaux.pid"
extra_started_commands="reload"

depend() {
        use logger dns
        need net
        after firewall ${DEPENDS:-coventry}
}

stop() {
  ebegin "Stopping ${RC_SVCNAME}"
  start-stop-daemon --signal INT --pidfile "${pidfile}"
  eend $? "Failed to stop ${RC_SVCNAME}"
}

reload() {
  ebegin "Reloading ${RC_SVCNAME}"
  start-stop-daemon --signal HUP --pidfile "${pidfile}"
  eend $?
}

