#!/sbin/openrc-run

name="nmqtt"
description="MQTT Broker"
command="/usr/bin/nmqtt"
command_args="${NMQTT_OPTS:--c /etc/nmqtt/nmqtt.conf}"
command_user="${NMQTT_USER:-nmqtt:nmqtt}"
command_background="yes"
pidfile="/run/${RC_SVCNAME}.pid"
output_log="/var/log/nmqtt/nmqtt.log"
error_log="/var/log/nmqtt/nmqtt.err"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath --directory --owner $command_user --mode 0755 \
		/var/log/nmqtt \
		/var/lib/nmqtt
}
