#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/media-sound/mpd/files/mpd.init,v 1.1 2010/09/10 07:55:07 angelos Exp $

depend() {
	need localmount
	use net netmount nfsmount alsa esound pulseaudio
} 

checkconfig() {
	if ! [ -f /etc/mpd.conf ]; then
		eerror "Configuration file /etc/mpd.conf does not exist."
		return 1
	fi

	return 0
}

start() {
	checkconfig || return 1

	ebegin "Starting Music Player Daemon" 
	start-stop-daemon --start --quiet --background --exec /usr/bin/mpd --pidfile /var/run/mpd.pid --make-pidfile -- --no-daemon /etc/mpd.conf 2>/dev/null
	eend $?
}

stop() {
	ebegin "Stopping Music Player Daemon"
	start-stop-daemon --stop --exec /usr/bin/mpd --pidfile /var/run/mpd.pid
	eend $? 
}
