#!/sbin/runscript

# Sample init.d file for alpine linux.

NAME=pingu
DAEMON=/usr/sbin/$NAME

depend() {
	need net
}

start() {
	ebegin "Starting ${NAME}"
		start-stop-daemon --start --quiet \
			--pidfile /var/run/${NAME}.pid \
			--exec ${DAEMON} --
	eend $?
}

stop() {
	ebegin "Stopping ${NAME}"
		start-stop-daemon --stop --quiet \
			--exec ${DAEMON} \
			--pidfile /var/run/${NAME}.pid
	eend $?
}

