#!/sbin/openrc-run

name="Waydroid Container Manager"
description="Waydroid Container Manager"

pidfile=/run/waydroid-container.pid

command=/usr/bin/waydroid
command_args="container start"
command_args_background="-p $pidfile"

depends() {
	uses net
}

stop() {
	ebegin "Stopping Waydroid container..."
	
	$supervisor $RC_SVCNAME \
		--stop \
		--pidfile $pidfile
	$command container stop
	$command session stop
	eend $?
}
