#!/sbin/runscript

# Sample init.d file for alpine linux.

NAME=prosody
DAEMON=/usr/bin/$NAME

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting ${NAME}"
		/usr/bin/prosodyctl start
#		start-stop-daemon --start --quiet --background \
#			--make-pidfile --pidfile /var/run/${NAME}/${NAME}.pid \
#			--chuid ${USER}:${GROUP} \
#			--exec ${DAEMON} -- ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${NAME}"
		/usr/bin/prosodyctl stop
#		start-stop-daemon --stop --quiet \
#			--exec ${DAEMON} \
#			--pidfile /var/run/${NAME}/${NAME}.pid \
	eend $?
}

reload() {
	ebegin "Reloading ${NAME}"
	if ! service_started "${NAME}" ; then
		eend 1 "${NAME} is not started"
		return 1
	fi
	/usr/bin/prosodyctl stop
	/usr/bin/prosodyctl start
#	start-stop-daemon --stop --oknodo --signal HUP \
#		--exec ${DAEMON} --pidfile /var/run/${NAME}/${NAME}.pid
	eend $?
}

