--- ./Makefile.orig
+++ ./Makefile
@@ -1,5 +1,7 @@
 # Makefile
 prefix ?= /usr/local
+bindir ?= $(prefix)/bin
+mandir ?= $(prefix)/share/man
 version = txt2man-1.5.6
 BIN = src2man bookman txt2man
 MAN1 = src2man.1 txt2man.1 bookman.1
@@ -7,9 +9,9 @@
 all: $(MAN1)
 
 install: $(MAN1)
-	mkdir -p $(prefix)/bin $(prefix)/man/man1
-	cp $(BIN) $(prefix)/bin/
-	cp $(MAN1) $(prefix)/man/man1
+	mkdir -p $(DESTDIR)$(bindir) $(DESTDIR)$(mandir)/man1
+	cp $(BIN) $(DESTDIR)$(bindir)
+	cp $(MAN1) $(DESTDIR)$(mandir)/man1
 
 clean:
 	rm -f *.1 *.txt *.ps *.pdf *.html
