--- src/frotz-2.43d/Makefile	2012-01-03 08:32:58.000000000 +0000
+++ ../Makefile	2014-12-01 13:08:50.390040011 +0000
@@ -14,19 +14,19 @@
 #-malign-jumps=2
 
 # Define where you want Frotz installed.  Usually this is /usr/local
-PREFIX = /usr/local
+PREFIX = /usr
 
-MAN_PREFIX = $(PREFIX)
-#MAN_PREFIX = /usr/local/share
+#MAN_PREFIX = $(PREFIX)
+MAN_PREFIX = /usr/share
 
-CONFIG_DIR = $(PREFIX)/etc
-#CONFIG_DIR = /etc
+#CONFIG_DIR = $(PREFIX)/etc
+CONFIG_DIR = /etc
 
 # Define where you want Frotz to look for frotz.conf.
 #
-CONFIG_DIR = /usr/local/etc
-#CONFIG_DIR = /etc
-#CONFIG_DIR = /usr/pkg/etc
+#CONFIG_DIR = /usr/local/etc
+#CONFIG_DIR = /etc                                                      
+#CONFIG_DIR = /usr/pkg/etc                                                   
 #CONFIG_DIR =
 
 # Uncomment this if you want color support.  Most, but not all curses
@@ -73,15 +73,15 @@
 # curses library won't work, comment out the first option and uncomment
 # the second.
 #
-CURSES = -lcurses
-#CURSES = -lncurses
+#CURSES = -lcurses
+CURSES = -lncurses
 
 # Uncomment this if your need to use ncurses instead of the
 # vendor-supplied curses library.  This just tells the compile process
 # which header to include, so don't worry if ncurses is all you have
 # (like on Linux).  You'll be fine.
 #
-#CURSES_DEF = -DUSE_NCURSES_H
+CURSES_DEF = -DUSE_NCURSES_H
 
 # Uncomment this if you're compiling Unix Frotz on a machine that lacks
 # the memmove(3) system call.  If you don't know what this means, leave it
