#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:

depend() {
	need net
        use logger
	before mta
}

start() {
	ebegin "Starting clapf"
	start-stop-daemon --start --quiet --user clapf --background \
	--exec /usr/sbin/clapf --make-pidfile --pid /var/run/clapf/clapf.pid -- -c /etc/clapf.conf
	eend $?
}

stop() {
	ebegin "Stopping clapf"
	start-stop-daemon --stop --quiet --pidfile /var/run/clapf/clapf.pid
	eend $?
}
