#!/sbin/openrc-run

supervisor=supervise-daemon

name="synapse BitTorrent daemon"
description="Synapse is a flexible and fast BitTorrent daemon"

: ${config:=.config/synapse.toml}
: ${logfile:=/var/log/${RC_SVCNAME}/${RC_SVCNAME}.log}

command="/usr/bin/synapse-bt"
command_user="synapse-bt:synapse-bt"
directory="/var/lib/${RC_SVCNAME}"
error_log="$logfile"

command_args="$command_args -c $config"

depend() {
	need net
	after logger firewall
}

