#!/sbin/openrc-run
name="yggdrasil"
description="An experiment in scalable routing as an encrypted IPv6 overlay network"
supervisor=supervise-daemon
command=/usr/bin/yggdrasil
command_args="-useconffile $yggdrasil_config_file"
output_logger="logger -t '${RC_SVCNAME}' -p daemon.info"
error_logger="logger -t '${RC_SVCNAME}' -p daemon.error"

depend() {
	use logger
	need net
	after firewall
	before radvd
}
