#!/sbin/openrc-run

: ${command_user:="kuma:kuma"}
: ${envoypath:="/usr/bin/envoy"}

name=kuma-dp
description="Kuma data plane proxy"
command="/usr/bin/kuma-dp"
command_args="
	run
	${envoypath:+"--binary-path \"$envoypath\""}
	${logfile:+"--log-output-path \"$logfile\""}
	${command_args:-}
	"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -d -o "$command_user" /var/lib/kuma /var/log/kuma
	if [ -n "$logfile" ]; then
		checkpath -f -m 640 -o "$command_user" "$logfile"
	fi
}
