#!/sbin/openrc-run

name="GmCapsule"
description="Extensible Python-based Gemini/Titan server"

command="/usr/bin/gmcapsuled"
command_args="-c $CONFIGFILE $ARGS"
command_background="yes"
command_user="gmcapsule"
pidfile="/run/$RC_SVCNAME.pid"
output_log="/var/log/gmcapsule/output.log"
error_log="/var/log/gmcapsule/error.log"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath --directory -m 755 -o "gmcapsule:gmcapsule" "/var/log/gmcapsule"
}
