Tests are run in check phase.

--- a/Makefile
+++ b/Makefile
@@ -13,7 +13,6 @@
 
 stringy.so: stringy.o stringy_test.lua
 	$(CC) -shared stringy.o -o $@
-	$(LUA) stringy_test.lua
 
 clean:
 	rm -f stringy.so stringy.o *.rock
