#!/sbin/openrc-run

name="Netflow collector"
description="NetFlow Сollector"
command=/usr/sbin/flowd
command_args="-g"
command_background=yes
pidfile=/run/flowd.pid
required_files=/etc/flowd/flowd.conf
extra_started_commands="reload reopen"
description_reload="Reload configuration"
description_reopen="Reopen log files"

depend() {
	need localmount net
}

reload() {
	ebegin "Reloading ${name:-$RC_SVCNAME}"
	start-stop-daemon --signal HUP --pidfile $pidfile
	eend $?
}

reopen() {
	ebegin "Reopening ${name:-$RC_SVCNAME} log files"
	start-stop-daemon --signal USR1 --pidfile $pidfile
	eend $?
}
