#!/sbin/runscript

depend() {
	need net
}

start() {
	ebegin "Starting PPPOE Server"
	test -x /usr/sbin/pppoe-server -a -f /etc/ppp/pppoe-server-options || exit 0
	start-stop-daemon --start --exec /usr/sbin/pppoe-server -- ${PPPOE_PARAMS}
	echo 1 > /proc/sys/net/ipv4/ip_forward
	eend $?
}

stop () {
	ebegin "Stopping PPPOE Server"
	start-stop-daemon --stop --exec /usr/sbin/pppoe-server
	echo 0 > /proc/sys/net/ipv4/ip_forward
	eend $?
}

restart () {
        ebegin "Restarting PPPOE Server"
        start-stop-daemon --stop --exec /usr/sbin/pppoe-server
        sleep 1
        start-stop-daemon --start --exec /usr/sbin/pppoe-server -- ${PPPOE_PARAMS}
        echo 1 > /proc/sys/net/ipv4/ip_forward
        echo "."
}

