#!/sbin/openrc-run

command="/usr/bin/scream-alsa"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"

command_args="-p ${SCREAM_PORT} -t ${SCREAM_LATENCY} -o ${SCREAM_DEVICE}"

if [ "${SCREAM_MULTICAST}" = "yes" ]; then
	command_args="${command_args} -g ${SCREAM_MULTICAST_GROUP}"
else
	command_args="${command_args} -u"
fi

if [ ! -z "${SCREAM_INTERFACE}" ]; then
	command_args="${command_args} -i ${SCREAM_INTERFACE}"
fi

depend() {
	need net alsa
}
