#!/sbin/openrc-run

name="bind_exporter"
description="bind exporter for the prometheus monitoring system"
supervisor=supervise-daemon
command=/usr/bin/bind_exporter
command_args="$bind_exporter_args"
command_user="prometheus:prometheus"

start_pre() {
	[ -n "$output_log" ] && checkpath -f "$output_log" \
		-m 644 -o prometheus:prometheus
	[ -n "$error_log" ] && checkpath -f "$error_log" \
		-m 644 -o prometheus:prometheus
}
