#!/sbin/openrc-run
# Copyright 2016-2026 Laurent Bercot
# Distributed under the terms of the ISC License.

# We currently start the s6 supervision tree as an
# openrc service. It's using ssd for now; we may
# switch to supervise-daemon later.

name="s6"
command="s6-svscanboot"
command_args="-c /dev/console -l catchlog -o t -d4 /run/service"
pidfile="/run/s6.pid"
start_stop_daemon_args="-b -m -k 022"
notify=fd:4
