#!/sbin/openrc-run

name="Hister"
description="Your own search engine"

command="/usr/bin/hister"
command_args="listen --config /etc/hister.yml"

command_user=hister:hister
command_background=true

output_logger="logger -t $RC_SVCNAME -p daemon.info"
error_logger="logger -t $RC_SVCNAME -p daemon.error"

pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need net
	after firewall
}

start_pre() {
  export NO_COLOR="1"

  [ -n "$HISTER_DATA_DIR" ] && checkpath --directory --owner "$command_user" --mode 0750 "$HISTER_DATA_DIR"
}
