--- ./src/lua-subprocess-20121211/Makefile
+++ ./Makefile
@@ -36,7 +36,8 @@
 
 .PHONY: install
 install: subprocess.so
-	$(INSTALL) -m755 subprocess.so $(INSTALL_CMOD)/
+	mkdir -p $(DESTDIR)$(INSTALL_CMOD)/
+	$(INSTALL) -m755 subprocess.so $(DESTDIR)$(INSTALL_CMOD)/
 
 .PHONY: uninstall
 uninstall:
