#!/sbin/openrc-run

output_log="${output_log:-/dev/null}"
error_log="${error_log:-/var/log/tempo-vulture/error.log}"

name="${name:-Tempo Vulture}"
command="/usr/bin/tempo-vulture"
command_args="${TEMPO_VULTURE_OPTS}"
command_user="${command_user:-root:root}"
command_background=yes
make_pidfile=yes
pidfile="/run/${RC_SVCNAME}.pid"
start_stop_daemon_args="${SSD_OPTS}
	-1 ${output_log} -2 ${error_log}"

depend() {
	need net
}

start_pre() {
	checkpath -d -m 0750 -o "${command_user}" "/var/log/tempo-vulture"
}

