#!/sbin/openrc-run

name="agate"
command="/usr/bin/agate"
command_user="agate:agate"
command_background=true
pidfile="/run/$RC_SVCNAME.pid"

command_args="--content '$content_path' --certs '$certificate_path' --hostname '$hostname'"

depend() {
    need net localmount
    after firewall
}

start_pre() {
    checkpath -f "$output_log" -o "$command_user"
    checkpath -f "$error_log" -o "$command_user"
    checkpath -d "$content_path" -o "$command_user"
    checkpath -d "$certificate_path" -o "$command_user"
}
