#!/sbin/openrc-run
supervisor=supervise-daemon

name="System login manager"
description="System service that manages user logins"
description_reload="Reload configuration without exiting"

command=/usr/libexec/elogind/elogind

depend() {
	need dbus cgroups

	# Make sure we start before any other display manager
	before display-manager
}

extra_started_commands="reload"

reload() {
	ebegin "Reloading configuration"
	$supervisor $RC_SVCNAME --signal HUP
	eend $?
}
