#!/sbin/openrc-run
supervisor=supervise-daemon

description="Nginx http and reverse proxy server"
extra_started_commands="reload reopen upgrade"

cfgfile=${cfgfile:-/etc/nginx/nginx.conf}
pidfile=/run/nginx/$RC_SVCNAME.sd.pid
command=/usr/sbin/nginx
command_args="-c $cfgfile"
command_args_foreground='-g "daemon off;"'
required_files="$cfgfile"

depend() {
	need net
	use dns logger netmount
}

start_pre() {
	ebegin
	checkpath --directory --owner nginx:nginx ${pidfile%/*}
	$command $command_args -t -q
	eend $?
}

reload() {
	ebegin "Reloading ${RC_SVCNAME} configuration"
	start_pre && $command -s reload
	eend $?
}

reopen() {
	ebegin "Reopening ${RC_SVCNAME} log files"
	$command -s reopen
	eend $?
}

upgrade() {
	restart
}

restart() {
	stop
	# prevents bind() failed (98: Address in use) error msg
	sleep 0.05
	start
}
