#!/sbin/openrc-run

description="HOMER App and UI"
supervisor=supervise-daemon
command=/usr/bin/homer-app
command_args="-webapp-config-path=/etc/homer -webapp-log-path /var/log/homer"
command_user=homer
command_group=homer
pidfile="/run/homer/${RC_SVCNAME}.pid"

depend() {
	need net
	after firewall
	want postgresql
}

start_pre() {
	checkpath --directory --owner $command_user:$command_group ${pidfile%/*} /var/log/homer
}
