#!/sbin/openrc-run
supervisor=supervise-daemon

command="/usr/bin/alertmanager-irc-relay"
command_args="$ARGS"
command_background="yes"
group="alertmanager-irc-relay"
user="alertmanager-irc-relay"

logdir="/var/log/alertmanager-irc-relay"
logfile="$logdir/${SVCNAME}.log"
pidfile="/var/run/${SVCNAME}.pid"
start_stop_daemon_args="--stderr $logfile --user $user --group $group"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -d -o $user:$group -m755 $logdir
	checkpath -f -o $user:$group -m644 $logfile
}
