#!/sbin/openrc-run

NAME=vsftpd
DAEMON=/usr/sbin/$NAME

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting ${SVCNAME}"
		start-stop-daemon --start --quiet --background \
			--make-pidfile --pidfile /var/run/${SVCNAME}.pid \
			--exec ${DAEMON} -- ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
		start-stop-daemon --stop --quiet \
			--exec ${DAEMON} \
			--pidfile /var/run/${SVCNAME}.pid \
	eend $?
}

