diff --git a/Makefile b/Makefile
index 0e66003..3269166 100644
--- a/Makefile
+++ b/Makefile
@@ -25,7 +25,7 @@ upxbuild:
 	${DOCKERRUN} ash -c "apk add --no-cache git upx libc-dev gcc && GO111MODULE=on go mod download && ${GOBUILD} -o bin/${BINNAME} github.com/bjwschaap/alpine-lift/cmd/lift && ${UPX}"
 
 localbuild:
-	${GOBUILD} -v -race -o bin/${BINNAME} github.com/bjwschaap/alpine-lift/cmd/lift
+	${GOBUILD} -v -o bin/${BINNAME} github.com/bjwschaap/alpine-lift/cmd/lift
 
 upx:
 	${UPX}
