#!/sbin/runscript

daemon=/usr/sbin/sems
pidfile=/var/run/sems/sems.pid
conffile=/etc/sems/sems.conf

depend() {
	need net
	after firewall
}

start() {
	ebegin "Starting sems"
	start-stop-daemon --start --quiet --pidfile $pidfile --exec $daemon \
		-- \
		-u sems \
		-g sems \
		-P $pidfile \
		-f $conffile
	eend $?
}

stop() {
	ebegin "Stopping sems"
	start-stop-daemon --stop --quiet --pidfile $pidfile
	eend $?
}
