#!/sbin/runscript
# quasselcore init.d file for alpine linux.

QUASSEL_CONFIG=/etc/config.d/quassel-core
DAEMON=/usr/bin/quassel-core
ACCOUNT=quassel
PID=/var/run/quassel-core.pid

# Load defaults
. /etc/default.d/quassel-core

# Load specific configuration
if [ -e ${QUASSEL_CONFIG} ] ; then
    . ${QUASSEL_CONFIG}
fi

depend() {
    need net
    after firewall
}

start() {
    ebegin "Starting quasselcore"
        start-stop-daemon --start \
            --pidfile ${PID} \
            --make-pidfile \
            --background \
            --user ${ACCOUNT} \
            --exec ${DAEMON} -- \
                --logfile=${QUASSEL_CORE_LOG_FILE} \
                --loglevel=${QUASSEL_CORE_LOG_LEVEL} \
                --configdir=${QUASSEL_CORE_DATADIR} \
                --port=${QUASSEL_CORE_PORT} \
                ${QUASSEL_CORE_DAEMON_OPTS}
    eend $?
}

stop() {
    ebegin "Stopping quasselcore"
        start-stop-daemon --stop --pidfile ${PID}
    eend $?
}
